# Pilot Analysis: Game Evidence Graph

This notebook is for asking early research/design questions against the generated datasets. Start with deterministic table queries. Use the optional LLM synthesis section only when you want prose answers over selected evidence rows.

## 1. Setup

In [1]:
from __future__ import annotations

import json
import os
import sys
from pathlib import Path

import pandas as pd

pd.set_option("display.max_columns", 100)
pd.set_option("display.max_colwidth", 220)

def find_project_root(start: Path | None = None) -> Path:
    start = (start or Path.cwd()).resolve()
    for candidate in [start, *start.parents]:
        if (candidate / "pyproject.toml").exists() and (candidate / "src/game_evidence_graph").exists():
            return candidate
    raise RuntimeError("Could not find project root. Launch Jupyter from the repo or notebooks directory.")

PROJECT_ROOT = find_project_root()
SRC_DIR = PROJECT_ROOT / "src"
DATA_DIR = PROJECT_ROOT / "data" / "processed"

if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

print("PROJECT_ROOT:", PROJECT_ROOT)
print("DATA_DIR:", DATA_DIR)

PROJECT_ROOT: /Users/srishtisaha/Desktop/infinite_lives/game-evidence-graph
DATA_DIR: /Users/srishtisaha/Desktop/infinite_lives/game-evidence-graph/data/processed

## 2. Load Data

In [2]:
df = pd.read_csv(DATA_DIR / "mechanic_intervention_dataset.csv")
edges = pd.read_csv(DATA_DIR / "evidence_edge_table.csv")
study_ontology = json.loads((DATA_DIR / "study_ontology.json").read_text())
game_ontology = json.loads((DATA_DIR / "game_ontology.json").read_text())

print("Dataset C rows:", len(df))
print("Supported evidence rows:", int(df["is_supported_evidence"].astype(bool).sum()))
print("Evidence graph edges:", len(edges))
print("Games:", len(game_ontology.get("games", [])))

Dataset C rows: 5159
Supported evidence rows: 3964
Evidence graph edges: 3964
Games: 381

## 3. Core Query Helpers

In [3]:
ANSWER_COLS = [
    "paper_id",
    "paper_title",
    "year",
    "game_name",
    "mechanic_name",
    "population_raw",
    "study_design",
    "outcome_canonical",
    "outcome_category",
    "effect_direction",
    "effect_size_raw",
    "p_value",
    "evidence_strength",
    "edge_weight",
    "source_quote",
    "review_status",
]

def supported(data: pd.DataFrame = df) -> pd.DataFrame:
    return data[data["is_supported_evidence"].astype(bool)].copy()

def contains(series: pd.Series, term: str) -> pd.Series:
    return series.astype(str).str.contains(term, case=False, na=False, regex=False)

def search_evidence(
    term: str | None = None,
    *,
    game: str | None = None,
    mechanic: str | None = None,
    outcome: str | None = None,
    category: str | None = None,
    effect: str | None = None,
    require_supported: bool = True,
    n: int = 25,
) -> pd.DataFrame:
    data = supported(df) if require_supported else df.copy()
    mask = pd.Series(True, index=data.index)

    if term:
        term_mask = pd.Series(False, index=data.index)
        for col in ["paper_title", "game_name", "mechanic_name", "outcome_raw", "outcome_canonical", "outcome_category", "source_quote"]:
            if col in data:
                term_mask = term_mask | contains(data[col], term)
        mask &= term_mask
    if game:
        mask &= contains(data["game_name"], game)
    if mechanic:
        mask &= contains(data["mechanic_name"], mechanic)
    if outcome:
        mask &= contains(data["outcome_canonical"], outcome) | contains(data["outcome_raw"], outcome)
    if category:
        mask &= contains(data["outcome_category"], category)
    if effect:
        mask &= data["effect_direction"].astype(str).str.lower().eq(effect.lower())

    result = data.loc[mask, [col for col in ANSWER_COLS if col in data.columns]].copy()
    if "edge_weight" in result:
        result = result.sort_values("edge_weight", ascending=False)
    return result.head(n)

def summarize_counts(data: pd.DataFrame) -> pd.DataFrame:
    if data.empty:
        return pd.DataFrame()
    return pd.DataFrame(
        {
            "rows": [len(data)],
            "papers": [data["paper_id"].nunique()],
            "games": [data["game_name"].nunique(dropna=True)],
            "mechanics": [data["mechanic_name"].nunique(dropna=True)],
            "outcomes": [data["outcome_canonical"].nunique(dropna=True)],
            "positive": [(data["effect_direction"] == "positive").sum()],
            "negative": [(data["effect_direction"] == "negative").sum()],
            "mixed": [(data["effect_direction"] == "mixed").sum()],
            "null": [(data["effect_direction"] == "null").sum()],
        }
    )

## 4. Candidate Pilot Questions

These are good first-pass questions because they map cleanly onto the structured fields.

In [4]:
pilot_questions = [
    "Which game mechanics have positive evidence for neuro/cognitive outcomes?",
    "What evidence links movement-control or gesture-input games to physiological outcomes?",
    "What evidence exists for Minecraft or cooperative play improving social outcomes?",
    "What evidence links first-person shooter/action video games to aggression or affective outcomes?",
    "Which named games appear most often in supported evidence rows?",
    "Which supported claims have the strongest edge weights?",
    "Where do we have null-game rows, and are those correctly generic studies?",
]

for i, question in enumerate(pilot_questions, start=1):
    print(f"{i}. {question}")

1. Which game mechanics have positive evidence for neuro/cognitive outcomes?
2. What evidence links movement-control or gesture-input games to physiological outcomes?
3. What evidence exists for Minecraft or cooperative play improving social outcomes?
4. What evidence links first-person shooter/action video games to aggression or affective outcomes?
5. Which named games appear most often in supported evidence rows?
6. Which supported claims have the strongest edge weights?
7. Where do we have null-game rows, and are those correctly generic studies?

## 5. Query 1: Mechanics With Positive Neuro/Cognitive Evidence

In [5]:
q1 = search_evidence(category="Neuro", effect="positive", n=50)
display(summarize_counts(q1))
display(q1)

   rows  papers  games  mechanics  outcomes  positive  negative  mixed  null
0    50       9     17          8        14        50         0      0     0

,paper_id,paper_title,year,game_name,mechanic_name,population_raw,study_design,outcome_canonical,outcome_category,effect_direction,effect_size_raw,p_value,evidence_strength,edge_weight,source_quote,review_status
5083,paper_302,Short‑Term Effects of Video‑Games on Cognitive Enhancement:,2021,fighting video-game,not_reported,healthy young adults,randomized_controlled_trial,single word reading and pseudoword reading improvement associated with play-driven biochemical activation,Neuro/Cognitive,positive,not_reported,not_reported,randomized_controlled_trial,0.2250,play-driven biochemical activation boosted single word and pseudoword reading.,needs_review
3301,paper_191,This is an open access article under the CC BY-NC-ND license (https://creativecommons.org/licenses/by-nc-nd/4.0) Peer-review under responsibility of the scientific committee of the 5th International Conference on Com...,2021,not_reported,not_reported,"Participants were generally people who don’t play video games naturally, split into 2 random groups.",randomized_controlled_trial,improvement in target cognitive tasks,neurocognitive,positive,not_reported,not_reported,randomized_controlled_trial,0.2250,"An experiment conducted with pre-testing and post-testing. Participants were generally people who don’t play video games naturally, split into 2 random groups. One group play action video game for 10 – 50 hours, with...",needs_review
4039,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,Kinect Sports,Movement Control,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,randomized_controlled_trial,Selective visual attention (Go/No-go task),Attention / Neurocognitive,positive,not_reported,<0.01,randomized_controlled_trial,0.2250,Selective attention improved significantly in the VGT group (p < 0.01).,needs_review
4038,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,Kinect Sports,Sports Simulation,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,randomized_controlled_trial,Selective visual attention (Go/No-go task),Attention / Neurocognitive,positive,not_reported,<0.01,randomized_controlled_trial,0.2250,Selective attention improved significantly in the VGT group (p < 0.01).,needs_review
4037,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,Kinect Sports,Gesture Input,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,randomized_controlled_trial,Selective visual attention (Go/No-go task),Attention / Neurocognitive,positive,not_reported,<0.01,randomized_controlled_trial,0.2250,Selective attention improved significantly in the VGT group (p < 0.01).,needs_review
4024,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,Kinect Adventures,Movement Control,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,randomized_controlled_trial,Selective visual attention (Go/No-go task),Attention / Neurocognitive,positive,not_reported,<0.01,randomized_controlled_trial,0.2250,Selective attention improved significantly in the VGT group (p < 0.01).,needs_review
4023,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,Kinect Adventures,Sports Simulation,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,randomized_controlled_trial,Selective visual attention (Go/No-go task),Attention / Neurocognitive,positive,not_reported,<0.01,randomized_controlled_trial,0.2250,Selective attention improved significantly in the VGT group (p < 0.01).,needs_review
4022,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,Kinect Adventures,Gesture Input,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,randomized_controlled_trial,Selective visual attention (Go/No-go task),Attention / Neurocognitive,positive,not_reported,<0.01,randomized_controlled_trial,0.2250,Selective attention improved significantly in the VGT group (p < 0.01).,needs_review
4009,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,X-Box 360 Kinect,Movement Control,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,randomized_controlled_trial,Selective visual attention (Go/No-go task),Attention / Neurocognitive,positive,not_reported,<0.01,randomized_controlled_trial,0.2250,Selective attention improved significantly in the VGT group (p < 0.01).,needs_review
4008,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,X-Box 360 Kinect,Sports Simulation,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,randomized_controlled_trial,Selective visual attention (Go/No-go task),Attention / Neurocognitive,positive,not_reported,<0.01,randomized_controlled_trial,0.2250,Selective attention improved significantly in the VGT group (p < 0.01).,needs_review
4007,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,X-Box 360 Kinect,Gesture Input,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,randomized_controlled_trial,Selective visual attention (Go/No-go task),Attention / Neurocognitive,positive,not_reported,<0.01,randomized_controlled_trial,0.2250,Selective attention improved significantly in the VGT group (p < 0.01).,needs_review
3303,paper_191,This is an open access article under the CC BY-NC-ND license (https://creativecommons.org/licenses/by-nc-nd/4.0) Peer-review under responsibility of the scientific committee of the 5th International Conference on Com...,2021,not_reported,not_reported,"Participants were generally people who don’t play video games naturally, split into 2 random groups.",randomized_controlled_trial,improvement in target cognitive tasks,neurocognitive,positive,not_reported,not_reported,randomized_controlled_trial,0.2250,"An experiment conducted with pre-testing and post-testing. Participants were generally people who don’t play video games naturally, split into 2 random groups. One group play action video game for 10 – 50 hours, with...",needs_review
4044,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,Biodex balance platform,not_reported,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,randomized_controlled_trial,Selective visual attention (Go/No-go task),Attention / Neurocognitive,positive,not_reported,<0.01,randomized_controlled_trial,0.2250,Selective attention improved significantly in the VGT group (p < 0.01).,needs_review
5068,paper_302,Short‑Term Effects of Video‑Games on Cognitive Enhancement:,2021,shooting video-game,not_reported,children with developmental coordination disorder and dyslexia,randomized_controlled_trial,visual perception (breadth/global),Neuro/Cognitive,positive,not_reported,not_reported,randomized_controlled_trial,0.2250,The funnier and more activating game enhanced breadth of visual perception and reduced sensorimotor and reading disorders.,needs_review
5082,paper_302,Short‑Term Effects of Video‑Games on Cognitive Enhancement:,2021,fighting video-game,not_reported,healthy young adults,randomized_controlled_trial,contextual reading (reading in context) improvement correlated with changes in positive emotions,Neuro/Cognitive,positive,not_reported,not_reported,randomized_controlled_trial,0.2250,"regardless of game characteristics, changes in positive emotions correlated with contextual reading enhancement",needs_review
5081,paper_302,Short‑Term Effects of Video‑Games on Cognitive Enhancement:,2021,shooting video-game,not_reported,healthy young adults,randomized_controlled_trial,single word reading and pseudoword reading improvement associated with play-driven biochemical activation,Neuro/Cognitive,positive,not_reported,not_reported,randomized_controlled_trial,0.2250,play-driven biochemical activation boosted single word and pseudoword reading.,needs_review
5080,paper_302,Short‑Term Effects of Video‑Games on Cognitive Enhancement:,2021,shooting video-game,not_reported,healthy young adults,randomized_controlled_trial,contextual reading (reading in context) improvement correlated with changes in positive emotions,Neuro/Cognitive,positive,not_reported,not_reported,randomized_controlled_trial,0.2250,"regardless of game characteristics, changes in positive emotions correlated with contextual reading enhancement",needs_review
5075,paper_302,Short‑Term Effects of Video‑Games on Cognitive Enhancement:,2021,puzzle video-game,Targeting,children with developmental coordination disorder and dyslexia,randomized_controlled_trial,sensorimotor performance / reduction in sensorimotor disorder measures,Neuro/Cognitive,positive,not_reported,not_reported,randomized_controlled_trial,0.2250,The funnier and more activating game enhanced breadth of visual perception and reduced sensorimotor and reading disorders.,needs_review
5074,paper_302,Short‑Term Effects of Video‑Games on Cognitive Enhancement:,2021,puzzle video-game,Puzzle Solving,children with developmental coordination disorder and dyslexia,randomized_controlled_trial,sensorimotor performance / reduction in sensorimotor disorder measures,Neuro/Cognitive,positive,not_reported,not_reported,randomized_controlled_trial,0.2250,The funnier and more activating game enhanced breadth of visual perception and reduced sensorimotor and reading disorders.,needs_review
5073,paper_302,Short‑Term Effects of Video‑Games on Cognitive Enhancement:,2021,puzzle video-game,Targeting,children with developmental coordination disorder and dyslexia,randomized_controlled_trial,visual perception (breadth/global),Neuro/Cognitive,positive,not_reported,not_reported,randomized_controlled_trial,0.2250,The funnier and more activating game enhanced breadth of visual perception and reduced sensorimotor and reading disorders.,needs_review
5069,paper_302,Short‑Term Effects of Video‑Games on Cognitive Enhancement:,2021,shooting video-game,not_reported,children with developmental coordination disorder and dyslexia,randomized_controlled_trial,sensorimotor performance / reduction in sensorimotor disorder measures,Neuro/Cognitive,positive,not_reported,not_reported,randomized_controlled_trial,0.2250,The funnier and more activating game enhanced breadth of visual perception and reduced sensorimotor and reading disorders.,needs_review
5072,paper_302,Short‑Term Effects of Video‑Games on Cognitive Enhancement:,2021,puzzle video-game,Puzzle Solving,children with developmental coordination disorder and dyslexia,randomized_controlled_trial,visual perception (breadth/global),Neuro/Cognitive,positive,not_reported,not_reported,randomized_controlled_trial,0.2250,The funnier and more activating game enhanced breadth of visual perception and reduced sensorimotor and reading disorders.,needs_review
1164,paper_042,Enriching hippocampal memory function in older adults through video games,2020,Solitaire,not_reported,"In total, 51 cognitively normal older adults (38 female, 13 male; mean age: 68.52 years, SD: 5.87; mean education: 16.53 years, SD: 2.25) completed the study.",quasi_experimental,lure discrimination index (LDI) from the Mnemonic Similarity Task (hippocampal-based memory),Neuro/Cognitive,positive,not_reported,not_reported,quasi_experimental,0.1687,"Performance in the hippocampal-mediated lure discrimination index (LDI) at pre-test (0-week) and post-test time points (2-week, 4-week, and 8-week), for all groups.",needs_review
1153,paper_042,Enriching hippocampal memory function in older adults through video games,2020,Angry Birds,Targeting,"In total, 51 cognitively normal older adults (38 female, 13 male; mean age: 68.52 years, SD: 5.87; mean education: 16.53 years, SD: 2.25) completed the study.",quasi_experimental,lure discrimination index (LDI) from the Mnemonic Similarity Task (hippocampal-based memory),Neuro/Cognitive,positive,not_reported,not_reported,quasi_experimental,0.1687,"Performance in the hippocampal-mediated lure discrimination index (LDI) at pre-test (0-week) and post-test time points (2-week, 4-week, and 8-week), for all groups.",needs_review
1166,paper_042,Enriching hippocampal memory function in older adults through video games,2020,Solitaire,not_reported,"In total, 51 cognitively normal older adults (38 female, 13 male; mean age: 68.52 years, SD: 5.87; mean education: 16.53 years, SD: 2.25) completed the study.",quasi_experimental,hippocampal-based memory (interpreted improvement after intervention),Neuro/Cognitive,positive,not_reported,not_reported,quasi_experimental,0.1687,"Here, we replicated our previous video game study in healthy older adults, showing that playing video games for four weeks can improve hippocampal-based memory in a population that is already experiencing age-related...",needs_review
1160,paper_042,Enriching hippocampal memory function in older adults through video games,2020,Super Mario 3D World,not_reported,"In total, 51 cognitively normal older adults (38 female, 13 male; mean age: 68.52 years, SD: 5.87; mean education: 16.53 years, SD: 2.25) completed the study.",quasi_experimental,hippocampal-based memory (interpreted improvement after intervention),Neuro/Cognitive,positive,not_reported,not_reported,quasi_experimental,0.1687,"Here, we replicated our previous video game study in healthy older adults, showing that playing video games for four weeks can improve hippocampal-based memory in a population that is already experiencing age-related...",needs_review
1163,paper_042,Enriching hippocampal memory function in older adults through video games,2020,Nintendo Wii U,not_reported,"In total, 51 cognitively normal older adults (38 female, 13 male; mean age: 68.52 years, SD: 5.87; mean education: 16.53 years, SD: 2.25) completed the study.",quasi_experimental,hippocampal-based memory (interpreted improvement after intervention),Neuro/Cognitive,positive,not_reported,not_reported,quasi_experimental,0.1687,"Here, we replicated our previous video game study in healthy older adults, showing that playing video games for four weeks can improve hippocampal-based memory in a population that is already experiencing age-related...",needs_review
1161,paper_042,Enriching hippocampal memory function in older adults through video games,2020,Nintendo Wii U,not_reported,"In total, 51 cognitively normal older adults (38 female, 13 male; mean age: 68.52 years, SD: 5.87; mean education: 16.53 years, SD: 2.25) completed the study.",quasi_experimental,lure discrimination index (LDI) from the Mnemonic Similarity Task (hippocampal-based memory),Neuro/Cognitive,positive,not_reported,not_reported,quasi_experimental,0.1687,"Performance in the hippocampal-mediated lure discrimination index (LDI) at pre-test (0-week) and post-test time points (2-week, 4-week, and 8-week), for all groups.",needs_review
4902,paper_292,"Developmental Dyslexia (Tn Wydell, Section Editor)",2015,action video game,Movement Control,children with DD,quasi_experimental,visual attention / visual attention span,Neuro/Cognitive,positive,not_reported,not_reported,quasi_experimental,0.1687,Franceschini et al. [100•] showed a direct effect of the AVG training on the spotlight of attention in children with DD. An improvement in the distribution and allocation of visuo-spatial attention was obtained in th...,needs_review
1158,paper_042,Enriching hippocampal memory function in older adults through video games,2020,Super Mario 3D World,not_reported,"In total, 51 cognitively normal older adults (38 female, 13 male; mean age: 68.52 years, SD: 5.87; mean education: 16.53 years, SD: 2.25) completed the study.",quasi_experimental,lure discrimination index (LDI) from the Mnemonic Similarity Task (hippocampal-based memory),Neuro/Cognitive,positive,not_reported,not_reported,quasi_experimental,0.1687,"Performance in the hippocampal-mediated lure discrimination index (LDI) at pre-test (0-week) and post-test time points (2-week, 4-week, and 8-week), for all groups.",needs_review
1152,paper_042,Enriching hippocampal memory function in older adults through video games,2020,Angry Birds,Puzzle Solving,"In total, 51 cognitively normal older adults (38 female, 13 male; mean age: 68.52 years, SD: 5.87; mean education: 16.53 years, SD: 2.25) completed the study.",quasi_experimental,lure discrimination index (LDI) from the Mnemonic Similarity Task (hippocampal-based memory),Neuro/Cognitive,positive,not_reported,not_reported,quasi_experimental,0.1687,"Performance in the hippocampal-mediated lure discrimination index (LDI) at pre-test (0-week) and post-test time points (2-week, 4-week, and 8-week), for all groups.",needs_review
4143,paper_264,Commercial video games and cognitive functions: video game genres and modulating factors of cognitive enhancement,2020,NaN,not_reported,"ChildrenSPD (N = 10), ​childrenSPD+ADHD(N = 17), TDC(N = 20)",quasi_experimental,improved cognitive control (attention); persistent improvement reported by parents,Neuro/Cognitive,positive,not_reported,not_reported,quasi_experimental,0.1687,Improved cognitive control in all children but greater enhancement in ​childrenSPD+ADHD showing more attentional deficits than other two groups of children; the persistent training effect found based on parental repo...,needs_review
4903,paper_292,"Developmental Dyslexia (Tn Wydell, Section Editor)",2015,non-action video game,Combat,children with DD,quasi_experimental,visual attention / visual attention span,Neuro/Cognitive,positive,not_reported,not_reported,quasi_experimental,0.1687,Franceschini et al. [100•] showed a direct effect of the AVG training on the spotlight of attention in children with DD. An improvement in the distribution and allocation of visuo-spatial attention was obtained in th...,needs_review
2614,paper_154,Enhancing Attentional Control: Lessons from Action Video Games,2019,NaN,not_reported,"players of a lab-designed video game that contained rewards outperformed individuals playing the same game without rewards on a declarative memory task (Prena et al., 2018).",quasi_experimental,declarative memory performance,Neuro/Cognitive,positive,not_reported,not_reported,quasi_experimental,0.1687,"players of a lab-designed video game that contained rewards outperformed individuals playing the same game without rewards on a declarative memory task (Prena et al., 2018).",needs_review

In [6]:
display(
    q1.groupby(["mechanic_name", "outcome_canonical", "effect_direction"], dropna=False)
    .agg(rows=("paper_id", "size"), papers=("paper_id", "nunique"), mean_edge_weight=("edge_weight", "mean"))
    .sort_values(["papers", "rows", "mean_edge_weight"], ascending=False)
    .head(30)
)

                                                                                                                                              rows  \
mechanic_name     outcome_canonical                                                                                         effect_direction
Gesture Input     Selective visual attention (Go/No-go task)                                                                positive             3
Movement Control  Selective visual attention (Go/No-go task)                                                                positive             3
Sports Simulation Selective visual attention (Go/No-go task)                                                                positive             3
not_reported      hippocampal-based memory (interpreted improvement after intervention)                                     positive             3
                  lure discrimination index (LDI) from the Mnemonic Similarity Task (hippocampal-based memory)              positive             3
                  contextual reading (reading in context) improvement correlated with changes in positive emotions          positive             2
                  improvement in target cognitive tasks                                                                     positive             2
                  single word reading and pseudoword reading improvement associated with play-driven biochemical activation positive             2
Combat            visual attention / visual attention span                                                                  positive             2
Movement Control  visual attention / visual attention span                                                                  positive             2
Rapid Response    visual attention / visual attention span                                                                  positive             2
Targeting         visual attention / visual attention span                                                                  positive             2
not_reported      declarative memory performance                                                                            positive             2
                  EEG theta band power (frontal regions)                                                                    positive             2
                  P2 component latency (occipito-temporal)                                                                  positive             2
Puzzle Solving    sensorimotor performance / reduction in sensorimotor disorder measures                                    positive             1
                  visual perception (breadth/global)                                                                        positive             1
Targeting         sensorimotor performance / reduction in sensorimotor disorder measures                                    positive             1
                  visual perception (breadth/global)                                                                        positive             1
not_reported      Selective visual attention (Go/No-go task)                                                                positive             1
                  sensorimotor performance / reduction in sensorimotor disorder measures                                    positive             1
                  visual perception (breadth/global)                                                                        positive             1
Puzzle Solving    hippocampal-based memory (interpreted improvement after intervention)                                     positive             1
                  lure discrimination index (LDI) from the Mnemonic Similarity Task (hippocampal-based memory)              positive             1
Targeting         hippocampal-based memory (interpreted improvement after intervention)                                     positive             1
                  lure discrimination index (LDI) from the Mnemonic Similarity Task (hippocampal-based memory)              positive             1
not_reported      improved cognitive control (attention); persistent improvement reported by parents                        positive             1
Combat            visual crowding                                                                                           positive             1
Movement Control  visual crowding                                                                                           positive             1
Rapid Response    visual crowding                                                                                           positive             1

                                                                                                                                              papers  \
mechanic_name     outcome_canonical                                                                                         effect_direction
Gesture Input     Selective visual attention (Go/No-go task)                                                                positive               1
Movement Control  Selective visual attention (Go/No-go task)                                                                positive               1
Sports Simulation Selective visual attention (Go/No-go task)                                                                positive               1
not_reported      hippocampal-based memory (interpreted improvement after intervention)                                     positive               1
                  lure discrimination index (LDI) from the Mnemonic Similarity Task (hippocampal-based memory)              positive               1
                  contextual reading (reading in context) improvement correlated with changes in positive emotions          positive               1
                  improvement in target cognitive tasks                                                                     positive               1
                  single word reading and pseudoword reading improvement associated with play-driven biochemical activation positive               1
Combat            visual attention / visual attention span                                                                  positive               1
Movement Control  visual attention / visual attention span                                                                  positive               1
Rapid Response    visual attention / visual attention span                                                                  positive               1
Targeting         visual attention / visual attention span                                                                  positive               1
not_reported      declarative memory performance                                                                            positive               1
                  EEG theta band power (frontal regions)                                                                    positive               1
                  P2 component latency (occipito-temporal)                                                                  positive               1
Puzzle Solving    sensorimotor performance / reduction in sensorimotor disorder measures                                    positive               1
                  visual perception (breadth/global)                                                                        positive               1
Targeting         sensorimotor performance / reduction in sensorimotor disorder measures                                    positive               1
                  visual perception (breadth/global)                                                                        positive               1
not_reported      Selective visual attention (Go/No-go task)                                                                positive               1
                  sensorimotor performance / reduction in sensorimotor disorder measures                                    positive               1
                  visual perception (breadth/global)                                                                        positive               1
Puzzle Solving    hippocampal-based memory (interpreted improvement after intervention)                                     positive               1
                  lure discrimination index (LDI) from the Mnemonic Similarity Task (hippocampal-based memory)              positive               1
Targeting         hippocampal-based memory (interpreted improvement after intervention)                                     positive               1
                  lure discrimination index (LDI) from the Mnemonic Similarity Task (hippocampal-based memory)              positive               1
not_reported      improved cognitive control (attention); persistent improvement reported by parents                        positive               1
Combat            visual crowding                                                                                           positive               1
Movement Control  visual crowding                                                                                           positive               1
Rapid Response    visual crowding                                                                                           positive               1

                                                                                                                                              mean_edge_weight
mechanic_name     outcome_canonical                                                                                         effect_direction
Gesture Input     Selective visual attention (Go/No-go task)                                                                positive                    0.2250
Movement Control  Selective visual attention (Go/No-go task)                                                                positive                    0.2250
Sports Simulation Selective visual attention (Go/No-go task)                                                                positive                    0.2250
not_reported      hippocampal-based memory (interpreted improvement after intervention)                                     positive                    0.1687
                  lure discrimination index (LDI) from the Mnemonic Similarity Task (hippocampal-based memory)              positive                    0.1687
                  contextual reading (reading in context) improvement correlated with changes in positive emotions          positive                    0.2250
                  improvement in target cognitive tasks                                                                     positive                    0.2250
                  single word reading and pseudoword reading improvement associated with play-driven biochemical activation positive                    0.2250
Combat            visual attention / visual attention span                                                                  positive                    0.1687
Movement Control  visual attention / visual attention span                                                                  positive                    0.1687
Rapid Response    visual attention / visual attention span                                                                  positive                    0.1687
Targeting         visual attention / visual attention span                                                                  positive                    0.1687
not_reported      declarative memory performance                                                                            positive                    0.1687
                  EEG theta band power (frontal regions)                                                                    positive                    0.1575
                  P2 component latency (occipito-temporal)                                                                  positive                    0.1575
Puzzle Solving    sensorimotor performance / reduction in sensorimotor disorder measures                                    positive                    0.2250
                  visual perception (breadth/global)                                                                        positive                    0.2250
Targeting         sensorimotor performance / reduction in sensorimotor disorder measures                                    positive                    0.2250
                  visual perception (breadth/global)                                                                        positive                    0.2250
not_reported      Selective visual attention (Go/No-go task)                                                                positive                    0.2250
                  sensorimotor performance / reduction in sensorimotor disorder measures                                    positive                    0.2250
                  visual perception (breadth/global)                                                                        positive                    0.2250
Puzzle Solving    hippocampal-based memory (interpreted improvement after intervention)                                     positive                    0.1687
                  lure discrimination index (LDI) from the Mnemonic Similarity Task (hippocampal-based memory)              positive                    0.1687
Targeting         hippocampal-based memory (interpreted improvement after intervention)                                     positive                    0.1687
                  lure discrimination index (LDI) from the Mnemonic Similarity Task (hippocampal-based memory)              positive                    0.1687
not_reported      improved cognitive control (attention); persistent improvement reported by parents                        positive                    0.1687
Combat            visual crowding                                                                                           positive                    0.1575
Movement Control  visual crowding                                                                                           positive                    0.1575
Rapid Response    visual crowding                                                                                           positive                    0.1575

## 6. Query 2: Movement/Gesture Evidence for Physiological Outcomes

In [7]:
movement = supported(df)
movement = movement[
    movement["mechanic_name"].astype(str).str.contains("Movement Control|Gesture Input|Balance Training|Physical Imitation", case=False, na=False, regex=True)
    & movement["outcome_category"].astype(str).str.contains("Physiological|Anthropometric|Balance|Motor", case=False, na=False, regex=True)
]
movement = movement[[col for col in ANSWER_COLS if col in movement.columns]].sort_values("edge_weight", ascending=False)

display(summarize_counts(movement))
display(movement.head(50))

   rows  papers  games  mechanics  outcomes  positive  negative  mixed  null
0   307      13     25          4        29       111         6     18     0

,paper_id,paper_title,year,game_name,mechanic_name,population_raw,study_design,outcome_canonical,outcome_category,effect_direction,effect_size_raw,p_value,evidence_strength,edge_weight,source_quote,review_status
3998,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,X-Box 360 Kinect,Gesture Input,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,randomized_controlled_trial,Unified Balance Scale (UBS),Balance/Mobility,positive,not_reported,<0.05,randomized_controlled_trial,0.2250,"Both groups improved in CB&M scores, but only the VGT group increased on the UBS and TUG with a between-group significance (p < 0.05).",needs_review
4030,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,Kinect Sports,Movement Control,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,randomized_controlled_trial,Unified Balance Scale (UBS),Balance/Mobility,positive,not_reported,<0.05,randomized_controlled_trial,0.2250,"Both groups improved in CB&M scores, but only the VGT group increased on the UBS and TUG with a between-group significance (p < 0.05).",needs_review
4028,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,Kinect Sports,Gesture Input,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,randomized_controlled_trial,Unified Balance Scale (UBS),Balance/Mobility,positive,not_reported,<0.05,randomized_controlled_trial,0.2250,"Both groups improved in CB&M scores, but only the VGT group increased on the UBS and TUG with a between-group significance (p < 0.05).",needs_review
4027,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,Kinect Sports,Movement Control,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,randomized_controlled_trial,Community Balance and Mobility Scale (CB&M),Balance/Mobility,positive,not_reported,not_reported,randomized_controlled_trial,0.2250,"Both groups improved in CB&M scores, but only the VGT group increased on the UBS and TUG with a between-group significance (p < 0.05). Selective attention improved significantly in the VGT group (p < 0.01).",needs_review
4025,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,Kinect Sports,Gesture Input,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,randomized_controlled_trial,Community Balance and Mobility Scale (CB&M),Balance/Mobility,positive,not_reported,not_reported,randomized_controlled_trial,0.2250,"Both groups improved in CB&M scores, but only the VGT group increased on the UBS and TUG with a between-group significance (p < 0.05). Selective attention improved significantly in the VGT group (p < 0.01).",needs_review
4015,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,Kinect Adventures,Movement Control,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,randomized_controlled_trial,Unified Balance Scale (UBS),Balance/Mobility,positive,not_reported,<0.05,randomized_controlled_trial,0.2250,"Both groups improved in CB&M scores, but only the VGT group increased on the UBS and TUG with a between-group significance (p < 0.05).",needs_review
4013,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,Kinect Adventures,Gesture Input,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,randomized_controlled_trial,Unified Balance Scale (UBS),Balance/Mobility,positive,not_reported,<0.05,randomized_controlled_trial,0.2250,"Both groups improved in CB&M scores, but only the VGT group increased on the UBS and TUG with a between-group significance (p < 0.05).",needs_review
4012,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,Kinect Adventures,Movement Control,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,randomized_controlled_trial,Community Balance and Mobility Scale (CB&M),Balance/Mobility,positive,not_reported,not_reported,randomized_controlled_trial,0.2250,"Both groups improved in CB&M scores, but only the VGT group increased on the UBS and TUG with a between-group significance (p < 0.05). Selective attention improved significantly in the VGT group (p < 0.01).",needs_review
4010,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,Kinect Adventures,Gesture Input,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,randomized_controlled_trial,Community Balance and Mobility Scale (CB&M),Balance/Mobility,positive,not_reported,not_reported,randomized_controlled_trial,0.2250,"Both groups improved in CB&M scores, but only the VGT group increased on the UBS and TUG with a between-group significance (p < 0.05). Selective attention improved significantly in the VGT group (p < 0.01).",needs_review
4000,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,X-Box 360 Kinect,Movement Control,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,randomized_controlled_trial,Unified Balance Scale (UBS),Balance/Mobility,positive,not_reported,<0.05,randomized_controlled_trial,0.2250,"Both groups improved in CB&M scores, but only the VGT group increased on the UBS and TUG with a between-group significance (p < 0.05).",needs_review
3997,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,X-Box 360 Kinect,Movement Control,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,randomized_controlled_trial,Community Balance and Mobility Scale (CB&M),Balance/Mobility,positive,not_reported,not_reported,randomized_controlled_trial,0.2250,"Both groups improved in CB&M scores, but only the VGT group increased on the UBS and TUG with a between-group significance (p < 0.05). Selective attention improved significantly in the VGT group (p < 0.01).",needs_review
3995,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,X-Box 360 Kinect,Gesture Input,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,randomized_controlled_trial,Community Balance and Mobility Scale (CB&M),Balance/Mobility,positive,not_reported,not_reported,randomized_controlled_trial,0.2250,"Both groups improved in CB&M scores, but only the VGT group increased on the UBS and TUG with a between-group significance (p < 0.05). Selective attention improved significantly in the VGT group (p < 0.01).",needs_review
2911,paper_170,Active video games as an exercise tool for children with cystic ﬁbrosis,2013,Wii Fit Free Jogging,Gesture Input,"Children with cystic ﬁbrosis [n = 30, aged 12.3 (2.6) years, 17 boys, BMI 17.7 (2.8) kg/m2] were recruited from outpatient clinics in Dublin hospitals. Age and gender matched control children were recruited from loca...",quasi_experimental,energy cost (between-group comparison),Physiological,NaN,No significant difference reported,not_reported,quasi_experimental,0.1687,No signiﬁcant difference was seen between groups in the energy cost of playing active video games.,needs_review
2954,paper_170,Active video games as an exercise tool for children with cystic ﬁbrosis,2013,Wii Sports Boxing,Movement Control,"Children with cystic ﬁbrosis [n = 30, aged 12.3 (2.6) years, 17 boys, BMI 17.7 (2.8) kg/m2] were recruited from outpatient clinics in Dublin hospitals. Age and gender matched control children were recruited from loca...",quasi_experimental,energy cost (between-group comparison),Physiological,NaN,No significant difference reported,not_reported,quasi_experimental,0.1687,No signiﬁcant difference was seen between groups in the energy cost of playing active video games.,needs_review
2952,paper_170,Active video games as an exercise tool for children with cystic ﬁbrosis,2013,Wii Sports Boxing,Gesture Input,"Children with cystic ﬁbrosis [n = 30, aged 12.3 (2.6) years, 17 boys, BMI 17.7 (2.8) kg/m2] were recruited from outpatient clinics in Dublin hospitals. Age and gender matched control children were recruited from loca...",quasi_experimental,energy cost (between-group comparison),Physiological,NaN,No significant difference reported,not_reported,quasi_experimental,0.1687,No signiﬁcant difference was seen between groups in the energy cost of playing active video games.,needs_review
2912,paper_170,Active video games as an exercise tool for children with cystic ﬁbrosis,2013,Wii Fit Free Jogging,Physical Imitation,"Children with cystic ﬁbrosis [n = 30, aged 12.3 (2.6) years, 17 boys, BMI 17.7 (2.8) kg/m2] were recruited from outpatient clinics in Dublin hospitals. Age and gender matched control children were recruited from loca...",quasi_experimental,energy cost (between-group comparison),Physiological,NaN,No significant difference reported,not_reported,quasi_experimental,0.1687,No signiﬁcant difference was seen between groups in the energy cost of playing active video games.,needs_review
2882,paper_170,Active video games as an exercise tool for children with cystic ﬁbrosis,2013,Wii Sports Boxing,Movement Control,"Children with cystic ﬁbrosis [n = 30, aged 12.3 (2.6) years, 17 boys, BMI 17.7 (2.8) kg/m2] were recruited from outpatient clinics in Dublin hospitals. Age and gender matched control children were recruited from loca...",quasi_experimental,energy cost (between-group comparison),Physiological,NaN,No significant difference reported,not_reported,quasi_experimental,0.1687,No signiﬁcant difference was seen between groups in the energy cost of playing active video games.,needs_review
2910,paper_170,Active video games as an exercise tool for children with cystic ﬁbrosis,2013,Wii Fit Free Jogging,Balance Training,"Children with cystic ﬁbrosis [n = 30, aged 12.3 (2.6) years, 17 boys, BMI 17.7 (2.8) kg/m2] were recruited from outpatient clinics in Dublin hospitals. Age and gender matched control children were recruited from loca...",quasi_experimental,energy cost (between-group comparison),Physiological,NaN,No significant difference reported,not_reported,quasi_experimental,0.1687,No signiﬁcant difference was seen between groups in the energy cost of playing active video games.,needs_review
2909,paper_170,Active video games as an exercise tool for children with cystic ﬁbrosis,2013,Wii Fit Free Jogging,Movement Control,"Children with cystic ﬁbrosis [n = 30, aged 12.3 (2.6) years, 17 boys, BMI 17.7 (2.8) kg/m2] were recruited from outpatient clinics in Dublin hospitals. Age and gender matched control children were recruited from loca...",quasi_experimental,energy cost (between-group comparison),Physiological,NaN,No significant difference reported,not_reported,quasi_experimental,0.1687,No signiﬁcant difference was seen between groups in the energy cost of playing active video games.,needs_review
2880,paper_170,Active video games as an exercise tool for children with cystic ﬁbrosis,2013,Wii Sports Boxing,Gesture Input,"Children with cystic ﬁbrosis [n = 30, aged 12.3 (2.6) years, 17 boys, BMI 17.7 (2.8) kg/m2] were recruited from outpatient clinics in Dublin hospitals. Age and gender matched control children were recruited from loca...",quasi_experimental,energy cost (between-group comparison),Physiological,NaN,No significant difference reported,not_reported,quasi_experimental,0.1687,No signiﬁcant difference was seen between groups in the energy cost of playing active video games.,needs_review
2982,paper_170,Active video games as an exercise tool for children with cystic ﬁbrosis,2013,Wii Fit Free Jogging,Balance Training,"Children with cystic ﬁbrosis [n = 30, aged 12.3 (2.6) years, 17 boys, BMI 17.7 (2.8) kg/m2] were recruited from outpatient clinics in Dublin hospitals. Age and gender matched control children were recruited from loca...",quasi_experimental,energy cost (between-group comparison),Physiological,NaN,No significant difference reported,not_reported,quasi_experimental,0.1687,No signiﬁcant difference was seen between groups in the energy cost of playing active video games.,needs_review
2981,paper_170,Active video games as an exercise tool for children with cystic ﬁbrosis,2013,Wii Fit Free Jogging,Movement Control,"Children with cystic ﬁbrosis [n = 30, aged 12.3 (2.6) years, 17 boys, BMI 17.7 (2.8) kg/m2] were recruited from outpatient clinics in Dublin hospitals. Age and gender matched control children were recruited from loca...",quasi_experimental,energy cost (between-group comparison),Physiological,NaN,No significant difference reported,not_reported,quasi_experimental,0.1687,No signiﬁcant difference was seen between groups in the energy cost of playing active video games.,needs_review
2983,paper_170,Active video games as an exercise tool for children with cystic ﬁbrosis,2013,Wii Fit Free Jogging,Gesture Input,"Children with cystic ﬁbrosis [n = 30, aged 12.3 (2.6) years, 17 boys, BMI 17.7 (2.8) kg/m2] were recruited from outpatient clinics in Dublin hospitals. Age and gender matched control children were recruited from loca...",quasi_experimental,energy cost (between-group comparison),Physiological,NaN,No significant difference reported,not_reported,quasi_experimental,0.1687,No signiﬁcant difference was seen between groups in the energy cost of playing active video games.,needs_review
2984,paper_170,Active video games as an exercise tool for children with cystic ﬁbrosis,2013,Wii Fit Free Jogging,Physical Imitation,"Children with cystic ﬁbrosis [n = 30, aged 12.3 (2.6) years, 17 boys, BMI 17.7 (2.8) kg/m2] were recruited from outpatient clinics in Dublin hospitals. Age and gender matched control children were recruited from loca...",quasi_experimental,energy cost (between-group comparison),Physiological,NaN,No significant difference reported,not_reported,quasi_experimental,0.1687,No signiﬁcant difference was seen between groups in the energy cost of playing active video games.,needs_review
174,paper_001,Activity and Energy Expenditure in Older People Playing Active Video Games,2012,Your Shape Fitness Evolved (Tai Chi),Gesture Input,Community-dwelling adults (N=19) aged 70.7±6.4 years.,within_subject_experimental,activity counts (accelerometer-derived),Physiological,NaN,no significant difference reported between equivalent games played while standing and seated,not_reported (stated as no significant difference),within_subject_experimental,0.1575,"There was no signiﬁcant difference in energy expenditure, activity counts, or perceived exertion between equivalent games played while standing and seated.",needs_review
183,paper_001,Activity and Energy Expenditure in Older People Playing Active Video Games,2012,Your Shape Fitness Evolved (Tai Chi),Physical Imitation,Community-dwelling adults (N=19) aged 70.7±6.4 years.,within_subject_experimental,"correlation(energy expenditure/activity counts, balance status)",Physiological,NaN,no significant correlations reported,not_reported (stated as no significant correlations),within_subject_experimental,0.1575,No signiﬁcant correlations were observed between energy expenditure or activity counts and balance status.,needs_review
176,paper_001,Activity and Energy Expenditure in Older People Playing Active Video Games,2012,Your Shape Fitness Evolved (Tai Chi),Movement Control,Community-dwelling adults (N=19) aged 70.7±6.4 years.,within_subject_experimental,perceived exertion (RPE Borg scale),Physiological,NaN,no significant difference reported between equivalent games played while standing and seated,not_reported (stated as no significant difference),within_subject_experimental,0.1575,"There was no signiﬁcant difference in energy expenditure, activity counts, or perceived exertion between equivalent games played while standing and seated.",needs_review
177,paper_001,Activity and Energy Expenditure in Older People Playing Active Video Games,2012,Your Shape Fitness Evolved (Tai Chi),Balance Training,Community-dwelling adults (N=19) aged 70.7±6.4 years.,within_subject_experimental,perceived exertion (RPE Borg scale),Physiological,NaN,no significant difference reported between equivalent games played while standing and seated,not_reported (stated as no significant difference),within_subject_experimental,0.1575,"There was no signiﬁcant difference in energy expenditure, activity counts, or perceived exertion between equivalent games played while standing and seated.",needs_review
178,paper_001,Activity and Energy Expenditure in Older People Playing Active Video Games,2012,Your Shape Fitness Evolved (Tai Chi),Gesture Input,Community-dwelling adults (N=19) aged 70.7±6.4 years.,within_subject_experimental,perceived exertion (RPE Borg scale),Physiological,NaN,no significant difference reported between equivalent games played while standing and seated,not_reported (stated as no significant difference),within_subject_experimental,0.1575,"There was no signiﬁcant difference in energy expenditure, activity counts, or perceived exertion between equivalent games played while standing and seated.",needs_review
179,paper_001,Activity and Energy Expenditure in Older People Playing Active Video Games,2012,Your Shape Fitness Evolved (Tai Chi),Physical Imitation,Community-dwelling adults (N=19) aged 70.7±6.4 years.,within_subject_experimental,perceived exertion (RPE Borg scale),Physiological,NaN,no significant difference reported between equivalent games played while standing and seated,not_reported (stated as no significant difference),within_subject_experimental,0.1575,"There was no signiﬁcant difference in energy expenditure, activity counts, or perceived exertion between equivalent games played while standing and seated.",needs_review
180,paper_001,Activity and Energy Expenditure in Older People Playing Active Video Games,2012,Your Shape Fitness Evolved (Tai Chi),Movement Control,Community-dwelling adults (N=19) aged 70.7±6.4 years.,within_subject_experimental,"correlation(energy expenditure/activity counts, balance status)",Physiological,NaN,no significant correlations reported,not_reported (stated as no significant correlations),within_subject_experimental,0.1575,No signiﬁcant correlations were observed between energy expenditure or activity counts and balance status.,needs_review

## 7. Query 3: Minecraft / Cooperative Play / Social Outcomes

In [8]:
social = supported(df)
social = social[
    (
        social["game_name"].astype(str).str.contains("Minecraft", case=False, na=False)
        | social["mechanic_name"].astype(str).str.contains("Cooperative|Cooperation|Perspective", case=False, na=False, regex=True)
    )
    & social[["outcome_category", "outcome_canonical", "outcome_raw"]]
    .astype(str)
    .agg(" ".join, axis=1)
    .str.contains("Social|intergroup|tolerance|prosocial|empathy|cooperation", case=False, na=False, regex=True)
]
social = social[[col for col in ANSWER_COLS if col in social.columns]].sort_values("edge_weight", ascending=False)

display(summarize_counts(social))
display(social.head(50))

   rows  papers  games  mechanics  outcomes  positive  negative  mixed  null
0    10       2      2          5         3        10         0      0     0

,paper_id,paper_title,year,game_name,mechanic_name,population_raw,study_design,outcome_canonical,outcome_category,effect_direction,effect_size_raw,p_value,evidence_strength,edge_weight,source_quote,review_status
1945,paper_096,Underlying factors of social capital acquisition in the context of online-gaming: Comparing World of Warcraft and Counter-Strike,2014,Counter-Strike,Cooperation,A sample of 682 clan/guild players of the games Counter-Strike and World of Warcraft was recruited via Internet and was asked to fill out a questionnaire.,correlational,bridging social capital,social_capital,positive,NaN,NaN,correlational,0.0473,"Results of a path analysis support our assumptions and enhance previous ﬁndings that players of online-games especially gain positive social outcomes, when they go beyond the game and join game-related groups, engage...",needs_review
1956,paper_096,Underlying factors of social capital acquisition in the context of online-gaming: Comparing World of Warcraft and Counter-Strike,2014,Counter-Strike,Cooperation,A sample of 682 clan/guild players of the games Counter-Strike and World of Warcraft was recruited via Internet and was asked to fill out a questionnaire.,correlational,bonding social capital,social_capital,positive,NaN,NaN,correlational,0.0473,"we hypothesize that ... foster self-disclosure towards fellow players, which together facilitates the formation of bridging and bonding social capital.",needs_review
488,paper_011,Gaming for peace: Virtual contact through cooperative video gaming increases children's intergroup tolerance in the context of the Israeli–Palestinian conflict,2018,Minecraft,Cooperative Play,mixed virtual teams of Jewish-Israeli and Palestinian-Israeli children,not_reported,willingness to engage in social contact (behavioral_intent),behavioral_intent,positive,NaN,NaN,not_reported,0.0135,"children who participated in the intergroup program showed reduced intergroup bias on both cognitive and emotional indicators, including reduced stereotypical views, negative emotions and discriminatory tendencies to...",needs_review
489,paper_011,Gaming for peace: Virtual contact through cooperative video gaming increases children's intergroup tolerance in the context of the Israeli–Palestinian conflict,2018,Minecraft,Building,mixed virtual teams of Jewish-Israeli and Palestinian-Israeli children,not_reported,willingness to engage in social contact (behavioral_intent),behavioral_intent,positive,NaN,NaN,not_reported,0.0135,"children who participated in the intergroup program showed reduced intergroup bias on both cognitive and emotional indicators, including reduced stereotypical views, negative emotions and discriminatory tendencies to...",needs_review
490,paper_011,Gaming for peace: Virtual contact through cooperative video gaming increases children's intergroup tolerance in the context of the Israeli–Palestinian conflict,2018,Minecraft,Exploration,mixed virtual teams of Jewish-Israeli and Palestinian-Israeli children,not_reported,willingness to engage in social contact (behavioral_intent),behavioral_intent,positive,NaN,NaN,not_reported,0.0135,"children who participated in the intergroup program showed reduced intergroup bias on both cognitive and emotional indicators, including reduced stereotypical views, negative emotions and discriminatory tendencies to...",needs_review
491,paper_011,Gaming for peace: Virtual contact through cooperative video gaming increases children's intergroup tolerance in the context of the Israeli–Palestinian conflict,2018,Minecraft,Perspective Taking,mixed virtual teams of Jewish-Israeli and Palestinian-Israeli children,not_reported,willingness to engage in social contact (behavioral_intent),behavioral_intent,positive,NaN,NaN,not_reported,0.0135,"children who participated in the intergroup program showed reduced intergroup bias on both cognitive and emotional indicators, including reduced stereotypical views, negative emotions and discriminatory tendencies to...",needs_review
508,paper_011,Gaming for peace: Virtual contact through cooperative video gaming increases children's intergroup tolerance in the context of the Israeli–Palestinian conflict,2018,Minecraft,Cooperative Play,mixed virtual teams of Jewish-Israeli and Palestinian-Israeli children,not_reported,willingness to engage in social contact (behavioral_intent),behavioral_intent,positive,NaN,NaN,not_reported,0.0135,"children who participated in the intergroup program showed reduced intergroup bias on both cognitive and emotional indicators, including reduced stereotypical views, negative emotions and discriminatory tendencies to...",needs_review
509,paper_011,Gaming for peace: Virtual contact through cooperative video gaming increases children's intergroup tolerance in the context of the Israeli–Palestinian conflict,2018,Minecraft,Building,mixed virtual teams of Jewish-Israeli and Palestinian-Israeli children,not_reported,willingness to engage in social contact (behavioral_intent),behavioral_intent,positive,NaN,NaN,not_reported,0.0135,"children who participated in the intergroup program showed reduced intergroup bias on both cognitive and emotional indicators, including reduced stereotypical views, negative emotions and discriminatory tendencies to...",needs_review
510,paper_011,Gaming for peace: Virtual contact through cooperative video gaming increases children's intergroup tolerance in the context of the Israeli–Palestinian conflict,2018,Minecraft,Exploration,mixed virtual teams of Jewish-Israeli and Palestinian-Israeli children,not_reported,willingness to engage in social contact (behavioral_intent),behavioral_intent,positive,NaN,NaN,not_reported,0.0135,"children who participated in the intergroup program showed reduced intergroup bias on both cognitive and emotional indicators, including reduced stereotypical views, negative emotions and discriminatory tendencies to...",needs_review
511,paper_011,Gaming for peace: Virtual contact through cooperative video gaming increases children's intergroup tolerance in the context of the Israeli–Palestinian conflict,2018,Minecraft,Perspective Taking,mixed virtual teams of Jewish-Israeli and Palestinian-Israeli children,not_reported,willingness to engage in social contact (behavioral_intent),behavioral_intent,positive,NaN,NaN,not_reported,0.0135,"children who participated in the intergroup program showed reduced intergroup bias on both cognitive and emotional indicators, including reduced stereotypical views, negative emotions and discriminatory tendencies to...",needs_review

## 8. Query 4: FPS / Action Games and Aggression or Affective Outcomes

In [9]:
fps = supported(df)
fps = fps[
    fps[["game_name", "paper_title", "mechanic_name"]]
    .astype(str)
    .agg(" ".join, axis=1)
    .str.contains("first-person|shooter|FPS|action video|Counter-Strike|violent", case=False, na=False, regex=True)
    & fps[["outcome_category", "outcome_canonical", "outcome_raw"]]
    .astype(str)
    .agg(" ".join, axis=1)
    .str.contains("aggression|aggressive|affect|emotion|cortisol|arousal|attention|cognitive", case=False, na=False, regex=True)
]
fps = fps[[col for col in ANSWER_COLS if col in fps.columns]].sort_values("edge_weight", ascending=False)

display(summarize_counts(fps))
display(fps.head(50))

   rows  papers  games  mechanics  outcomes  positive  negative  mixed  null
0   402      27     36         25        66       312        40     21     0

,paper_id,paper_title,year,game_name,mechanic_name,population_raw,study_design,outcome_canonical,outcome_category,effect_direction,effect_size_raw,p_value,evidence_strength,edge_weight,source_quote,review_status
452,paper_009,Intense acts of violence during video game play make daily life aggression appear innocuous: A new mechanism why violent video games increase aggression,2012,Counterstrike,not_reported,"Participants were 82 adults (61 women, 21 men, mean age: 21.9 years).",randomized_controlled_trial,perceived aggressiveness,Psychological,negative,d = 0.84,< .001,randomized_controlled_trial,0.2250,"participants who played the violent video game perceived their daily life aggressive behavior as being less aggressive (M = 4.23, SD = 2.40; contrast weight: 3) compared to participants who played the violent video g...",needs_review
455,paper_009,Intense acts of violence during video game play make daily life aggression appear innocuous: A new mechanism why violent video games increase aggression,2012,Trooper Assassin,not_reported,"Participants were 82 adults (61 women, 21 men, mean age: 21.9 years).",randomized_controlled_trial,perceived aggressiveness,Psychological,negative,d = 0.84,< .001,randomized_controlled_trial,0.2250,"participants who played the violent video game perceived their daily life aggressive behavior as being less aggressive (M = 4.23, SD = 2.40; contrast weight: 3) compared to participants who played the violent video g...",needs_review
458,paper_009,Intense acts of violence during video game play make daily life aggression appear innocuous: A new mechanism why violent video games increase aggression,2012,Super Bubbles,not_reported,"Participants were 82 adults (61 women, 21 men, mean age: 21.9 years).",randomized_controlled_trial,perceived aggressiveness,Psychological,negative,d = 0.84,< .001,randomized_controlled_trial,0.2250,"participants who played the violent video game perceived their daily life aggressive behavior as being less aggressive (M = 4.23, SD = 2.40; contrast weight: 3) compared to participants who played the violent video g...",needs_review
461,paper_009,Intense acts of violence during video game play make daily life aggression appear innocuous: A new mechanism why violent video games increase aggression,2012,Penguin,not_reported,"Participants were 82 adults (61 women, 21 men, mean age: 21.9 years).",randomized_controlled_trial,perceived aggressiveness,Psychological,negative,d = 0.84,< .001,randomized_controlled_trial,0.2250,"participants who played the violent video game perceived their daily life aggressive behavior as being less aggressive (M = 4.23, SD = 2.40; contrast weight: 3) compared to participants who played the violent video g...",needs_review
4902,paper_292,"Developmental Dyslexia (Tn Wydell, Section Editor)",2015,action video game,Movement Control,children with DD,quasi_experimental,visual attention / visual attention span,Neuro/Cognitive,positive,not_reported,not_reported,quasi_experimental,0.1687,Franceschini et al. [100•] showed a direct effect of the AVG training on the spotlight of attention in children with DD. An improvement in the distribution and allocation of visuo-spatial attention was obtained in th...,needs_review
4904,paper_292,"Developmental Dyslexia (Tn Wydell, Section Editor)",2015,non-action video game,Rapid Response,children with DD,quasi_experimental,visual attention / visual attention span,Neuro/Cognitive,positive,not_reported,not_reported,quasi_experimental,0.1687,Franceschini et al. [100•] showed a direct effect of the AVG training on the spotlight of attention in children with DD. An improvement in the distribution and allocation of visuo-spatial attention was obtained in th...,needs_review
2614,paper_154,Enhancing Attentional Control: Lessons from Action Video Games,2019,NaN,not_reported,"players of a lab-designed video game that contained rewards outperformed individuals playing the same game without rewards on a declarative memory task (Prena et al., 2018).",quasi_experimental,declarative memory performance,Neuro/Cognitive,positive,not_reported,not_reported,quasi_experimental,0.1687,"players of a lab-designed video game that contained rewards outperformed individuals playing the same game without rewards on a declarative memory task (Prena et al., 2018).",needs_review
2613,paper_154,Enhancing Attentional Control: Lessons from Action Video Games,2019,NaN,not_reported,"players of a lab-designed video game that contained rewards outperformed individuals playing the same game without rewards on a declarative memory task (Prena et al., 2018).",quasi_experimental,declarative memory performance,Neuro/Cognitive,positive,not_reported,not_reported,quasi_experimental,0.1687,"players of a lab-designed video game that contained rewards outperformed individuals playing the same game without rewards on a declarative memory task (Prena et al., 2018).",needs_review
4899,paper_292,"Developmental Dyslexia (Tn Wydell, Section Editor)",2015,action video game,Combat,children with DD,quasi_experimental,visual attention / visual attention span,Neuro/Cognitive,positive,not_reported,not_reported,quasi_experimental,0.1687,Franceschini et al. [100•] showed a direct effect of the AVG training on the spotlight of attention in children with DD. An improvement in the distribution and allocation of visuo-spatial attention was obtained in th...,needs_review
4900,paper_292,"Developmental Dyslexia (Tn Wydell, Section Editor)",2015,action video game,Rapid Response,children with DD,quasi_experimental,visual attention / visual attention span,Neuro/Cognitive,positive,not_reported,not_reported,quasi_experimental,0.1687,Franceschini et al. [100•] showed a direct effect of the AVG training on the spotlight of attention in children with DD. An improvement in the distribution and allocation of visuo-spatial attention was obtained in th...,needs_review
4901,paper_292,"Developmental Dyslexia (Tn Wydell, Section Editor)",2015,action video game,Targeting,children with DD,quasi_experimental,visual attention / visual attention span,Neuro/Cognitive,positive,not_reported,not_reported,quasi_experimental,0.1687,Franceschini et al. [100•] showed a direct effect of the AVG training on the spotlight of attention in children with DD. An improvement in the distribution and allocation of visuo-spatial attention was obtained in th...,needs_review
4903,paper_292,"Developmental Dyslexia (Tn Wydell, Section Editor)",2015,non-action video game,Combat,children with DD,quasi_experimental,visual attention / visual attention span,Neuro/Cognitive,positive,not_reported,not_reported,quasi_experimental,0.1687,Franceschini et al. [100•] showed a direct effect of the AVG training on the spotlight of attention in children with DD. An improvement in the distribution and allocation of visuo-spatial attention was obtained in th...,needs_review
4906,paper_292,"Developmental Dyslexia (Tn Wydell, Section Editor)",2015,non-action video game,Movement Control,children with DD,quasi_experimental,visual attention / visual attention span,Neuro/Cognitive,positive,not_reported,not_reported,quasi_experimental,0.1687,Franceschini et al. [100•] showed a direct effect of the AVG training on the spotlight of attention in children with DD. An improvement in the distribution and allocation of visuo-spatial attention was obtained in th...,needs_review
4905,paper_292,"Developmental Dyslexia (Tn Wydell, Section Editor)",2015,non-action video game,Targeting,children with DD,quasi_experimental,visual attention / visual attention span,Neuro/Cognitive,positive,not_reported,not_reported,quasi_experimental,0.1687,Franceschini et al. [100•] showed a direct effect of the AVG training on the spotlight of attention in children with DD. An improvement in the distribution and allocation of visuo-spatial attention was obtained in th...,needs_review
4484,paper_282,Open Access Reward system and temporal pole contributions to affective evaluation during a first person shooter video game,2011,Tactical Ops: Assault on Terror,not_reported,"Thirteen male German volunteers (age 18-26 years, mean 22.7 ± 2.0) ... right-handed subjects with at least 5 hours weekly video game experience (15.1 ± 9.0 hrs/week). We excluded individuals with contraindication aga...",within_subject_experimental,negative correlation between PANAS negative affect (post-play) and rTP BOLD response to failure,Neuro/Cognitive,negative,NaN,not_reported,within_subject_experimental,0.1575,A negative correlation between negative affect and responses to failure was evident in the right temporal pole (rTP).,needs_review
4483,paper_282,Open Access Reward system and temporal pole contributions to affective evaluation during a first person shooter video game,2011,Tactical Ops: Assault on Terror,not_reported,"Thirteen male German volunteers (age 18-26 years, mean 22.7 ± 2.0) ... right-handed subjects with at least 5 hours weekly video game experience (15.1 ± 9.0 hrs/week). We excluded individuals with contraindication aga...",within_subject_experimental,caudate nucleus BOLD response to failure events (decrease),Neuro/Cognitive,negative,NaN,not_reported,within_subject_experimental,0.1575,but only failure decreased activity in orbitofrontal cortex and caudate nucleus.,needs_review
4482,paper_282,Open Access Reward system and temporal pole contributions to affective evaluation during a first person shooter video game,2011,Tactical Ops: Assault on Terror,not_reported,"Thirteen male German volunteers (age 18-26 years, mean 22.7 ± 2.0) ... right-handed subjects with at least 5 hours weekly video game experience (15.1 ± 9.0 hrs/week). We excluded individuals with contraindication aga...",within_subject_experimental,orbitofrontal cortex BOLD response to failure events (decrease),Neuro/Cognitive,negative,NaN,not_reported,within_subject_experimental,0.1575,but only failure decreased activity in orbitofrontal cortex,needs_review
4907,paper_292,"Developmental Dyslexia (Tn Wydell, Section Editor)",2015,action video game,Combat,people without AVG experience,within_subject_experimental,visual crowding,Neuro/Cognitive,positive,not_reported,not_reported,within_subject_experimental,0.1575,"Moreover, people without AVG experience could also reduce their crowding effect with 20 h of AVG training [114].",needs_review
4908,paper_292,"Developmental Dyslexia (Tn Wydell, Section Editor)",2015,action video game,Rapid Response,people without AVG experience,within_subject_experimental,visual crowding,Neuro/Cognitive,positive,not_reported,not_reported,within_subject_experimental,0.1575,"Moreover, people without AVG experience could also reduce their crowding effect with 20 h of AVG training [114].",needs_review
4909,paper_292,"Developmental Dyslexia (Tn Wydell, Section Editor)",2015,action video game,Targeting,people without AVG experience,within_subject_experimental,visual crowding,Neuro/Cognitive,positive,not_reported,not_reported,within_subject_experimental,0.1575,"Moreover, people without AVG experience could also reduce their crowding effect with 20 h of AVG training [114].",needs_review
4481,paper_282,Open Access Reward system and temporal pole contributions to affective evaluation during a first person shooter video game,2011,Tactical Ops: Assault on Terror,not_reported,"Thirteen male German volunteers (age 18-26 years, mean 22.7 ± 2.0) ... right-handed subjects with at least 5 hours weekly video game experience (15.1 ± 9.0 hrs/week). We excluded individuals with contraindication aga...",within_subject_experimental,visual cortex BOLD response to success and failure events,Neuro/Cognitive,positive,NaN,not_reported,within_subject_experimental,0.1575,Failure and success events evoked increased activity in visual cortex,needs_review
4910,paper_292,"Developmental Dyslexia (Tn Wydell, Section Editor)",2015,action video game,Movement Control,people without AVG experience,within_subject_experimental,visual crowding,Neuro/Cognitive,positive,not_reported,not_reported,within_subject_experimental,0.1575,"Moreover, people without AVG experience could also reduce their crowding effect with 20 h of AVG training [114].",needs_review
2050,paper_112,"Violent video game effects on salivary cortisol, arousal, and aggressive thoughts in children",2016,Finding Nemo (Xbox),not_reported,"One hundred and thirty-six children (67 male, 67 female, 2 unmarked) participated in the current study. The average age of the sample was 10.1 (SD = 1.25, Range = 8 to 12) years old. The sample was recruited by flyer...",randomized_controlled_trial,salivary cortisol (indicator of stress / fight-or-flight activation),physiological,positive,NaN,NaN,randomized_controlled_trial,0.1350,Results showed that the violent video game increased cortisol ... more than did the equally exciting nonviolent game.,needs_review
366,paper_007,Effects of violent video games on players’ and observers’ aggressive cognitions and aggressive behaviors,2020,Tetris,not_reported,The sample comprised 192 12-year-old children (50% girls) attending three primary schools from Chongqing in the Southwest of China.,randomized_controlled_trial,sex (male) effect on aggression in violent play,Behavioral,positive,NaN,NaN,randomized_controlled_trial,0.1350,"""Boys displayed more aggressive cognitions and behaviors than girls, but this trend was observed only in the violent game play condition.""",needs_review
367,paper_007,Effects of violent video games on players’ and observers’ aggressive cognitions and aggressive behaviors,2020,Tetris,not_reported,The sample comprised 192 12-year-old children (50% girls) attending three primary schools from Chongqing in the Southwest of China.,randomized_controlled_trial,mediation: aggressive cognitions -> aggressive behaviors,Psychological,positive,NaN,NaN,randomized_controlled_trial,0.1350,"""Mediational analysis suggested that aggressive cognitions partially mediated the effect of violent video games on aggressive behaviors.""",needs_review
2046,paper_112,"Violent video game effects on salivary cortisol, arousal, and aggressive thoughts in children",2016,Spiderman (Xbox),not_reported,"One hundred and thirty-six children (67 male, 67 female, 2 unmarked) participated in the current study. The average age of the sample was 10.1 (SD = 1.25, Range = 8 to 12) years old. The sample was recruited by flyer...",randomized_controlled_trial,salivary cortisol (indicator of stress / fight-or-flight activation),physiological,positive,NaN,NaN,randomized_controlled_trial,0.1350,Results showed that the violent video game increased cortisol ... more than did the equally exciting nonviolent game.,needs_review
2047,paper_112,"Violent video game effects on salivary cortisol, arousal, and aggressive thoughts in children",2016,Spiderman (Xbox),not_reported,"One hundred and thirty-six children (67 male, 67 female, 2 unmarked) participated in the current study. The average age of the sample was 10.1 (SD = 1.25, Range = 8 to 12) years old. The sample was recruited by flyer...",randomized_controlled_trial,cardiovascular arousal (heart rate and mean arterial pressure),physiological,mixed,NaN,NaN,randomized_controlled_trial,0.1350,Results showed that the violent video game increased cortisol and (for boys) cardiovascular arousal (relative to baseline) more than did the equally exciting nonviolent game.,needs_review
2048,paper_112,"Violent video game effects on salivary cortisol, arousal, and aggressive thoughts in children",2016,Spiderman (Xbox),not_reported,"One hundred and thirty-six children (67 male, 67 female, 2 unmarked) participated in the current study. The average age of the sample was 10.1 (SD = 1.25, Range = 8 to 12) years old. The sample was recruited by flyer...",randomized_controlled_trial,accessibility of aggressive thoughts,cognitive,positive,NaN,NaN,randomized_controlled_trial,0.1350,The violent game also increased the accessibility of aggressive thoughts.,needs_review
2371,paper_133,The Fortnite social paradox: The effects of violent-cooperative multi-player video games on children’s basic psychological needs and prosocial behavior,2021,neutral game,not_reported,The sample was composed of 845 nine to twelve-year-olds who were randomly allocated to a 2 (game content: violent versus neutral) X 2 (game mode: single-versus co-player) between-subjects design.,randomized_controlled_trial,"satisfaction of psychological needs (competence, relatedness, positive-emotions, enjoyment) as mediator",Psychological,positive,NaN,NaN,randomized_controlled_trial,0.1350,"Satisfaction of the psychological needs of competence, relatedness, positive-emotions, and enjoyment was examined as possible mediator of the hypothesized effect of cooperative violent game on prosociality.\nIncrease...",needs_review
2051,paper_112,"Violent video game effects on salivary cortisol, arousal, and aggressive thoughts in children",2016,Finding Nemo (Xbox),not_reported,"One hundred and thirty-six children (67 male, 67 female, 2 unmarked) participated in the current study. The average age of the sample was 10.1 (SD = 1.25, Range = 8 to 12) years old. The sample was recruited by flyer...",randomized_controlled_trial,cardiovascular arousal (heart rate and mean arterial pressure),physiological,mixed,NaN,NaN,randomized_controlled_trial,0.1350,Results showed that the violent video game increased cortisol and (for boys) cardiovascular arousal (relative to baseline) more than did the equally exciting nonviolent game.,needs_review
364,paper_007,Effects of violent video games on players’ and observers’ aggressive cognitions and aggressive behaviors,2020,Tetris,not_reported,The sample comprised 192 12-year-old children (50% girls) attending three primary schools from Chongqing in the Southwest of China.,randomized_controlled_trial,aggressive behaviors,Behavioral,positive,NaN,NaN,randomized_controlled_trial,0.1350,"""each participant completed a lexical decision task and a competitive reaction time task to measure their aggressive cognitions and behaviors.""",needs_review
2365,paper_133,The Fortnite social paradox: The effects of violent-cooperative multi-player video games on children’s basic psychological needs and prosocial behavior,2021,neutral game,not_reported,The sample was composed of 845 nine to twelve-year-olds who were randomly allocated to a 2 (game content: violent versus neutral) X 2 (game mode: single-versus co-player) between-subjects design.,randomized_controlled_trial,"satisfaction of psychological needs (competence, relatedness, positive-emotions, enjoyment) as mediator",Psychological,positive,NaN,NaN,randomized_controlled_trial,0.1350,"Satisfaction of the psychological needs of competence, relatedness, positive-emotions, and enjoyment was examined as possible mediator of the hypothesized effect of cooperative violent game on prosociality.\nIncrease...",needs_review
2362,paper_133,The Fortnite social paradox: The effects of violent-cooperative multi-player video games on children’s basic psychological needs and prosocial behavior,2021,MMOG,not_reported,The sample was composed of 845 nine to twelve-year-olds who were randomly allocated to a 2 (game content: violent versus neutral) X 2 (game mode: single-versus co-player) between-subjects design.,randomized_controlled_trial,"satisfaction of psychological needs (competence, relatedness, positive-emotions, enjoyment) as mediator",Psychological,positive,NaN,NaN,randomized_controlled_trial,0.1350,"Satisfaction of the psychological needs of competence, relatedness, positive-emotions, and enjoyment was examined as possible mediator of the hypothesized effect of cooperative violent game on prosociality.\nIncrease...",needs_review

## 9. Query 5: Most Common Named Games in Supported Evidence

In [10]:
named_supported = supported(df)[supported(df)["game_id"].notna()].copy()
game_counts = (
    named_supported.groupby("game_name", dropna=False)
    .agg(rows=("paper_id", "size"), papers=("paper_id", "nunique"), outcomes=("outcome_canonical", "nunique"), mean_edge_weight=("edge_weight", "mean"))
    .sort_values(["papers", "rows"], ascending=False)
)
display(game_counts.head(50))

,rows,papers,outcomes,mean_edge_weight
game_name,,,,
not_reported,101,13,44,0.108370
World of Warcraft,42,9,31,0.077429
Nintendo Wii,40,8,23,0.134770
MMORPG,51,6,28,0.071663
video games,23,6,23,0.055191
Call of Duty,21,6,19,0.091724
action video games,280,5,17,0.093311
first-person shooter,140,5,19,0.062529
League of Legends,117,4,9,0.069767
Wii,7,4,6,0.056571
Counter-Strike,99,3,9,0.074756
Minecraft,76,3,11,0.104795
virtual reality,42,3,14,0.018000
mobile phones,16,3,16,0.027000
MMORPGs,15,3,10,0.079247
Wii Fit Plus,60,2,10,0.098700
Kinect Sports,24,2,8,0.191250
Microsoft Xbox,16,2,9,0.085825
Angry Birds,14,2,7,0.149443
Xbox,13,2,8,0.075808
Tetris,12,2,7,0.129367
StarCraft II,11,2,7,0.034364
The Sims 4,10,2,4,0.036900
tablets,10,2,10,0.066140
action games,9,2,6,0.048500
Counterstrike,7,2,7,0.138886
Xbox One,7,2,5,0.074271
MOBA,6,2,6,0.074250
Nintendo DS,6,2,4,0.123733
iPad,6,2,6,0.094483
multiplayer online battle arena (MOBA),6,2,5,0.080267
Pokémon Go,5,2,5,0.079640
DOTA 2,4,2,4,0.079325
Halo,4,2,4,0.089400
MMOG,4,2,4,0.111375
custom-made action video game,48,1,4,0.101200
online first-person shooter video game,48,1,4,0.168700
Active@Home exergame,36,1,9,0.078800
Wii boxing,36,1,4,0.157500
first-person-shooter (FPS) game,36,1,2,0.135000
video or computer games,36,1,3,0.047300
collective action games,35,1,4,0.101200
Your Shape Fitness Evolved (Tai Chi),32,1,4,0.157500
Kinect,30,1,5,0.094500
custom-built video game,28,1,7,0.168700
HMD VR,24,1,4,0.013500
Kinect Sports bowling,24,1,4,0.157500
Kinect Sports boxing,24,1,4,0.157500
Kinect Sports table tennis,24,1,4,0.157500
Wii Sport bowling,24,1,4,0.157500

## 10. Query 6: Strongest Supported Claims

In [11]:
display(supported(df)[[col for col in ANSWER_COLS if col in df.columns]].sort_values("edge_weight", ascending=False).head(50))

,paper_id,paper_title,year,game_name,mechanic_name,population_raw,study_design,outcome_canonical,outcome_category,effect_direction,effect_size_raw,p_value,evidence_strength,edge_weight,source_quote,review_status
4015,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,Kinect Adventures,Movement Control,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,randomized_controlled_trial,Unified Balance Scale (UBS),Balance/Mobility,positive,not_reported,<0.05,randomized_controlled_trial,0.225,"Both groups improved in CB&M scores, but only the VGT group increased on the UBS and TUG with a between-group significance (p < 0.05).",needs_review
3342,paper_196,Use of commercial video games to improve postural balance in patients with multiple sclerosis: A systematic review and meta-analysis of randomised controlled clinical trials,2021,NaN,not_reported,patients with multiple sclerosis (MS),randomized_controlled_trial,Berg Balance Scale (BBS),postural_balance,positive,DM: 5.30,< .001,randomized_controlled_trial,0.225,"We did observe intergroup differences in BBS scores in favour of video game therapy (DM: 5.30; 95% CI,3.39—7.21; P < .001; I2 = 0%), but these were not greater than the minimum detectable change reported in the liter...",needs_review
3340,paper_196,Use of commercial video games to improve postural balance in patients with multiple sclerosis: A systematic review and meta-analysis of randomised controlled clinical trials,2021,NaN,not_reported,patients with multiple sclerosis (MS),randomized_controlled_trial,Four Step Square Test,postural_balance,NaN,DM: −.74,.48,randomized_controlled_trial,0.225,"We found no signiﬁcant differences between the video game therapy group and the control group in Four Step Square Test (DM: −.74; 95% CI, −2.79 to 1.32; P = .48; I2 = 0%)",needs_review
3324,paper_194,"Impact of an active educational video game on children’s motivation, science knowledge, and physical activity",2014,not_reported,not_reported,"In this randomized controlled study, 53 elementary school students were assigned to an experimental condition or a comparison condition.",randomized_controlled_trial,situational interest (perceived),Psychological,positive,η2 = 0.301,p < 0.01,randomized_controlled_trial,0.225,"Students in the experimental condition perceived a higher level of situational interest than their counterparts in the comparison group (p < 0.01, and η2 = 0.301).",needs_review
3323,paper_194,"Impact of an active educational video game on children’s motivation, science knowledge, and physical activity",2014,not_reported,not_reported,"In this randomized controlled study, 53 elementary school students were assigned to an experimental condition or a comparison condition.",randomized_controlled_trial,physical activity intensity (heart rate),Physiological,positive,t = 7.212,p < 0.001,randomized_controlled_trial,0.225,"the students’ average heart rates (HRs) were in the Target-Heart-Rate-Zone (HR = 134 bpm), which was signiﬁcantly higher than the average HR (103 bpm) from the comparison condition (t = 7.212, p < 0.001).",needs_review
3322,paper_194,"Impact of an active educational video game on children’s motivation, science knowledge, and physical activity",2014,not_reported,not_reported,"In this randomized controlled study, 53 elementary school students were assigned to an experimental condition or a comparison condition.",randomized_controlled_trial,science knowledge (test performance),Learning,NaN,η2 = 0.486 (pre-post),p < 0.001 (pre-post); between-group difference not significant,randomized_controlled_trial,0.225,"students in both groups performed better on the post-test than they did on the pre-test (p < 0.001, η2 = 0.486), and their post-test scores did not differ signiﬁcantly.",needs_review
3321,paper_194,"Impact of an active educational video game on children’s motivation, science knowledge, and physical activity",2014,not_reported,not_reported,"In this randomized controlled study, 53 elementary school students were assigned to an experimental condition or a comparison condition.",randomized_controlled_trial,situational interest (perceived),Psychological,positive,η2 = 0.301,p < 0.01,randomized_controlled_trial,0.225,"Students in the experimental condition perceived a higher level of situational interest than their counterparts in the comparison group (p < 0.01, and η2 = 0.301).",needs_review
3320,paper_194,"Impact of an active educational video game on children’s motivation, science knowledge, and physical activity",2014,not_reported,not_reported,"In this randomized controlled study, 53 elementary school students were assigned to an experimental condition or a comparison condition.",randomized_controlled_trial,physical activity intensity (heart rate),Physiological,positive,t = 7.212,p < 0.001,randomized_controlled_trial,0.225,"the students’ average heart rates (HRs) were in the Target-Heart-Rate-Zone (HR = 134 bpm), which was signiﬁcantly higher than the average HR (103 bpm) from the comparison condition (t = 7.212, p < 0.001).",needs_review
3319,paper_194,"Impact of an active educational video game on children’s motivation, science knowledge, and physical activity",2014,not_reported,not_reported,"In this randomized controlled study, 53 elementary school students were assigned to an experimental condition or a comparison condition.",randomized_controlled_trial,science knowledge (test performance),Learning,NaN,η2 = 0.486 (pre-post),p < 0.001 (pre-post); between-group difference not significant,randomized_controlled_trial,0.225,"students in both groups performed better on the post-test than they did on the pre-test (p < 0.001, η2 = 0.486), and their post-test scores did not differ signiﬁcantly.",needs_review
3303,paper_191,This is an open access article under the CC BY-NC-ND license (https://creativecommons.org/licenses/by-nc-nd/4.0) Peer-review under responsibility of the scientific committee of the 5th International Conference on Com...,2021,not_reported,not_reported,"Participants were generally people who don’t play video games naturally, split into 2 random groups.",randomized_controlled_trial,improvement in target cognitive tasks,neurocognitive,positive,not_reported,not_reported,randomized_controlled_trial,0.225,"An experiment conducted with pre-testing and post-testing. Participants were generally people who don’t play video games naturally, split into 2 random groups. One group play action video game for 10 – 50 hours, with...",needs_review
3301,paper_191,This is an open access article under the CC BY-NC-ND license (https://creativecommons.org/licenses/by-nc-nd/4.0) Peer-review under responsibility of the scientific committee of the 5th International Conference on Com...,2021,not_reported,not_reported,"Participants were generally people who don’t play video games naturally, split into 2 random groups.",randomized_controlled_trial,improvement in target cognitive tasks,neurocognitive,positive,not_reported,not_reported,randomized_controlled_trial,0.225,"An experiment conducted with pre-testing and post-testing. Participants were generally people who don’t play video games naturally, split into 2 random groups. One group play action video game for 10 – 50 hours, with...",needs_review
5068,paper_302,Short‑Term Effects of Video‑Games on Cognitive Enhancement:,2021,shooting video-game,not_reported,children with developmental coordination disorder and dyslexia,randomized_controlled_trial,visual perception (breadth/global),Neuro/Cognitive,positive,not_reported,not_reported,randomized_controlled_trial,0.225,The funnier and more activating game enhanced breadth of visual perception and reduced sensorimotor and reading disorders.,needs_review
5069,paper_302,Short‑Term Effects of Video‑Games on Cognitive Enhancement:,2021,shooting video-game,not_reported,children with developmental coordination disorder and dyslexia,randomized_controlled_trial,sensorimotor performance / reduction in sensorimotor disorder measures,Neuro/Cognitive,positive,not_reported,not_reported,randomized_controlled_trial,0.225,The funnier and more activating game enhanced breadth of visual perception and reduced sensorimotor and reading disorders.,needs_review
5070,paper_302,Short‑Term Effects of Video‑Games on Cognitive Enhancement:,2021,shooting video-game,not_reported,children with developmental coordination disorder and dyslexia,randomized_controlled_trial,reading performance / reduction in reading disorder measures,Learning,positive,not_reported,not_reported,randomized_controlled_trial,0.225,The funnier and more activating game enhanced breadth of visual perception and reduced sensorimotor and reading disorders.,needs_review
5071,paper_302,Short‑Term Effects of Video‑Games on Cognitive Enhancement:,2021,shooting video-game,not_reported,children with developmental coordination disorder and dyslexia,randomized_controlled_trial,"correlation between positive emotions (fun) and improvements in visual perception, sensorimotor and reading",Psychological,positive,not_reported,not_reported,randomized_controlled_trial,0.225,"Visual perception, sensorimotor and reading improvements correlated with fun.",needs_review
5072,paper_302,Short‑Term Effects of Video‑Games on Cognitive Enhancement:,2021,puzzle video-game,Puzzle Solving,children with developmental coordination disorder and dyslexia,randomized_controlled_trial,visual perception (breadth/global),Neuro/Cognitive,positive,not_reported,not_reported,randomized_controlled_trial,0.225,The funnier and more activating game enhanced breadth of visual perception and reduced sensorimotor and reading disorders.,needs_review
5073,paper_302,Short‑Term Effects of Video‑Games on Cognitive Enhancement:,2021,puzzle video-game,Targeting,children with developmental coordination disorder and dyslexia,randomized_controlled_trial,visual perception (breadth/global),Neuro/Cognitive,positive,not_reported,not_reported,randomized_controlled_trial,0.225,The funnier and more activating game enhanced breadth of visual perception and reduced sensorimotor and reading disorders.,needs_review
5074,paper_302,Short‑Term Effects of Video‑Games on Cognitive Enhancement:,2021,puzzle video-game,Puzzle Solving,children with developmental coordination disorder and dyslexia,randomized_controlled_trial,sensorimotor performance / reduction in sensorimotor disorder measures,Neuro/Cognitive,positive,not_reported,not_reported,randomized_controlled_trial,0.225,The funnier and more activating game enhanced breadth of visual perception and reduced sensorimotor and reading disorders.,needs_review
5075,paper_302,Short‑Term Effects of Video‑Games on Cognitive Enhancement:,2021,puzzle video-game,Targeting,children with developmental coordination disorder and dyslexia,randomized_controlled_trial,sensorimotor performance / reduction in sensorimotor disorder measures,Neuro/Cognitive,positive,not_reported,not_reported,randomized_controlled_trial,0.225,The funnier and more activating game enhanced breadth of visual perception and reduced sensorimotor and reading disorders.,needs_review
5076,paper_302,Short‑Term Effects of Video‑Games on Cognitive Enhancement:,2021,puzzle video-game,Puzzle Solving,children with developmental coordination disorder and dyslexia,randomized_controlled_trial,reading performance / reduction in reading disorder measures,Learning,positive,not_reported,not_reported,randomized_controlled_trial,0.225,The funnier and more activating game enhanced breadth of visual perception and reduced sensorimotor and reading disorders.,needs_review
5077,paper_302,Short‑Term Effects of Video‑Games on Cognitive Enhancement:,2021,puzzle video-game,Targeting,children with developmental coordination disorder and dyslexia,randomized_controlled_trial,reading performance / reduction in reading disorder measures,Learning,positive,not_reported,not_reported,randomized_controlled_trial,0.225,The funnier and more activating game enhanced breadth of visual perception and reduced sensorimotor and reading disorders.,needs_review
3341,paper_196,Use of commercial video games to improve postural balance in patients with multiple sclerosis: A systematic review and meta-analysis of randomised controlled clinical trials,2021,NaN,not_reported,patients with multiple sclerosis (MS),randomized_controlled_trial,Timed 25-Foot Walk,postural_balance,NaN,DM: .15,.75,randomized_controlled_trial,0.225,"We found no signiﬁcant differences between the video game therapy group and the control group in ... Timed 25-Foot Walk scores (DM: .15; 95% CI, −1.06 to .76; P = .75; I2 = 0%)",needs_review
3343,paper_196,Use of commercial video games to improve postural balance in patients with multiple sclerosis: A systematic review and meta-analysis of randomised controlled clinical trials,2021,NaN,not_reported,patients with multiple sclerosis (MS),randomized_controlled_trial,clinical_significance_relative_to_minimum_detectable_change,postural_balance_interpretation,NaN,not greater than the minimum detectable change reported in the literature,not_reported,randomized_controlled_trial,0.225,but these were not greater than the minimum detectable change reported in the literature.,needs_review
5079,paper_302,Short‑Term Effects of Video‑Games on Cognitive Enhancement:,2021,puzzle video-game,Targeting,children with developmental coordination disorder and dyslexia,randomized_controlled_trial,"correlation between positive emotions (fun) and improvements in visual perception, sensorimotor and reading",Psychological,positive,not_reported,not_reported,randomized_controlled_trial,0.225,"Visual perception, sensorimotor and reading improvements correlated with fun.",needs_review
3344,paper_196,Use of commercial video games to improve postural balance in patients with multiple sclerosis: A systematic review and meta-analysis of randomised controlled clinical trials,2021,NaN,not_reported,patients with multiple sclerosis (MS),randomized_controlled_trial,Four Step Square Test,postural_balance,NaN,DM: −.74,.48,randomized_controlled_trial,0.225,"We found no signiﬁcant differences between the video game therapy group and the control group in Four Step Square Test (DM: −.74; 95% CI, −2.79 to 1.32; P = .48; I2 = 0%)",needs_review
4768,paper_288,Active video games: the mediating effect of aerobic fitness on body composition,2008,Sport,not_reported,"322 overweight and obese children aged 10–14 years, who were current users of sedentary video games",randomized_controlled_trial,Body mass index (BMI) change from baseline at 24 weeks,physiological,positive,Observed difference between groups reduced from -0.3265 (p = 0.01) to -0.2992 (p = 0.02) when aerobic fitness was included (approximately 8% reduction in treatment effect). Table shows difference in means -0.33 (SE 0...,p = 0.01 (before mediation); p = 0.02 (after mediation),randomized_controlled_trial,0.225,"For change in BMI, the observed difference between the two treatment groups reduced from −0.3265 (p = 0.01) to −0.2992 (p = 0.02), or approximately 8% when aerobic fitness was included.",needs_review
4769,paper_288,Active video games: the mediating effect of aerobic fitness on body composition,2008,Sport,not_reported,"322 overweight and obese children aged 10–14 years, who were current users of sedentary video games",randomized_controlled_trial,Percentage body fat change from baseline at 24 weeks,physiological,positive,"Observed group difference shifted from -0.291 (p = 0.02) to -0.4136 (p = 0.03) when aerobic fitness was included (approximately 50% change in treatment effect). Table shows difference in means -0.83 (SE 0.36), 95% CI...",p = 0.02 (before mediation); p = 0.03 (after mediation),randomized_controlled_trial,0.225,"For percentage body fat, the observed group difference shifted from −0.291 (p = 0.02) to −0.4136 (p = 0.03), or approximately 50%.",needs_review
4770,paper_288,Active video games: the mediating effect of aerobic fitness on body composition,2008,Sport,not_reported,"322 overweight and obese children aged 10–14 years, who were current users of sedentary video games",randomized_controlled_trial,aerobic fitness (VO2Max) measured at 24 weeks,physiological,positive,"Table reports change values (e.g., difference in means approx -0.30 in the VO2Max row of Table 1) and mediation analysis indicates aerobic fitness at 24 weeks met mediation criteria and was a significant mediator.",p < 0.0001 (mediator significance),randomized_controlled_trial,0.225,"Only aerobic fitness at 24 weeks met the conditions for mediation, and was a significant mediator of all treatment outcomes (p < 0.0001) evaluated in the above models.",needs_review
4001,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,X-Box 360 Kinect,Gesture Input,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,randomized_controlled_trial,Timed Up and Go (TUG),Mobility/Functional mobility,positive,not_reported,<0.05,randomized_controlled_trial,0.225,"Both groups improved in CB&M scores, but only the VGT group increased on the UBS and TUG with a between-group significance (p < 0.05).",needs_review
4773,paper_288,Active video games: the mediating effect of aerobic fitness on body composition,2008,Dance Factory,not_reported,"322 overweight and obese children aged 10–14 years, who were current users of sedentary video games",randomized_controlled_trial,Body mass index (BMI) change from baseline at 24 weeks,physiological,positive,Observed difference between groups reduced from -0.3265 (p = 0.01) to -0.2992 (p = 0.02) when aerobic fitness was included (approximately 8% reduction in treatment effect). Table shows difference in means -0.33 (SE 0...,p = 0.01 (before mediation); p = 0.02 (after mediation),randomized_controlled_trial,0.225,"For change in BMI, the observed difference between the two treatment groups reduced from −0.3265 (p = 0.01) to −0.2992 (p = 0.02), or approximately 8% when aerobic fitness was included.",needs_review
4774,paper_288,Active video games: the mediating effect of aerobic fitness on body composition,2008,Dance Factory,not_reported,"322 overweight and obese children aged 10–14 years, who were current users of sedentary video games",randomized_controlled_trial,Percentage body fat change from baseline at 24 weeks,physiological,positive,"Observed group difference shifted from -0.291 (p = 0.02) to -0.4136 (p = 0.03) when aerobic fitness was included (approximately 50% change in treatment effect). Table shows difference in means -0.83 (SE 0.36), 95% CI...",p = 0.02 (before mediation); p = 0.03 (after mediation),randomized_controlled_trial,0.225,"For percentage body fat, the observed group difference shifted from −0.291 (p = 0.02) to −0.4136 (p = 0.03), or approximately 50%.",needs_review
4775,paper_288,Active video games: the mediating effect of aerobic fitness on body composition,2008,Dance Factory,not_reported,"322 overweight and obese children aged 10–14 years, who were current users of sedentary video games",randomized_controlled_trial,aerobic fitness (VO2Max) measured at 24 weeks,physiological,positive,"Table reports change values (e.g., difference in means approx -0.30 in the VO2Max row of Table 1) and mediation analysis indicates aerobic fitness at 24 weeks met mediation criteria and was a significant mediator.",p < 0.0001 (mediator significance),randomized_controlled_trial,0.225,"Only aerobic fitness at 24 weeks met the conditions for mediation, and was a significant mediator of all treatment outcomes (p < 0.0001) evaluated in the above models.",needs_review

## 11. Query 7: Null-Game Rows Audit

In [12]:
null_game = df[df["game_id"].isna()].copy()
display(summarize_counts(null_game))
display(null_game[[col for col in ANSWER_COLS if col in null_game.columns]].head(50))

   rows  papers  games  mechanics  outcomes  positive  negative  mixed  null
0   927     154      0          1       597       464        92     28     0

,paper_id,paper_title,year,game_name,mechanic_name,population_raw,study_design,outcome_canonical,outcome_category,effect_direction,effect_size_raw,p_value,evidence_strength,edge_weight,source_quote,review_status
302,paper_003,Interactive video games to reduce paediatric procedural pain and anxiety: a systematic review and meta-analysis,2020,NaN,not_reported,children (0e18 yr) undergoing painful procedures,not_reported,procedural pain,Pain,negative,SMD = e0.43,not_reported,not_reported,0.0225,Interactive video games appear to reduce children’s procedural pain (standardised mean difference [SMD]¼e0.43; 95% conﬁdence interval [CI]: e0.67 to e0.20),needs_review
303,paper_003,Interactive video games to reduce paediatric procedural pain and anxiety: a systematic review and meta-analysis,2020,NaN,not_reported,children (0e18 yr) undergoing painful procedures,not_reported,anxiety,Psychological,negative,SMD¼0.61,not_reported,not_reported,0.0225,"Interactive video games appear to reduce children’s procedural pain (standardised mean difference [SMD]¼e0.43; 95% conﬁdence interval [CI]: e0.67 to e0.20), anxiety (SMD¼0.61; 95% CI: e0.88 to e0.34), and caregivers’...",needs_review
304,paper_003,Interactive video games to reduce paediatric procedural pain and anxiety: a systematic review and meta-analysis,2020,NaN,not_reported,children (0e18 yr) undergoing painful procedures,not_reported,caregiver anxiety,Psychological,negative,SMD¼e0.31,not_reported,not_reported,0.0225,"Interactive video games appear to reduce children’s procedural pain (standardised mean difference [SMD]¼e0.43; 95% conﬁdence interval [CI]: e0.67 to e0.20), anxiety (SMD¼0.61; 95% CI: e0.88 to e0.34), and caregivers’...",needs_review
305,paper_003,Interactive video games to reduce paediatric procedural pain and anxiety: a systematic review and meta-analysis,2020,NaN,not_reported,children (0e18 yr) undergoing painful procedures,not_reported,procedure length,Physiological/Medical,NaN,not_reported,not_reported,not_reported,0.0225,"We also observed no difference between interactive video games compared with standard care for most medical outcomes (e.g. procedure length), except a reduced need for restraint.",needs_review
306,paper_003,Interactive video games to reduce paediatric procedural pain and anxiety: a systematic review and meta-analysis,2020,NaN,not_reported,children (0e18 yr) undergoing painful procedures,not_reported,need for physical restraint during procedure,Behavioral/Medical,negative,not_reported,not_reported,not_reported,0.0225,"We also observed no difference between interactive video games compared with standard care for most medical outcomes (e.g. procedure length), except a reduced need for restraint.",needs_review
307,paper_003,Interactive video games to reduce paediatric procedural pain and anxiety: a systematic review and meta-analysis,2020,NaN,not_reported,children (0e18 yr) undergoing painful procedures,not_reported,adverse effects,Safety,negative,minimal adverse effects reported,not_reported,not_reported,0.0225,Studies reported minimal adverse effects and typically had high intervention acceptability and satisfaction.,needs_review
308,paper_003,Interactive video games to reduce paediatric procedural pain and anxiety: a systematic review and meta-analysis,2020,NaN,not_reported,children (0e18 yr) undergoing painful procedures,not_reported,acceptability/satisfaction,Implementation/Acceptability,positive,typically high intervention acceptability and satisfaction,not_reported,not_reported,0.0225,Studies reported minimal adverse effects and typically had high intervention acceptability and satisfaction.,needs_review
333,paper_004,Exposure to ﬁrst-person shooter videogames is associated with multisensory temporal precision and migraine incidence,2020,NaN,not_reported,We tested this hypothesis by comparing the temporal proﬁle of the sound-induced illusion in a group of expert ﬁrst-person shooter gamers and a non-players group.,between_subject_observational,multisensory temporal binding window (TBW) width,Neuro/Cognitive,positive,~87 ms (gamers) vs ~105 ms (non-players),NaN,between_subject_observational,0.0540,"In line with the hypotheses, gamers experience signiﬁcantly narrower windows of illusion (~87 ms) relative to non-players (~105 ms), leading to higher veridical reports in gamers (~68%) relative to non-players (~59%).",needs_review
334,paper_004,Exposure to ﬁrst-person shooter videogames is associated with multisensory temporal precision and migraine incidence,2020,NaN,not_reported,We tested this hypothesis by comparing the temporal proﬁle of the sound-induced illusion in a group of expert ﬁrst-person shooter gamers and a non-players group.,between_subject_observational,veridical perception rate (accuracy of perceiving actual single flash),Neuro/Cognitive,positive,~68% (gamers) vs ~59% (non-players),NaN,between_subject_observational,0.0540,"In line with the hypotheses, gamers experience signiﬁcantly narrower windows of illusion (~87 ms) relative to non-players (~105 ms), leading to higher veridical reports in gamers (~68%) relative to non-players (~59%).",needs_review
335,paper_004,Exposure to ﬁrst-person shooter videogames is associated with multisensory temporal precision and migraine incidence,2020,NaN,not_reported,We tested this hypothesis by comparing the temporal proﬁle of the sound-induced illusion in a group of expert ﬁrst-person shooter gamers and a non-players group.,between_subject_observational,migraine incidence/severity associated with videogame exposure,Physiological,positive,NaN,NaN,between_subject_observational,0.0540,"we tested whether audio-visual intensive training in gamers could be related to the incidence of migraine, and found that its severity may be directly proportioned to the time spent on videogames.",needs_review
336,paper_005,Techno-dependencies in video games production: A Chilean case study,2021,NaN,not_reported,Deploying semi-structured interviews with Chilean game developers and governmental agencies,qualitative,technological dependency and IP dependency (interpreted construct),interpreted_construct|game_level_claim,not_reported,NaN,NaN,qualitative,0.0000,the article evidence forms of dependency on the use of non-proprietary technological tools (game engines and software development kits – SDKs) and the protection of intellectual property (IP) in the centre (publishin...,needs_review
337,paper_005,Techno-dependencies in video games production: A Chilean case study,2021,NaN,not_reported,Deploying semi-structured interviews with Chilean game developers and governmental agencies,qualitative,use of non-proprietary tools limits creativity and dissemination (game-level claim),game_level_claim,not_reported,NaN,NaN,qualitative,0.0000,"The use of non-proprietary software has led to critiques from games scholars, specifically that the use of said tools (Game Engines and Software Development Kits for consoles) not only limits creativity (Kirkpatrick,...",needs_review
338,paper_005,Techno-dependencies in video games production: A Chilean case study,2021,NaN,not_reported,Deploying semi-structured interviews with Chilean game developers and governmental agencies,qualitative,IP appropriation/transfer to publishers; developers operating as outsourced service providers (interpreted construct),interpreted_construct|game_level_claim,not_reported,NaN,NaN,qualitative,0.0000,"the primary source of value in cognitive capitalism and global game production (IP) is eventually transferred to publishers in exchange for financial stability, or games developers are transformed into service provid...",needs_review
339,paper_005,Techno-dependencies in video games production: A Chilean case study,2021,NaN,not_reported,Deploying semi-structured interviews with Chilean game developers and governmental agencies,qualitative,sector size and annual revenue (descriptive statistic),measured_outcome,not_reported,$13 million annual revenues; ~33 companies,NaN,qualitative,0.0000,"In 2016, the Chilean video games sector comprised around 33 companies (both medium-size and small size companies) with annual revenues of $13 million (VG Chile, 2017).",needs_review
340,paper_005,Techno-dependencies in video games production: A Chilean case study,2021,NaN,not_reported,Deploying semi-structured interviews with Chilean game developers and governmental agencies,qualitative,technological dependency and IP dependency (interpreted construct),interpreted_construct|game_level_claim,not_reported,NaN,NaN,qualitative,0.0000,the article evidence forms of dependency on the use of non-proprietary technological tools (game engines and software development kits – SDKs) and the protection of intellectual property (IP) in the centre (publishin...,needs_review
341,paper_005,Techno-dependencies in video games production: A Chilean case study,2021,NaN,not_reported,Deploying semi-structured interviews with Chilean game developers and governmental agencies,qualitative,use of non-proprietary tools limits creativity and dissemination (game-level claim),game_level_claim,not_reported,NaN,NaN,qualitative,0.0000,"The use of non-proprietary software has led to critiques from games scholars, specifically that the use of said tools (Game Engines and Software Development Kits for consoles) not only limits creativity (Kirkpatrick,...",needs_review
342,paper_005,Techno-dependencies in video games production: A Chilean case study,2021,NaN,not_reported,Deploying semi-structured interviews with Chilean game developers and governmental agencies,qualitative,IP appropriation/transfer to publishers; developers operating as outsourced service providers (interpreted construct),interpreted_construct|game_level_claim,not_reported,NaN,NaN,qualitative,0.0000,"the primary source of value in cognitive capitalism and global game production (IP) is eventually transferred to publishers in exchange for financial stability, or games developers are transformed into service provid...",needs_review
343,paper_005,Techno-dependencies in video games production: A Chilean case study,2021,NaN,not_reported,Deploying semi-structured interviews with Chilean game developers and governmental agencies,qualitative,sector size and annual revenue (descriptive statistic),measured_outcome,not_reported,$13 million annual revenues; ~33 companies,NaN,qualitative,0.0000,"In 2016, the Chilean video games sector comprised around 33 companies (both medium-size and small size companies) with annual revenues of $13 million (VG Chile, 2017).",needs_review
344,paper_006,Not just playing: The politics of designing games for impact on anticipatory climate governance,2022,NaN,not_reported,"a game simulating a sustainable food policy council with food system actors in Kyoto, Japan",qualitative,unclear,unclear,not_reported,NaN,NaN,qualitative,0.0000,NaN,needs_review
345,paper_006,Not just playing: The politics of designing games for impact on anticipatory climate governance,2022,NaN,not_reported,"a game simulating a sustainable food policy council with food system actors in Kyoto, Japan",qualitative,unclear,unclear,not_reported,NaN,NaN,qualitative,0.0000,NaN,needs_review
346,paper_006,Not just playing: The politics of designing games for impact on anticipatory climate governance,2022,NaN,not_reported,participants of the global climate negotiation community,qualitative,unclear,unclear,not_reported,NaN,NaN,qualitative,0.0000,NaN,needs_review
347,paper_006,Not just playing: The politics of designing games for impact on anticipatory climate governance,2022,NaN,not_reported,participants of the global climate negotiation community,qualitative,unclear,unclear,not_reported,NaN,NaN,qualitative,0.0000,NaN,needs_review
464,paper_009,Intense acts of violence during video game play make daily life aggression appear innocuous: A new mechanism why violent video games increase aggression,2012,NaN,not_reported,not_reported,not_reported,unclear,unclear,not_reported,NaN,NaN,not_reported,0.0000,NaN,needs_review
465,paper_009,Intense acts of violence during video game play make daily life aggression appear innocuous: A new mechanism why violent video games increase aggression,2012,NaN,not_reported,not_reported,not_reported,unclear,unclear,not_reported,NaN,NaN,not_reported,0.0000,NaN,needs_review
466,paper_009,Intense acts of violence during video game play make daily life aggression appear innocuous: A new mechanism why violent video games increase aggression,2012,NaN,not_reported,not_reported,not_reported,unclear,unclear,not_reported,NaN,NaN,not_reported,0.0000,NaN,needs_review
467,paper_009,Intense acts of violence during video game play make daily life aggression appear innocuous: A new mechanism why violent video games increase aggression,2012,NaN,not_reported,not_reported,not_reported,unclear,unclear,not_reported,NaN,NaN,not_reported,0.0000,NaN,needs_review
516,paper_012,"Gaming disorder test: Assessing psychometric properties, prevalence, temporal stability, and invariance using a Czech two-time-point longitudinal sample",2024,NaN,not_reported,A large-scale sample of adult Czech gamers collected at two points within nine months was analysed – T1 N = 5356; T2 N = 6077; longitudinal sample N = 1430. The project was targeted at experienced and active gamers o...,within_subject_observational,Unidimensional factor structure of the GDT,psychometric,positive,NaN,NaN,within_subject_observational,0.0608,The study confirmed the one-factor structure of the GDT,needs_review
517,paper_012,"Gaming disorder test: Assessing psychometric properties, prevalence, temporal stability, and invariance using a Czech two-time-point longitudinal sample",2024,NaN,not_reported,A large-scale sample of adult Czech gamers collected at two points within nine months was analysed – T1 N = 5356; T2 N = 6077; longitudinal sample N = 1430. The project was targeted at experienced and active gamers o...,within_subject_observational,Measurement invariance of the GDT across preferred gaming genres and time,psychometric,positive,NaN,NaN,within_subject_observational,0.0608,The study confirmed the one-factor structure of the GDT and showed that it is invariant across preferred gaming genres and the time of data collection.,needs_review
518,paper_012,"Gaming disorder test: Assessing psychometric properties, prevalence, temporal stability, and invariance using a Czech two-time-point longitudinal sample",2024,NaN,not_reported,A large-scale sample of adult Czech gamers collected at two points within nine months was analysed – T1 N = 5356; T2 N = 6077; longitudinal sample N = 1430. The project was targeted at experienced and active gamers o...,within_subject_observational,Temporal stability (test-retest) of the GDT over two timepoints,psychometric,positive,NaN,NaN,within_subject_observational,0.0608,"The study suggests that the Czech version of the GDT has good psychometric properties, including temporal stability and invariance across gaming genres, so it is suitable for the survey type and epidemiological inves...",needs_review
519,paper_012,"Gaming disorder test: Assessing psychometric properties, prevalence, temporal stability, and invariance using a Czech two-time-point longitudinal sample",2024,NaN,not_reported,A large-scale sample of adult Czech gamers collected at two points within nine months was analysed – T1 N = 5356; T2 N = 6077; longitudinal sample N = 1430. The project was targeted at experienced and active gamers o...,within_subject_observational,Negative association between GDT scores and life satisfaction,association,negative,NaN,NaN,within_subject_observational,0.0608,"It showed a negative relationship with life satisfaction and a positive relationship with anxiety, even when controlling for their mutual relationships.",needs_review
520,paper_012,"Gaming disorder test: Assessing psychometric properties, prevalence, temporal stability, and invariance using a Czech two-time-point longitudinal sample",2024,NaN,not_reported,A large-scale sample of adult Czech gamers collected at two points within nine months was analysed – T1 N = 5356; T2 N = 6077; longitudinal sample N = 1430. The project was targeted at experienced and active gamers o...,within_subject_observational,Positive association between GDT scores and anxiety,association,positive,NaN,NaN,within_subject_observational,0.0608,"It showed a negative relationship with life satisfaction and a positive relationship with anxiety, even when controlling for their mutual relationships.",needs_review
521,paper_012,"Gaming disorder test: Assessing psychometric properties, prevalence, temporal stability, and invariance using a Czech two-time-point longitudinal sample",2024,NaN,not_reported,A large-scale sample of adult Czech gamers collected at two points within nine months was analysed – T1 N = 5356; T2 N = 6077; longitudinal sample N = 1430. The project was targeted at experienced and active gamers o...,within_subject_observational,Prevalence of Gaming Disorder (per GDT criteria) across waves,epidemiological / prevalence,not_reported,T1/T2 prevalence <= 1.9%; longitudinal prevalence 0.5% (n = 7),NaN,within_subject_observational,0.0000,"The prevalence in the longitudinal sample was equal to or below 1.9% in each wave, but only 0.5% in the longitudinal sample (hence n = 7 participants fulfilled in both waves the criteria for GD).",needs_review
522,paper_013,User Communities and Social Software in the Video Game Industry*,2011,NaN,not_reported,"From this typology, we carried out interviews in video game firms to answer this research question: Do user communities in the video game industry influence the way firms use social software to harness communities?",qualitative,unclear,unclear,not_reported,NaN,NaN,qualitative,0.0000,NaN,needs_review
523,paper_013,User Communities and Social Software in the Video Game Industry*,2011,NaN,not_reported,"From this typology, we carried out interviews in video game firms to answer this research question: Do user communities in the video game industry influence the way firms use social software to harness communities?",qualitative,unclear,unclear,not_reported,NaN,NaN,qualitative,0.0000,NaN,needs_review
526,paper_015,Can video games enhance surgical skills acquisition for medical students? A systematic review,2020,NaN,not_reported,amongst 75 medical students,between_subject_observational,time_to_completion,surgical_task_performance,positive,200 s vs 244 s,P = .003,between_subject_observational,0.0900,"Harbin et al16 demonstrated that, amongst 75 medical students, those with a history of heavy video gaming (participating in ±2>3 sessions/month as recently as 3 months) demonstrated the shortest time to completion on...",needs_review
527,paper_015,Can video games enhance surgical skills acquisition for medical students? A systematic review,2020,NaN,not_reported,amongst 75 medical students,between_subject_observational,economy_of_motion,surgical_task_performance,positive,not_reported,not_reported,between_subject_observational,0.0900,"In robotic surgery, being a gamer was associated with reduced economy-of-motion scores. Harbin et al16 observed that being a heavy gamer (participating in : ±2>3 sessions/month) in the past year was",needs_review
528,paper_015,Can video games enhance surgical skills acquisition for medical students? A systematic review,2020,NaN,not_reported,amongst 75 medical students,between_subject_observational,time_to_completion,surgical_task_performance,positive,200 s vs 244 s,P = .003,between_subject_observational,0.0900,"Harbin et al16 demonstrated that, amongst 75 medical students, those with a history of heavy video gaming (participating in ±2>3 sessions/month as recently as 3 months) demonstrated the shortest time to completion on...",needs_review

## 12. A Simple Evidence Answer Template

This is not an AI agent. It gives a compact deterministic answer skeleton from selected rows.

In [13]:
def evidence_brief(question: str, rows: pd.DataFrame, max_quotes: int = 5) -> None:
    print("QUESTION:", question)
    print()
    if rows.empty:
        print("No matching supported evidence rows found.")
        return
    print("COUNTS")
    print("- rows:", len(rows))
    print("- papers:", rows["paper_id"].nunique())
    print("- games:", rows["game_name"].nunique(dropna=True))
    print("- mechanics:", rows["mechanic_name"].nunique(dropna=True))
    print()
    print("EFFECT DIRECTIONS")
    print(rows["effect_direction"].value_counts(dropna=False).to_string())
    print()
    print("TOP MECHANICS")
    print(rows["mechanic_name"].value_counts(dropna=False).head(10).to_string())
    print()
    print("REPRESENTATIVE QUOTES")
    quotes = rows.dropna(subset=["source_quote"]).sort_values("edge_weight", ascending=False)
    for _, row in quotes.head(max_quotes).iterrows():
        print(f"- {row['paper_id']} | {row.get('game_name')} | {row.get('mechanic_name')} -> {row.get('outcome_canonical')} [{row.get('effect_direction')}]")
        print(f"  {row['source_quote']}")

evidence_brief("What evidence links movement/gesture games to physiological outcomes?", movement)

QUESTION: What evidence links movement/gesture games to physiological outcomes?

COUNTS
- rows: 307
- papers: 13
- games: 25
- mechanics: 4

EFFECT DIRECTIONS
effect_direction
NaN         172
positive    111
mixed        18
negative      6

TOP MECHANICS
mechanic_name
Movement Control      138
Gesture Input         117
Physical Imitation     26
Balance Training       26

REPRESENTATIVE QUOTES
- paper_257 | X-Box 360 Kinect | Gesture Input -> Unified Balance Scale (UBS) [positive]
  Both groups improved in CB&M scores, but only the VGT group increased on the UBS and TUG with a between-group significance (p < 0.05).
- paper_257 | Kinect Adventures | Movement Control -> Community Balance and Mobility Scale (CB&M) [positive]
  Both groups improved in CB&M scores, but only the VGT group increased on the UBS and TUG with a between-group significance (p < 0.05). Selective attention improved significantly in the VGT group (p < 0.01).
- paper_257 | Kinect Sports | Movement Control -> Unified Balance Scale (UBS) [positive]
  Both groups improved in CB&M scores, but only the VGT group increased on the UBS and TUG with a between-group significance (p < 0.05).
- paper_257 | X-Box 360 Kinect | Gesture Input -> Community Balance and Mobility Scale (CB&M) [positive]
  Both groups improved in CB&M scores, but only the VGT group increased on the UBS and TUG with a between-group significance (p < 0.05). Selective attention improved significantly in the VGT group (p < 0.01).
- paper_257 | X-Box 360 Kinect | Movement Control -> Community Balance and Mobility Scale (CB&M) [positive]
  Both groups improved in CB&M scores, but only the VGT group increased on the UBS and TUG with a between-group significance (p < 0.05). Selective attention improved significantly in the VGT group (p < 0.01).

## 13. Optional LLM Synthesis

An AI agent is useful here if you want a prose answer that weighs rows, quotes caveats, and proposes follow-up filters. Keep the dataframe query deterministic first, then pass only the selected evidence rows to an LLM. This keeps the agent grounded.

In [14]:
# Optional. Requires OPENAI_API_KEY or the same key setup you used for the pipeline.
# This cell is intentionally not run by default.

def load_project_env(env_path: Path = PROJECT_ROOT / ".env") -> None:
    """Tiny .env loader so the notebook does not require python-dotenv."""
    if not env_path.exists():
        return
    for line in env_path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        os.environ[key.strip()] = value.strip().strip("'\"")

def llm_synthesize(question: str, rows: pd.DataFrame, model: str | None = None, max_rows: int = 20) -> str:
    try:
        from openai import OpenAI
    except ModuleNotFoundError as exc:
        raise ModuleNotFoundError(
            "The notebook kernel does not have the openai package. Install it in this kernel, "
            "or switch the notebook kernel to the project .venv."
        ) from exc

    load_project_env()
    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        raise RuntimeError("OPENAI_API_KEY was not found. Check the project .env or set it in this notebook kernel.")

    model = model or os.getenv("GAME_EVIDENCE_LLM_MODEL") or "gpt-4.1-mini"
    client = OpenAI(api_key=api_key)

    evidence_rows = rows.head(max_rows)[[col for col in ANSWER_COLS if col in rows.columns]].to_dict(orient="records")
    prompt = f"""
You are analyzing a literature-derived game evidence dataset.
Answer the question using only the evidence rows provided.
Be concise. Separate supported findings from caveats. Mention paper_id values.

Question: {question}

Evidence rows JSON:
{json.dumps(evidence_rows, indent=2)}
""".strip()

    response = client.responses.create(
        model=model,
        input=prompt,
    )
    return response.output_text

# Example usage after inspecting `movement` above:
# print(llm_synthesize("What evidence links movement/gesture games to physiological outcomes?", movement))

In [15]:
# First run this query cell or rerun it here
movement = supported(df)
movement = movement[
    movement["mechanic_name"].astype(str).str.contains(
        "Movement Control|Gesture Input|Balance Training|Physical Imitation",
        case=False,
        na=False,
        regex=True,
    )
    & movement["outcome_category"].astype(str).str.contains(
        "Physiological|Anthropometric|Balance|Motor",
        case=False,
        na=False,
        regex=True,
    )
]

movement = movement.sort_values("edge_weight", ascending=False)
display(movement.head(20))

,paper_id,paper_title,year,doi,study_id,intervention_id,condition_id,condition_type,game_id,game_name,game_match_confidence,mechanic_id,mechanic_name,mechanic_match_confidence,mechanic_set_id,co_mechanics,population_id,population_raw,sample_size,age_range,country,context,duration,study_design,treatment_raw,control_raw,outcome_id,outcome_raw,outcome_canonical,outcome_category,outcome_match_confidence,measurement_id,measurement_raw,measurement_type,measurement_match_confidence,effect_direction,effect_size_raw,effect_size_numeric,effect_metric,p_value,confidence_interval,effect_target_measure,evidence_strength,attribution_level,claim_type,claim_explicitness,source_quote,source_page,page_trace_status,extraction_confidence,is_supported_evidence,edge_weight,review_status,notes
3998,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,10.1186/s12883-017-0871-9,study_1,study_1_int_01,study_1_cond_treatment,treatment,g299,X-Box 360 Kinect,needs_review,m004,Gesture Input,high,ms_27805,Gesture Input|Sports Simulation|Movement Control,pop_001,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,21.0,NaN,NaN,"ambulatory chronic traumatic brain injury patients recruited from patients discharged at home (clinic database) or those receiving multidisciplinary inpatient rehabilitation at Ferrara University Hospital (Ferrara, I...",Each patient received three 1-h sessions per week over the course of 6 weeks.,randomized_controlled_trial,"Video game therapy was delivered with a video game console (X-Box 360 Kinect, Microsoft, Inc., Redmond, WA). Pre-selected games were chosen from “Kinect Adventures” and “Kinect Sports” that encompassed a wide range o...","Balance/rebalancing, postural stability and weight-shifting exercises with and without visual feedback were administered using a balance platform (Biodex Medical Systems, Inc., Shirley, NY). Each task was trained for...",study_1_out_002,Unified Balance Scale (UBS) score,Unified Balance Scale (UBS),Balance/Mobility,high,study_1_meas_002,Unified Balance Scale (UBS),clinical scale,high,positive,not_reported,NaN,NaN,<0.05,not_reported,NaN,randomized_controlled_trial,mechanic_set_inferred,reported_intervention_effect,inferred,"Both groups improved in CB&M scores, but only the VGT group increased on the UBS and TUG with a between-group significance (p < 0.05).",1.0,found,0.5,True,0.2250,needs_review,NaN
4030,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,10.1186/s12883-017-0871-9,study_1,study_1_int_01,study_1_cond_treatment,treatment,g11,Kinect Sports,needs_review,m002,Movement Control,high,ms_00302,Gesture Input|Sports Simulation|Movement Control,pop_001,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,21.0,NaN,NaN,"ambulatory chronic traumatic brain injury patients recruited from patients discharged at home (clinic database) or those receiving multidisciplinary inpatient rehabilitation at Ferrara University Hospital (Ferrara, I...",Each patient received three 1-h sessions per week over the course of 6 weeks.,randomized_controlled_trial,"Video game therapy was delivered with a video game console (X-Box 360 Kinect, Microsoft, Inc., Redmond, WA). Pre-selected games were chosen from “Kinect Adventures” and “Kinect Sports” that encompassed a wide range o...","Balance/rebalancing, postural stability and weight-shifting exercises with and without visual feedback were administered using a balance platform (Biodex Medical Systems, Inc., Shirley, NY). Each task was trained for...",study_1_out_002,Unified Balance Scale (UBS) score,Unified Balance Scale (UBS),Balance/Mobility,high,study_1_meas_002,Unified Balance Scale (UBS),clinical scale,high,positive,not_reported,NaN,NaN,<0.05,not_reported,NaN,randomized_controlled_trial,mechanic_set_inferred,reported_intervention_effect,inferred,"Both groups improved in CB&M scores, but only the VGT group increased on the UBS and TUG with a between-group significance (p < 0.05).",1.0,found,0.5,True,0.2250,needs_review,NaN
4028,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,10.1186/s12883-017-0871-9,study_1,study_1_int_01,study_1_cond_treatment,treatment,g11,Kinect Sports,needs_review,m004,Gesture Input,high,ms_00302,Gesture Input|Sports Simulation|Movement Control,pop_001,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,21.0,NaN,NaN,"ambulatory chronic traumatic brain injury patients recruited from patients discharged at home (clinic database) or those receiving multidisciplinary inpatient rehabilitation at Ferrara University Hospital (Ferrara, I...",Each patient received three 1-h sessions per week over the course of 6 weeks.,randomized_controlled_trial,"Video game therapy was delivered with a video game console (X-Box 360 Kinect, Microsoft, Inc., Redmond, WA). Pre-selected games were chosen from “Kinect Adventures” and “Kinect Sports” that encompassed a wide range o...","Balance/rebalancing, postural stability and weight-shifting exercises with and without visual feedback were administered using a balance platform (Biodex Medical Systems, Inc., Shirley, NY). Each task was trained for...",study_1_out_002,Unified Balance Scale (UBS) score,Unified Balance Scale (UBS),Balance/Mobility,high,study_1_meas_002,Unified Balance Scale (UBS),clinical scale,high,positive,not_reported,NaN,NaN,<0.05,not_reported,NaN,randomized_controlled_trial,mechanic_set_inferred,reported_intervention_effect,inferred,"Both groups improved in CB&M scores, but only the VGT group increased on the UBS and TUG with a between-group significance (p < 0.05).",1.0,found,0.5,True,0.2250,needs_review,NaN
4027,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,10.1186/s12883-017-0871-9,study_1,study_1_int_01,study_1_cond_treatment,treatment,g11,Kinect Sports,needs_review,m002,Movement Control,high,ms_00302,Gesture Input|Sports Simulation|Movement Control,pop_001,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,21.0,NaN,NaN,"ambulatory chronic traumatic brain injury patients recruited from patients discharged at home (clinic database) or those receiving multidisciplinary inpatient rehabilitation at Ferrara University Hospital (Ferrara, I...",Each patient received three 1-h sessions per week over the course of 6 weeks.,randomized_controlled_trial,"Video game therapy was delivered with a video game console (X-Box 360 Kinect, Microsoft, Inc., Redmond, WA). Pre-selected games were chosen from “Kinect Adventures” and “Kinect Sports” that encompassed a wide range o...","Balance/rebalancing, postural stability and weight-shifting exercises with and without visual feedback were administered using a balance platform (Biodex Medical Systems, Inc., Shirley, NY). Each task was trained for...",study_1_out_001,Community Balance & Mobility Scale (CB&M) score,Community Balance and Mobility Scale (CB&M),Balance/Mobility,high,study_1_meas_001,Community Balance & Mobility Scale (CB&M),clinical scale,high,positive,not_reported,NaN,NaN,not_reported,not_reported,NaN,randomized_controlled_trial,mechanic_set_inferred,reported_intervention_effect,inferred,"Both groups improved in CB&M scores, but only the VGT group increased on the UBS and TUG with a between-group significance (p < 0.05). Selective attention improved significantly in the VGT group (p < 0.01).",1.0,found,0.5,True,0.2250,needs_review,NaN
4025,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,10.1186/s12883-017-0871-9,study_1,study_1_int_01,study_1_cond_treatment,treatment,g11,Kinect Sports,needs_review,m004,Gesture Input,high,ms_00302,Gesture Input|Sports Simulation|Movement Control,pop_001,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,21.0,NaN,NaN,"ambulatory chronic traumatic brain injury patients recruited from patients discharged at home (clinic database) or those receiving multidisciplinary inpatient rehabilitation at Ferrara University Hospital (Ferrara, I...",Each patient received three 1-h sessions per week over the course of 6 weeks.,randomized_controlled_trial,"Video game therapy was delivered with a video game console (X-Box 360 Kinect, Microsoft, Inc., Redmond, WA). Pre-selected games were chosen from “Kinect Adventures” and “Kinect Sports” that encompassed a wide range o...","Balance/rebalancing, postural stability and weight-shifting exercises with and without visual feedback were administered using a balance platform (Biodex Medical Systems, Inc., Shirley, NY). Each task was trained for...",study_1_out_001,Community Balance & Mobility Scale (CB&M) score,Community Balance and Mobility Scale (CB&M),Balance/Mobility,high,study_1_meas_001,Community Balance & Mobility Scale (CB&M),clinical scale,high,positive,not_reported,NaN,NaN,not_reported,not_reported,NaN,randomized_controlled_trial,mechanic_set_inferred,reported_intervention_effect,inferred,"Both groups improved in CB&M scores, but only the VGT group increased on the UBS and TUG with a between-group significance (p < 0.05). Selective attention improved significantly in the VGT group (p < 0.01).",1.0,found,0.5,True,0.2250,needs_review,NaN
4015,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,10.1186/s12883-017-0871-9,study_1,study_1_int_01,study_1_cond_treatment,treatment,g300,Kinect Adventures,needs_review,m002,Movement Control,high,ms_27574,Gesture Input|Sports Simulation|Movement Control,pop_001,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,21.0,NaN,NaN,"ambulatory chronic traumatic brain injury patients recruited from patients discharged at home (clinic database) or those receiving multidisciplinary inpatient rehabilitation at Ferrara University Hospital (Ferrara, I...",Each patient received three 1-h sessions per week over the course of 6 weeks.,randomized_controlled_trial,"Video game therapy was delivered with a video game console (X-Box 360 Kinect, Microsoft, Inc., Redmond, WA). Pre-selected games were chosen from “Kinect Adventures” and “Kinect Sports” that encompassed a wide range o...","Balance/rebalancing, postural stability and weight-shifting exercises with and without visual feedback were administered using a balance platform (Biodex Medical Systems, Inc., Shirley, NY). Each task was trained for...",study_1_out_002,Unified Balance Scale (UBS) score,Unified Balance Scale (UBS),Balance/Mobility,high,study_1_meas_002,Unified Balance Scale (UBS),clinical scale,high,positive,not_reported,NaN,NaN,<0.05,not_reported,NaN,randomized_controlled_trial,mechanic_set_inferred,reported_intervention_effect,inferred,"Both groups improved in CB&M scores, but only the VGT group increased on the UBS and TUG with a between-group significance (p < 0.05).",1.0,found,0.5,True,0.2250,needs_review,NaN
4013,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,10.1186/s12883-017-0871-9,study_1,study_1_int_01,study_1_cond_treatment,treatment,g300,Kinect Adventures,needs_review,m004,Gesture Input,high,ms_27574,Gesture Input|Sports Simulation|Movement Control,pop_001,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,21.0,NaN,NaN,"ambulatory chronic traumatic brain injury patients recruited from patients discharged at home (clinic database) or those receiving multidisciplinary inpatient rehabilitation at Ferrara University Hospital (Ferrara, I...",Each patient received three 1-h sessions per week over the course of 6 weeks.,randomized_controlled_trial,"Video game therapy was delivered with a video game console (X-Box 360 Kinect, Microsoft, Inc., Redmond, WA). Pre-selected games were chosen from “Kinect Adventures” and “Kinect Sports” that encompassed a wide range o...","Balance/rebalancing, postural stability and weight-shifting exercises with and without visual feedback were administered using a balance platform (Biodex Medical Systems, Inc., Shirley, NY). Each task was trained for...",study_1_out_002,Unified Balance Scale (UBS) score,Unified Balance Scale (UBS),Balance/Mobility,high,study_1_meas_002,Unified Balance Scale (UBS),clinical scale,high,positive,not_reported,NaN,NaN,<0.05,not_reported,NaN,randomized_controlled_trial,mechanic_set_inferred,reported_intervention_effect,inferred,"Both groups improved in CB&M scores, but only the VGT group increased on the UBS and TUG with a between-group significance (p < 0.05).",1.0,found,0.5,True,0.2250,needs_review,NaN
4012,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,10.1186/s12883-017-0871-9,study_1,study_1_int_01,study_1_cond_treatment,treatment,g300,Kinect Adventures,needs_review,m002,Movement Control,high,ms_27574,Gesture Input|Sports Simulation|Movement Control,pop_001,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,21.0,NaN,NaN,"ambulatory chronic traumatic brain injury patients recruited from patients discharged at home (clinic database) or those receiving multidisciplinary inpatient rehabilitation at Ferrara University Hospital (Ferrara, I...",Each patient received three 1-h sessions per week over the course of 6 weeks.,randomized_controlled_trial,"Video game therapy was delivered with a video game console (X-Box 360 Kinect, Microsoft, Inc., Redmond, WA). Pre-selected games were chosen from “Kinect Adventures” and “Kinect Sports” that encompassed a wide range o...","Balance/rebalancing, postural stability and weight-shifting exercises with and without visual feedback were administered using a balance platform (Biodex Medical Systems, Inc., Shirley, NY). Each task was trained for...",study_1_out_001,Community Balance & Mobility Scale (CB&M) score,Community Balance and Mobility Scale (CB&M),Balance/Mobility,high,study_1_meas_001,Community Balance & Mobility Scale (CB&M),clinical scale,high,positive,not_reported,NaN,NaN,not_reported,not_reported,NaN,randomized_controlled_trial,mechanic_set_inferred,reported_intervention_effect,inferred,"Both groups improved in CB&M scores, but only the VGT group increased on the UBS and TUG with a between-group significance (p < 0.05). Selective attention improved significantly in the VGT group (p < 0.01).",1.0,found,0.5,True,0.2250,needs_review,NaN
4010,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,10.1186/s12883-017-0871-9,study_1,study_1_int_01,study_1_cond_treatment,treatment,g300,Kinect Adventures,needs_review,m004,Gesture Input,high,ms_27574,Gesture Input|Sports Simulation|Movement Control,pop_001,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,21.0,NaN,NaN,"ambulatory chronic traumatic brain injury patients recruited from patients discharged at home (clinic database) or those receiving multidisciplinary inpatient rehabilitation at Ferrara University Hospital (Ferrara, I...",Each patient received three 1-h sessions per week over the course of 6 weeks.,randomized_controlled_trial,"Video game therapy was delivered with a video game console (X-Box 360 Kinect, Microsoft, Inc., Redmond, WA). Pre-selected games were chosen from “Kinect Adventures” and “Kinect Sports” that encompassed a wide range o...","Balance/rebalancing, postural stability and weight-shifting exercises with and without visual feedback were administered using a balance platform (Biodex Medical Systems, Inc., Shirley, NY). Each task was trained for...",study_1_out_001,Community Balance & Mobility Scale (CB&M) score,Community Balance and Mobility Scale (CB&M),Balance/Mobility,high,study_1_meas_001,Community Balance & Mobility Scale (CB&M),clinical scale,high,positive,not_reported,NaN,NaN,not_reported,not_reported,NaN,randomized_controlled_trial,mechanic_set_inferred,reported_intervention_effect,inferred,"Both groups improved in CB&M scores, but only the VGT group increased on the UBS and TUG with a between-group significance (p < 0.05). Selective attention improved significantly in the VGT group (p < 0.01).",1.0,found,0.5,True,0.2250,needs_review,NaN
4000,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,10.1186/s12883-017-0871-9,study_1,study_1_int_01,study_1_cond_treatment,treatment,g299,X-Box 360 Kinect,needs_review,m002,Movement Control,high,ms_27805,Gesture Input|Sports Simulation|Movement Control,pop_001,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,21.0,NaN,NaN,"ambulatory chronic traumatic brain injury patients recruited from patients discharged at home (clinic database) or those receiving multidisciplinary inpatient rehabilitation at Ferrara University Hospital (Ferrara, I...",Each patient received three 1-h sessions per week over the course of 6 weeks.,randomized_controlled_trial,"Video game therapy was delivered with a video game console (X-Box 360 Kinect, Microsoft, Inc., Redmond, WA). Pre-selected games were chosen from “Kinect Adventures” and “Kinect Sports” that encompassed a wide range o...","Balance/rebalancing, postural stability and weight-shifting exercises with and without visual feedback were administered using a balance platform (Biodex Medical Systems, Inc., Shirley, NY). Each task was trained for...",study_1_out_002,Unified Balance Scale (UBS) score,Unified Balance Scale (UBS),Balance/Mobility,high,study_1_meas_002,Unified Balance Scale (UBS),clinical scale,high,positive,not_reported,NaN,NaN,<0.05,not_reported,NaN,randomized_controlled_trial,mechanic_set_inferred,reported_intervention_effect,inferred,"Both groups improved in CB&M scores, but only the VGT group increased on the UBS and TUG with a between-group significance (p < 0.05).",1.0,found,0.5,True,0.2250,needs_review,NaN

In [16]:
answer = llm_synthesize(
    "What evidence links movement/gesture games to physiological outcomes?",
    movement,
    max_rows=20,
)

print(answer)

Supported findings
- paper_170: In a quasi‑experimental study of 30 children with cystic fibrosis (age ~12 y) vs age/gender‑matched controls, active movement/gesture games (Wii Fit Free Jogging, Wii Sports Boxing; mechanics labelled Gesture Input, Movement Control, Physical Imitation, Balance Training) showed no significant difference in energy cost between groups ("No significant difference was seen between groups in the energy cost of playing active video games."). (paper_id: paper_170)

Caveats
- Study design was quasi‑experimental and sample size was small (n=30); effect sizes and p‑values are not reported in these rows.
- The outcome assessed was energy cost only (one physiological measure) and was a between‑group comparison (CF vs controls), not necessarily a within‑subject physiological change from the games.
- Other provided studies (paper_257) report balance/mobility and attention outcomes (positive), but do not report physiological outcomes in the supplied rows. (paper_id: paper_257)

In [17]:
behavioral = supported(df)

behavioral = behavioral[
    behavioral[["outcome_category", "outcome_canonical", "outcome_raw", "paper_title"]]
    .astype(str)
    .agg(" ".join, axis=1)
    .str.contains(
        "behavior|behaviour|aggression|aggressive|prosocial|cooperation|motivation|engagement|addiction|gaming disorder|social|purchase|intention",
        case=False,
        na=False,
        regex=True,
    )
]

behavioral = behavioral[
    [col for col in ANSWER_COLS if col in behavioral.columns]
].sort_values("edge_weight", ascending=False)

display(summarize_counts(behavioral))
display(behavioral.head(50))

   rows  papers  games  mechanics  outcomes  positive  negative  mixed  null
0  1413     136    187         36       372      1003       125    108     0

,paper_id,paper_title,year,game_name,mechanic_name,population_raw,study_design,outcome_canonical,outcome_category,effect_direction,effect_size_raw,p_value,evidence_strength,edge_weight,source_quote,review_status
460,paper_009,Intense acts of violence during video game play make daily life aggression appear innocuous: A new mechanism why violent video games increase aggression,2012,Super Bubbles,not_reported,"Participants were 82 adults (61 women, 21 men, mean age: 21.9 years).",randomized_controlled_trial,game liking,Psychological,negative,d = 1.48,< .001,randomized_controlled_trial,0.2250,"Liking of the violent video game (M = 2.32, SD = 1.27) was lower than liking of the neutral video game (M = 4.40, SD = 1.53), t(80) = 6.65, p b .001, d = 1.48.",needs_review
458,paper_009,Intense acts of violence during video game play make daily life aggression appear innocuous: A new mechanism why violent video games increase aggression,2012,Super Bubbles,not_reported,"Participants were 82 adults (61 women, 21 men, mean age: 21.9 years).",randomized_controlled_trial,perceived aggressiveness,Psychological,negative,d = 0.84,< .001,randomized_controlled_trial,0.2250,"participants who played the violent video game perceived their daily life aggressive behavior as being less aggressive (M = 4.23, SD = 2.40; contrast weight: 3) compared to participants who played the violent video g...",needs_review
3320,paper_194,"Impact of an active educational video game on children’s motivation, science knowledge, and physical activity",2014,not_reported,not_reported,"In this randomized controlled study, 53 elementary school students were assigned to an experimental condition or a comparison condition.",randomized_controlled_trial,physical activity intensity (heart rate),Physiological,positive,t = 7.212,p < 0.001,randomized_controlled_trial,0.2250,"the students’ average heart rates (HRs) were in the Target-Heart-Rate-Zone (HR = 134 bpm), which was signiﬁcantly higher than the average HR (103 bpm) from the comparison condition (t = 7.212, p < 0.001).",needs_review
3319,paper_194,"Impact of an active educational video game on children’s motivation, science knowledge, and physical activity",2014,not_reported,not_reported,"In this randomized controlled study, 53 elementary school students were assigned to an experimental condition or a comparison condition.",randomized_controlled_trial,science knowledge (test performance),Learning,NaN,η2 = 0.486 (pre-post),p < 0.001 (pre-post); between-group difference not significant,randomized_controlled_trial,0.2250,"students in both groups performed better on the post-test than they did on the pre-test (p < 0.001, η2 = 0.486), and their post-test scores did not differ signiﬁcantly.",needs_review
3299,paper_191,This is an open access article under the CC BY-NC-ND license (https://creativecommons.org/licenses/by-nc-nd/4.0) Peer-review under responsibility of the scientific committee of the 5th International Conference on Com...,2021,not_reported,not_reported,"Initial study: 297 participants split into 2 groups (149 played video games, 148 used traditional educational app). Follow-up study: 122 participants split into 2 groups (64 played video games, 58 used traditional ed...",randomized_controlled_trial,behaviour change in decision-making,interpreted_construct,positive,not_reported,not_reported,randomized_controlled_trial,0.2250,"Physicians who played the video game has more significant behaviour change. Therefore, the video game has bigger impact to participants compared to traditional educational app.",needs_review
463,paper_009,Intense acts of violence during video game play make daily life aggression appear innocuous: A new mechanism why violent video games increase aggression,2012,Penguin,not_reported,"Participants were 82 adults (61 women, 21 men, mean age: 21.9 years).",randomized_controlled_trial,game liking,Psychological,negative,d = 1.48,< .001,randomized_controlled_trial,0.2250,"Liking of the violent video game (M = 2.32, SD = 1.27) was lower than liking of the neutral video game (M = 4.40, SD = 1.53), t(80) = 6.65, p b .001, d = 1.48.",needs_review
462,paper_009,Intense acts of violence during video game play make daily life aggression appear innocuous: A new mechanism why violent video games increase aggression,2012,Penguin,not_reported,"Participants were 82 adults (61 women, 21 men, mean age: 21.9 years).",randomized_controlled_trial,mood,Psychological,NaN,d = 0.39,0.081,randomized_controlled_trial,0.2250,"Playing the violent video game (M = 4.56, SD = 1.29) led to more negative mood scores than playing the neutral video game (M = 5.02, SD = 1.06), but the difference did not achieve traditional levels of statistical si...",needs_review
461,paper_009,Intense acts of violence during video game play make daily life aggression appear innocuous: A new mechanism why violent video games increase aggression,2012,Penguin,not_reported,"Participants were 82 adults (61 women, 21 men, mean age: 21.9 years).",randomized_controlled_trial,perceived aggressiveness,Psychological,negative,d = 0.84,< .001,randomized_controlled_trial,0.2250,"participants who played the violent video game perceived their daily life aggressive behavior as being less aggressive (M = 4.23, SD = 2.40; contrast weight: 3) compared to participants who played the violent video g...",needs_review
3298,paper_191,This is an open access article under the CC BY-NC-ND license (https://creativecommons.org/licenses/by-nc-nd/4.0) Peer-review under responsibility of the scientific committee of the 5th International Conference on Com...,2021,not_reported,not_reported,"Initial study: 297 participants split into 2 groups (149 played video games, 148 used traditional educational app). Follow-up study: 122 participants split into 2 groups (64 played video games, 58 used traditional ed...",randomized_controlled_trial,physician decision-making behaviour,behavioral,positive,not_reported,not_reported,randomized_controlled_trial,0.2250,Participants decisions are measured during the trial span. Their behaviour and actions on different cases were recorded and analysed. Participants were also asked to fill the questionnaire related to their experience...,needs_review
459,paper_009,Intense acts of violence during video game play make daily life aggression appear innocuous: A new mechanism why violent video games increase aggression,2012,Super Bubbles,not_reported,"Participants were 82 adults (61 women, 21 men, mean age: 21.9 years).",randomized_controlled_trial,mood,Psychological,NaN,d = 0.39,0.081,randomized_controlled_trial,0.2250,"Playing the violent video game (M = 4.56, SD = 1.29) led to more negative mood scores than playing the neutral video game (M = 5.02, SD = 1.06), but the difference did not achieve traditional levels of statistical si...",needs_review
457,paper_009,Intense acts of violence during video game play make daily life aggression appear innocuous: A new mechanism why violent video games increase aggression,2012,Trooper Assassin,not_reported,"Participants were 82 adults (61 women, 21 men, mean age: 21.9 years).",randomized_controlled_trial,game liking,Psychological,negative,d = 1.48,< .001,randomized_controlled_trial,0.2250,"Liking of the violent video game (M = 2.32, SD = 1.27) was lower than liking of the neutral video game (M = 4.40, SD = 1.53), t(80) = 6.65, p b .001, d = 1.48.",needs_review
3322,paper_194,"Impact of an active educational video game on children’s motivation, science knowledge, and physical activity",2014,not_reported,not_reported,"In this randomized controlled study, 53 elementary school students were assigned to an experimental condition or a comparison condition.",randomized_controlled_trial,science knowledge (test performance),Learning,NaN,η2 = 0.486 (pre-post),p < 0.001 (pre-post); between-group difference not significant,randomized_controlled_trial,0.2250,"students in both groups performed better on the post-test than they did on the pre-test (p < 0.001, η2 = 0.486), and their post-test scores did not differ signiﬁcantly.",needs_review
456,paper_009,Intense acts of violence during video game play make daily life aggression appear innocuous: A new mechanism why violent video games increase aggression,2012,Trooper Assassin,not_reported,"Participants were 82 adults (61 women, 21 men, mean age: 21.9 years).",randomized_controlled_trial,mood,Psychological,NaN,d = 0.39,0.081,randomized_controlled_trial,0.2250,"Playing the violent video game (M = 4.56, SD = 1.29) led to more negative mood scores than playing the neutral video game (M = 5.02, SD = 1.06), but the difference did not achieve traditional levels of statistical si...",needs_review
455,paper_009,Intense acts of violence during video game play make daily life aggression appear innocuous: A new mechanism why violent video games increase aggression,2012,Trooper Assassin,not_reported,"Participants were 82 adults (61 women, 21 men, mean age: 21.9 years).",randomized_controlled_trial,perceived aggressiveness,Psychological,negative,d = 0.84,< .001,randomized_controlled_trial,0.2250,"participants who played the violent video game perceived their daily life aggressive behavior as being less aggressive (M = 4.23, SD = 2.40; contrast weight: 3) compared to participants who played the violent video g...",needs_review
454,paper_009,Intense acts of violence during video game play make daily life aggression appear innocuous: A new mechanism why violent video games increase aggression,2012,Counterstrike,not_reported,"Participants were 82 adults (61 women, 21 men, mean age: 21.9 years).",randomized_controlled_trial,game liking,Psychological,negative,d = 1.48,< .001,randomized_controlled_trial,0.2250,"Liking of the violent video game (M = 2.32, SD = 1.27) was lower than liking of the neutral video game (M = 4.40, SD = 1.53), t(80) = 6.65, p b .001, d = 1.48.",needs_review
453,paper_009,Intense acts of violence during video game play make daily life aggression appear innocuous: A new mechanism why violent video games increase aggression,2012,Counterstrike,not_reported,"Participants were 82 adults (61 women, 21 men, mean age: 21.9 years).",randomized_controlled_trial,mood,Psychological,NaN,d = 0.39,0.081,randomized_controlled_trial,0.2250,"Playing the violent video game (M = 4.56, SD = 1.29) led to more negative mood scores than playing the neutral video game (M = 5.02, SD = 1.06), but the difference did not achieve traditional levels of statistical si...",needs_review
452,paper_009,Intense acts of violence during video game play make daily life aggression appear innocuous: A new mechanism why violent video games increase aggression,2012,Counterstrike,not_reported,"Participants were 82 adults (61 women, 21 men, mean age: 21.9 years).",randomized_controlled_trial,perceived aggressiveness,Psychological,negative,d = 0.84,< .001,randomized_controlled_trial,0.2250,"participants who played the violent video game perceived their daily life aggressive behavior as being less aggressive (M = 4.23, SD = 2.40; contrast weight: 3) compared to participants who played the violent video g...",needs_review
3297,paper_191,This is an open access article under the CC BY-NC-ND license (https://creativecommons.org/licenses/by-nc-nd/4.0) Peer-review under responsibility of the scientific committee of the 5th International Conference on Com...,2021,not_reported,not_reported,"Initial study: 297 participants split into 2 groups (149 played video games, 148 used traditional educational app). Follow-up study: 122 participants split into 2 groups (64 played video games, 58 used traditional ed...",randomized_controlled_trial,behaviour change in decision-making,interpreted_construct,positive,not_reported,not_reported,randomized_controlled_trial,0.2250,"Physicians who played the video game has more significant behaviour change. Therefore, the video game has bigger impact to participants compared to traditional educational app.",needs_review
3296,paper_191,This is an open access article under the CC BY-NC-ND license (https://creativecommons.org/licenses/by-nc-nd/4.0) Peer-review under responsibility of the scientific committee of the 5th International Conference on Com...,2021,not_reported,not_reported,"Initial study: 297 participants split into 2 groups (149 played video games, 148 used traditional educational app). Follow-up study: 122 participants split into 2 groups (64 played video games, 58 used traditional ed...",randomized_controlled_trial,physician decision-making behaviour,behavioral,positive,not_reported,not_reported,randomized_controlled_trial,0.2250,Participants decisions are measured during the trial span. Their behaviour and actions on different cases were recorded and analysed. Participants were also asked to fill the questionnaire related to their experience...,needs_review
3245,paper_182,Procedia - Social and Behavioral Sciences 98 ( 2014 ) 286 – 291,2014,NaN,not_reported,"The participants, (24) low-intermediate EFL learners... Forty five lower intermediate learners, ranging from 16-22 years old learning English as a foreign language (studying at Khorasan Language Institute in Kashmar,...",randomized_controlled_trial,English vocabulary learning (post-test score),Learning,positive,not_reported,not_reported,randomized_controlled_trial,0.2250,The findings of the analyzed data indicated that the experimental group outperformed the control group statistically significant in the post-test.,needs_review
3321,paper_194,"Impact of an active educational video game on children’s motivation, science knowledge, and physical activity",2014,not_reported,not_reported,"In this randomized controlled study, 53 elementary school students were assigned to an experimental condition or a comparison condition.",randomized_controlled_trial,situational interest (perceived),Psychological,positive,η2 = 0.301,p < 0.01,randomized_controlled_trial,0.2250,"Students in the experimental condition perceived a higher level of situational interest than their counterparts in the comparison group (p < 0.01, and η2 = 0.301).",needs_review
3323,paper_194,"Impact of an active educational video game on children’s motivation, science knowledge, and physical activity",2014,not_reported,not_reported,"In this randomized controlled study, 53 elementary school students were assigned to an experimental condition or a comparison condition.",randomized_controlled_trial,physical activity intensity (heart rate),Physiological,positive,t = 7.212,p < 0.001,randomized_controlled_trial,0.2250,"the students’ average heart rates (HRs) were in the Target-Heart-Rate-Zone (HR = 134 bpm), which was signiﬁcantly higher than the average HR (103 bpm) from the comparison condition (t = 7.212, p < 0.001).",needs_review
2156,paper_121,The impact of explicit mental health messages in video games on players’ motivation and affect,2017,not_reported,not_reported,undergraduate students (n ¼ 146) played a cooperative commercial video game in pairs following a mental health or an entertainment-focused introduction message.,randomized_controlled_trial,competence,psychological,negative,not_reported,not_reported,randomized_controlled_trial,0.2250,"Furthermore, players higher in depressive symptoms experienced more relatedness, a stronger improvement in mood but also, in the mental health condition, less competence.",needs_review
2157,paper_121,The impact of explicit mental health messages in video games on players’ motivation and affect,2017,not_reported,not_reported,undergraduate students (n ¼ 146) played a cooperative commercial video game in pairs following a mental health or an entertainment-focused introduction message.,randomized_controlled_trial,intrinsic motivation,psychological,NaN,not_reported,not_reported,randomized_controlled_trial,0.2250,"Results showed that intrinsic motivation was high and similar across conditions, but autonomy was lower in the mental health condition.",needs_review
4741,paper_287,Page 1 of 5 (page number not for citation purposes),2008,EyeToy®,not_reported,Twenty children (mean ± SD age = 12 ± 1.5 years; 40% female) were randomised to receive either an active video game upgrade package or to a control group (no intervention).,randomized_controlled_trial,video game play time (minutes/day),physical_activity_behavior,NaN,"54 versus 98 minutes/day [difference = -44 minutes/day, 95% CI [-92, 2]]",0.06,randomized_controlled_trial,0.2250,Children in the intervention group spent less mean time over the total 12-week intervention period playing all video games compared to those in the control group (54 versus 98 minutes/day [difference = -44 minutes/da...,needs_review
4744,paper_287,Page 1 of 5 (page number not for citation purposes),2008,dance mat,not_reported,Twenty children (mean ± SD age = 12 ± 1.5 years; 40% female) were randomised to receive either an active video game upgrade package or to a control group (no intervention).,randomized_controlled_trial,video game play time (minutes/day),physical_activity_behavior,NaN,"54 versus 98 minutes/day [difference = -44 minutes/day, 95% CI [-92, 2]]",0.06,randomized_controlled_trial,0.2250,Children in the intervention group spent less mean time over the total 12-week intervention period playing all video games compared to those in the control group (54 versus 98 minutes/day [difference = -44 minutes/da...,needs_review
4747,paper_287,Page 1 of 5 (page number not for citation purposes),2008,PlayStation®2,not_reported,Twenty children (mean ± SD age = 12 ± 1.5 years; 40% female) were randomised to receive either an active video game upgrade package or to a control group (no intervention).,randomized_controlled_trial,video game play time (minutes/day),physical_activity_behavior,NaN,"54 versus 98 minutes/day [difference = -44 minutes/day, 95% CI [-92, 2]]",0.06,randomized_controlled_trial,0.2250,Children in the intervention group spent less mean time over the total 12-week intervention period playing all video games compared to those in the control group (54 versus 98 minutes/day [difference = -44 minutes/da...,needs_review
4750,paper_287,Page 1 of 5 (page number not for citation purposes),2008,NaN,not_reported,Twenty children (mean ± SD age = 12 ± 1.5 years; 40% female) were randomised to receive either an active video game upgrade package or to a control group (no intervention).,randomized_controlled_trial,video game play time (minutes/day),physical_activity_behavior,NaN,"54 versus 98 minutes/day [difference = -44 minutes/day, 95% CI [-92, 2]]",0.06,randomized_controlled_trial,0.2250,Children in the intervention group spent less mean time over the total 12-week intervention period playing all video games compared to those in the control group (54 versus 98 minutes/day [difference = -44 minutes/da...,needs_review
2161,paper_121,The impact of explicit mental health messages in video games on players’ motivation and affect,2017,not_reported,not_reported,undergraduate students (n ¼ 146) played a cooperative commercial video game in pairs following a mental health or an entertainment-focused introduction message.,randomized_controlled_trial,competence,psychological,negative,not_reported,not_reported,randomized_controlled_trial,0.2250,"Furthermore, players higher in depressive symptoms experienced more relatedness, a stronger improvement in mood but also, in the mental health condition, less competence.",needs_review
2160,paper_121,The impact of explicit mental health messages in video games on players’ motivation and affect,2017,not_reported,not_reported,undergraduate students (n ¼ 146) played a cooperative commercial video game in pairs following a mental health or an entertainment-focused introduction message.,randomized_controlled_trial,mood,affective,positive,not_reported,not_reported,randomized_controlled_trial,0.2250,"Furthermore, players higher in depressive symptoms experienced more relatedness, a stronger improvement in mood but also, in the mental health condition, less competence.",needs_review

In [18]:
answer = llm_synthesize(
    "What behavioral outcomes are linked to video games or game mechanics in the evidence dataset?",
    behavioral,
    max_rows=25,
)

print(answer)

Supported findings
- Physician decision-making behaviour / behaviour change in decision-making — positive effect reported: physicians who played the video game showed greater behaviour change versus a traditional educational app (paper_191). (Effect size and p not reported; source reports measured decisions and recorded actions.)
- Physical activity intensity (heart rate) — increased during an active educational video game: experimental group HR = 134 bpm vs comparison 103 bpm, t = 7.212, p < 0.001 (paper_194).
- Video-game play time (minutes/day) — intervention (active game upgrade) group spent less time playing all video games over 12 weeks than controls: 54 vs 98 min/day (difference = −44 min/day, 95% CI [−92, 2]); p = 0.06 (trend toward decrease, paper_287).

Caveats
- The physician decision-making result (paper_191) lacks reported effect sizes, CIs, or p-values; details and robustness are unclear.
- The reduced play-time finding (paper_287) did not reach conventional significance (p = 0.06) and is based on a small sample (n = 20).
- Increased heart rate (paper_194) is a physiological indicator of greater physical activity during play; it does not directly measure longer-term behavior change outside the play session.
- Many other rows (e.g., paper_009) report psychological outcomes (perceived aggressiveness, liking, mood) rather than behavioral outcomes and are therefore not listed above.

In [19]:
aggression = search_evidence(
    term="aggression",
    require_supported=True,
    n=50,
)

display(summarize_counts(aggression))
display(aggression)

   rows  papers  games  mechanics  outcomes  positive  negative  mixed  null
0    50       8     10          1        18        22        10      2     0

,paper_id,paper_title,year,game_name,mechanic_name,population_raw,study_design,outcome_canonical,outcome_category,effect_direction,effect_size_raw,p_value,evidence_strength,edge_weight,source_quote,review_status
457,paper_009,Intense acts of violence during video game play make daily life aggression appear innocuous: A new mechanism why violent video games increase aggression,2012,Trooper Assassin,not_reported,"Participants were 82 adults (61 women, 21 men, mean age: 21.9 years).",randomized_controlled_trial,game liking,Psychological,negative,d = 1.48,< .001,randomized_controlled_trial,0.2250,"Liking of the violent video game (M = 2.32, SD = 1.27) was lower than liking of the neutral video game (M = 4.40, SD = 1.53), t(80) = 6.65, p b .001, d = 1.48.",needs_review
453,paper_009,Intense acts of violence during video game play make daily life aggression appear innocuous: A new mechanism why violent video games increase aggression,2012,Counterstrike,not_reported,"Participants were 82 adults (61 women, 21 men, mean age: 21.9 years).",randomized_controlled_trial,mood,Psychological,NaN,d = 0.39,0.081,randomized_controlled_trial,0.2250,"Playing the violent video game (M = 4.56, SD = 1.29) led to more negative mood scores than playing the neutral video game (M = 5.02, SD = 1.06), but the difference did not achieve traditional levels of statistical si...",needs_review
459,paper_009,Intense acts of violence during video game play make daily life aggression appear innocuous: A new mechanism why violent video games increase aggression,2012,Super Bubbles,not_reported,"Participants were 82 adults (61 women, 21 men, mean age: 21.9 years).",randomized_controlled_trial,mood,Psychological,NaN,d = 0.39,0.081,randomized_controlled_trial,0.2250,"Playing the violent video game (M = 4.56, SD = 1.29) led to more negative mood scores than playing the neutral video game (M = 5.02, SD = 1.06), but the difference did not achieve traditional levels of statistical si...",needs_review
458,paper_009,Intense acts of violence during video game play make daily life aggression appear innocuous: A new mechanism why violent video games increase aggression,2012,Super Bubbles,not_reported,"Participants were 82 adults (61 women, 21 men, mean age: 21.9 years).",randomized_controlled_trial,perceived aggressiveness,Psychological,negative,d = 0.84,< .001,randomized_controlled_trial,0.2250,"participants who played the violent video game perceived their daily life aggressive behavior as being less aggressive (M = 4.23, SD = 2.40; contrast weight: 3) compared to participants who played the violent video g...",needs_review
462,paper_009,Intense acts of violence during video game play make daily life aggression appear innocuous: A new mechanism why violent video games increase aggression,2012,Penguin,not_reported,"Participants were 82 adults (61 women, 21 men, mean age: 21.9 years).",randomized_controlled_trial,mood,Psychological,NaN,d = 0.39,0.081,randomized_controlled_trial,0.2250,"Playing the violent video game (M = 4.56, SD = 1.29) led to more negative mood scores than playing the neutral video game (M = 5.02, SD = 1.06), but the difference did not achieve traditional levels of statistical si...",needs_review
456,paper_009,Intense acts of violence during video game play make daily life aggression appear innocuous: A new mechanism why violent video games increase aggression,2012,Trooper Assassin,not_reported,"Participants were 82 adults (61 women, 21 men, mean age: 21.9 years).",randomized_controlled_trial,mood,Psychological,NaN,d = 0.39,0.081,randomized_controlled_trial,0.2250,"Playing the violent video game (M = 4.56, SD = 1.29) led to more negative mood scores than playing the neutral video game (M = 5.02, SD = 1.06), but the difference did not achieve traditional levels of statistical si...",needs_review
455,paper_009,Intense acts of violence during video game play make daily life aggression appear innocuous: A new mechanism why violent video games increase aggression,2012,Trooper Assassin,not_reported,"Participants were 82 adults (61 women, 21 men, mean age: 21.9 years).",randomized_controlled_trial,perceived aggressiveness,Psychological,negative,d = 0.84,< .001,randomized_controlled_trial,0.2250,"participants who played the violent video game perceived their daily life aggressive behavior as being less aggressive (M = 4.23, SD = 2.40; contrast weight: 3) compared to participants who played the violent video g...",needs_review
454,paper_009,Intense acts of violence during video game play make daily life aggression appear innocuous: A new mechanism why violent video games increase aggression,2012,Counterstrike,not_reported,"Participants were 82 adults (61 women, 21 men, mean age: 21.9 years).",randomized_controlled_trial,game liking,Psychological,negative,d = 1.48,< .001,randomized_controlled_trial,0.2250,"Liking of the violent video game (M = 2.32, SD = 1.27) was lower than liking of the neutral video game (M = 4.40, SD = 1.53), t(80) = 6.65, p b .001, d = 1.48.",needs_review
452,paper_009,Intense acts of violence during video game play make daily life aggression appear innocuous: A new mechanism why violent video games increase aggression,2012,Counterstrike,not_reported,"Participants were 82 adults (61 women, 21 men, mean age: 21.9 years).",randomized_controlled_trial,perceived aggressiveness,Psychological,negative,d = 0.84,< .001,randomized_controlled_trial,0.2250,"participants who played the violent video game perceived their daily life aggressive behavior as being less aggressive (M = 4.23, SD = 2.40; contrast weight: 3) compared to participants who played the violent video g...",needs_review
461,paper_009,Intense acts of violence during video game play make daily life aggression appear innocuous: A new mechanism why violent video games increase aggression,2012,Penguin,not_reported,"Participants were 82 adults (61 women, 21 men, mean age: 21.9 years).",randomized_controlled_trial,perceived aggressiveness,Psychological,negative,d = 0.84,< .001,randomized_controlled_trial,0.2250,"participants who played the violent video game perceived their daily life aggressive behavior as being less aggressive (M = 4.23, SD = 2.40; contrast weight: 3) compared to participants who played the violent video g...",needs_review
463,paper_009,Intense acts of violence during video game play make daily life aggression appear innocuous: A new mechanism why violent video games increase aggression,2012,Penguin,not_reported,"Participants were 82 adults (61 women, 21 men, mean age: 21.9 years).",randomized_controlled_trial,game liking,Psychological,negative,d = 1.48,< .001,randomized_controlled_trial,0.2250,"Liking of the violent video game (M = 2.32, SD = 1.27) was lower than liking of the neutral video game (M = 4.40, SD = 1.53), t(80) = 6.65, p b .001, d = 1.48.",needs_review
460,paper_009,Intense acts of violence during video game play make daily life aggression appear innocuous: A new mechanism why violent video games increase aggression,2012,Super Bubbles,not_reported,"Participants were 82 adults (61 women, 21 men, mean age: 21.9 years).",randomized_controlled_trial,game liking,Psychological,negative,d = 1.48,< .001,randomized_controlled_trial,0.2250,"Liking of the violent video game (M = 2.32, SD = 1.27) was lower than liking of the neutral video game (M = 4.40, SD = 1.53), t(80) = 6.65, p b .001, d = 1.48.",needs_review
2317,paper_129,The eﬀect of violence and competition within video games on aggression,2007,same video game across all conditions,not_reported,Sixtyfour participants played one of four versions of a video game (2 [Competitive] x 2 [Violent]),randomized_controlled_trial,aggressive behaviour,Behavioral,NaN,not_reported,not_reported,quasi_experimental,0.1687,Neither competition nor violence impacted aggressive behaviour. Possible limitations to this study included the poor validity of the Taylor Competitive Reaction Time Task (TCRTT) and the delay between participants ﬁn...,needs_review
2316,paper_129,The eﬀect of violence and competition within video games on aggression,2007,same video game across all conditions,not_reported,Sixtyfour participants played one of four versions of a video game (2 [Competitive] x 2 [Violent]),randomized_controlled_trial,aggressive affect,Psychological,positive,not_reported,not_reported,quasi_experimental,0.1687,"it was found that competition, but not violence, impacted aggressive aﬀect. In addition, participants who lost in the competitive version of the game had even higher levels of aggressive aﬀect.",needs_review
2315,paper_129,The eﬀect of violence and competition within video games on aggression,2007,same video game across all conditions,not_reported,Sixtyfour participants played one of four versions of a video game (2 [Competitive] x 2 [Violent]),randomized_controlled_trial,aggressive behaviour,Behavioral,NaN,not_reported,not_reported,quasi_experimental,0.1687,Neither competition nor violence impacted aggressive behaviour. Possible limitations to this study included the poor validity of the Taylor Competitive Reaction Time Task (TCRTT) and the delay between participants ﬁn...,needs_review
2314,paper_129,The eﬀect of violence and competition within video games on aggression,2007,same video game across all conditions,not_reported,Sixtyfour participants played one of four versions of a video game (2 [Competitive] x 2 [Violent]),randomized_controlled_trial,aggressive affect,Psychological,positive,not_reported,not_reported,quasi_experimental,0.1687,"it was found that competition, but not violence, impacted aggressive aﬀect. In addition, participants who lost in the competitive version of the game had even higher levels of aggressive aﬀect.",needs_review
2312,paper_129,The eﬀect of violence and competition within video games on aggression,2007,same video game across all conditions,not_reported,Sixtyfour participants played one of four versions of a video game (2 [Competitive] x 2 [Violent]),randomized_controlled_trial,aggressive affect,Psychological,positive,not_reported,not_reported,quasi_experimental,0.1687,"it was found that competition, but not violence, impacted aggressive aﬀect. In addition, participants who lost in the competitive version of the game had even higher levels of aggressive aﬀect.",needs_review
2313,paper_129,The eﬀect of violence and competition within video games on aggression,2007,same video game across all conditions,not_reported,Sixtyfour participants played one of four versions of a video game (2 [Competitive] x 2 [Violent]),randomized_controlled_trial,aggressive behaviour,Behavioral,NaN,not_reported,not_reported,quasi_experimental,0.1687,Neither competition nor violence impacted aggressive behaviour. Possible limitations to this study included the poor validity of the Taylor Competitive Reaction Time Task (TCRTT) and the delay between participants ﬁn...,needs_review
2310,paper_129,The eﬀect of violence and competition within video games on aggression,2007,same video game across all conditions,not_reported,Sixtyfour participants played one of four versions of a video game (2 [Competitive] x 2 [Violent]),randomized_controlled_trial,aggressive affect,Psychological,positive,not_reported,not_reported,quasi_experimental,0.1687,"it was found that competition, but not violence, impacted aggressive aﬀect. In addition, participants who lost in the competitive version of the game had even higher levels of aggressive aﬀect.",needs_review
2318,paper_129,The eﬀect of violence and competition within video games on aggression,2007,same video game across all conditions,not_reported,Sixtyfour participants played one of four versions of a video game (2 [Competitive] x 2 [Violent]),randomized_controlled_trial,aggressive affect,Psychological,positive,not_reported,not_reported,quasi_experimental,0.1687,"it was found that competition, but not violence, impacted aggressive aﬀect. In addition, participants who lost in the competitive version of the game had even higher levels of aggressive aﬀect.",needs_review
2319,paper_129,The eﬀect of violence and competition within video games on aggression,2007,same video game across all conditions,not_reported,Sixtyfour participants played one of four versions of a video game (2 [Competitive] x 2 [Violent]),randomized_controlled_trial,aggressive behaviour,Behavioral,NaN,not_reported,not_reported,quasi_experimental,0.1687,Neither competition nor violence impacted aggressive behaviour. Possible limitations to this study included the poor validity of the Taylor Competitive Reaction Time Task (TCRTT) and the delay between participants ﬁn...,needs_review
2320,paper_129,The eﬀect of violence and competition within video games on aggression,2007,same video game across all conditions,not_reported,Sixtyfour participants played one of four versions of a video game (2 [Competitive] x 2 [Violent]),randomized_controlled_trial,aggressive affect,Psychological,positive,not_reported,not_reported,quasi_experimental,0.1687,"it was found that competition, but not violence, impacted aggressive aﬀect. In addition, participants who lost in the competitive version of the game had even higher levels of aggressive aﬀect.",needs_review
2321,paper_129,The eﬀect of violence and competition within video games on aggression,2007,same video game across all conditions,not_reported,Sixtyfour participants played one of four versions of a video game (2 [Competitive] x 2 [Violent]),randomized_controlled_trial,aggressive behaviour,Behavioral,NaN,not_reported,not_reported,quasi_experimental,0.1687,Neither competition nor violence impacted aggressive behaviour. Possible limitations to this study included the poor validity of the Taylor Competitive Reaction Time Task (TCRTT) and the delay between participants ﬁn...,needs_review
2311,paper_129,The eﬀect of violence and competition within video games on aggression,2007,same video game across all conditions,not_reported,Sixtyfour participants played one of four versions of a video game (2 [Competitive] x 2 [Violent]),randomized_controlled_trial,aggressive behaviour,Behavioral,NaN,not_reported,not_reported,quasi_experimental,0.1687,Neither competition nor violence impacted aggressive behaviour. Possible limitations to this study included the poor validity of the Taylor Competitive Reaction Time Task (TCRTT) and the delay between participants ﬁn...,needs_review
3238,paper_181,Procedia - Social and Behavioral Sciences 82 ( 2013 ) 933 – 941,2013,not_reported,not_reported,"In experiment participated 24 pupils (13 girls and 11 boys) aged 12-14 years. School-gymnasium № 23, 7 form, c.Almaty.",within_subject_experimental,index_of_aggression,measured_outcome,positive,"Before game 17,3; After game 21,7",not_reported,within_subject_experimental,0.1575,"Test of Buss-Durkey ... Index of aggression ... Before game 17,3 ... After game 21,7",needs_review
3242,paper_181,Procedia - Social and Behavioral Sciences 82 ( 2013 ) 933 – 941,2013,not_reported,not_reported,"In experiment participated 24 pupils (13 girls and 11 boys) aged 12-14 years. School-gymnasium № 23, 7 form, c.Almaty.",within_subject_experimental,aggressiveness_scale,measured_outcome,positive,"Before game 7,9; After game 11,9",not_reported,within_subject_experimental,0.1575,"Test of Eysenck ... Aggressionn ... Before game 7,9 ... After game 11,9",needs_review
351,paper_007,Effects of violent video games on players’ and observers’ aggressive cognitions and aggressive behaviors,2020,Street Fighter II,not_reported,The sample comprised 192 12-year-old children (50% girls) attending three primary schools from Chongqing in the Southwest of China.,randomized_controlled_trial,sex (male) effect on aggression in violent play,Behavioral,positive,NaN,NaN,randomized_controlled_trial,0.1350,"""Boys displayed more aggressive cognitions and behaviors than girls, but this trend was observed only in the violent game play condition.""",needs_review
350,paper_007,Effects of violent video games on players’ and observers’ aggressive cognitions and aggressive behaviors,2020,Street Fighter II,not_reported,The sample comprised 192 12-year-old children (50% girls) attending three primary schools from Chongqing in the Southwest of China.,randomized_controlled_trial,player versus observer effect on aggression,Behavioral,positive,NaN,NaN,randomized_controlled_trial,0.1350,"""Results showed that players displayed more aggressive cognitions and behaviors than observers.""",needs_review
365,paper_007,Effects of violent video games on players’ and observers’ aggressive cognitions and aggressive behaviors,2020,Tetris,not_reported,The sample comprised 192 12-year-old children (50% girls) attending three primary schools from Chongqing in the Southwest of China.,randomized_controlled_trial,player versus observer effect on aggression,Behavioral,positive,NaN,NaN,randomized_controlled_trial,0.1350,"""Results showed that players displayed more aggressive cognitions and behaviors than observers.""",needs_review
366,paper_007,Effects of violent video games on players’ and observers’ aggressive cognitions and aggressive behaviors,2020,Tetris,not_reported,The sample comprised 192 12-year-old children (50% girls) attending three primary schools from Chongqing in the Southwest of China.,randomized_controlled_trial,sex (male) effect on aggression in violent play,Behavioral,positive,NaN,NaN,randomized_controlled_trial,0.1350,"""Boys displayed more aggressive cognitions and behaviors than girls, but this trend was observed only in the violent game play condition.""",needs_review
356,paper_007,Effects of violent video games on players’ and observers’ aggressive cognitions and aggressive behaviors,2020,Street Fighter II,not_reported,The sample comprised 192 12-year-old children (50% girls) attending three primary schools from Chongqing in the Southwest of China.,randomized_controlled_trial,sex (male) effect on aggression in violent play,Behavioral,positive,NaN,NaN,randomized_controlled_trial,0.1350,"""Boys displayed more aggressive cognitions and behaviors than girls, but this trend was observed only in the violent game play condition.""",needs_review
355,paper_007,Effects of violent video games on players’ and observers’ aggressive cognitions and aggressive behaviors,2020,Street Fighter II,not_reported,The sample comprised 192 12-year-old children (50% girls) attending three primary schools from Chongqing in the Southwest of China.,randomized_controlled_trial,player versus observer effect on aggression,Behavioral,positive,NaN,NaN,randomized_controlled_trial,0.1350,"""Results showed that players displayed more aggressive cognitions and behaviors than observers.""",needs_review
360,paper_007,Effects of violent video games on players’ and observers’ aggressive cognitions and aggressive behaviors,2020,Tetris,not_reported,The sample comprised 192 12-year-old children (50% girls) attending three primary schools from Chongqing in the Southwest of China.,randomized_controlled_trial,player versus observer effect on aggression,Behavioral,positive,NaN,NaN,randomized_controlled_trial,0.1350,"""Results showed that players displayed more aggressive cognitions and behaviors than observers.""",needs_review
361,paper_007,Effects of violent video games on players’ and observers’ aggressive cognitions and aggressive behaviors,2020,Tetris,not_reported,The sample comprised 192 12-year-old children (50% girls) attending three primary schools from Chongqing in the Southwest of China.,randomized_controlled_trial,sex (male) effect on aggression in violent play,Behavioral,positive,NaN,NaN,randomized_controlled_trial,0.1350,"""Boys displayed more aggressive cognitions and behaviors than girls, but this trend was observed only in the violent game play condition.""",needs_review

In [20]:
answer = llm_synthesize(
    "What does the evidence say about video games and aggression-related behavioral outcomes?",
    aggression,
    max_rows=25,
)

print(answer)

Supported findings
- No behavioral effect in a lab experiment of violent vs nonviolent (and competitive) game versions: paper_129 (N=64; 2x2 design) reported that neither violence nor competition impacted aggressive behaviour (TCRTT). (paper_129)
- Short-term increase on a self-report aggression index after play: paper_181 (N=24, pupils aged 12–14) reported the Buss–Durkey aggression score rose from 17.3 before the game to 21.7 after the game. (paper_181)

Related psychological finding (not direct behavior)
- Players of violent games reported perceiving their own daily-life aggressive acts as less aggressive (perceived aggressiveness decreased; d = 0.84, p < .001) in paper_009 (N=82 adults). This is a subjective/perceptual outcome rather than an observed behavioral measure. (paper_009)

Caveats
- Measurement and reporting problems: paper_129 noted poor validity of the TCRTT and a delay between play and the aggression task; paper_129 and paper_181 did not report effect sizes/p-values for the behavioral change. (paper_129, paper_181)
- Small samples and different populations (adults vs adolescents) limit generalizability. (paper_129, paper_181, paper_009)
- Some evidence addresses perceptions or affect rather than objectively measured aggressive acts. (paper_009)

Bottom line: the provided studies give mixed, limited evidence — one study found no effect on observed aggressive behaviour (paper_129), one small study found an increase in self-reported aggression after play (paper_181), and another found reduced perceived aggressiveness of one’s own actions after violent play (paper_009).

In [21]:
learning = supported(df)

learning = learning[
    learning[["outcome_category", "outcome_canonical", "outcome_raw", "paper_title", "source_quote"]]
    .astype(str)
    .agg(" ".join, axis=1)
    .str.contains(
        "education|learning|student|students|school|teacher|teachers|academic|achievement|motivation|knowledge|skills|vocabulary|STEM|geography|math|mathematics|literacy",
        case=False,
        na=False,
        regex=True,
    )
]

learning = learning[
    [col for col in ANSWER_COLS if col in learning.columns]
].sort_values("edge_weight", ascending=False)

display(summarize_counts(learning))
display(learning.head(50))

   rows  papers  games  mechanics  outcomes  positive  negative  mixed  null
0  1152      90    123         31       251       863       116     78     0

,paper_id,paper_title,year,game_name,mechanic_name,population_raw,study_design,outcome_canonical,outcome_category,effect_direction,effect_size_raw,p_value,evidence_strength,edge_weight,source_quote,review_status
1536,paper_071,Video games can develop graduate skills in higher education students: A randomised trial,2016,Minecraft,Building,Undergraduate students in the Arts and Humanities,randomized_controlled_trial,adaptability,graduate_attribute,positive,mean score change 1.15 standard deviations more positive in the intervention group than the control,0.002,randomized_controlled_trial,0.225,"A large effect size was observed with mean score change 1.1, 1.15, and 0.9 standard deviations more positive in the intervention group than the control on the communication, adaptability, and resourcefulness scales r...",needs_review
3170,paper_174,Does playing video games improve laparoscopic skills?,2012,NaN,not_reported,30 surgical novices were matched and randomised to 5 week VG training to in Half Life/HL (similar to endoscopy n = 15) or Chessmaster/CM (cognitive skills n = 15) and 10 in the control group with no game training.,randomized_controlled_trial,simulator performance (GI Mentor II surface examined),Performance,positive,HL: Diff = 4.60 (p = 0.039); CM: Diff = 1.67 (p = 0.20); Cont: Diff = 0.50 (p = 0.79),p = 0.039; p = 0.20; p = 0.79,randomized_controlled_trial,0.225,Only the HL group showed a signiﬁcant improvement on the “surface examined” test (p = 0.039). HL: Diff = 4.60 (p = 0.039) CM: Diff = 1.67 (p = 0.20) Cont: Diff = 0.50 (p = 0.79),needs_review
1564,paper_071,Video games can develop graduate skills in higher education students: A randomised trial,2016,Minecraft,Exploration,Undergraduate students in the Arts and Humanities,randomized_controlled_trial,adaptability,graduate_attribute,positive,mean score change 1.15 standard deviations more positive in the intervention group than the control,0.002,randomized_controlled_trial,0.225,"A large effect size was observed with mean score change 1.1, 1.15, and 0.9 standard deviations more positive in the intervention group than the control on the communication, adaptability, and resourcefulness scales r...",needs_review
1565,paper_071,Video games can develop graduate skills in higher education students: A randomised trial,2016,Minecraft,Perspective Taking,Undergraduate students in the Arts and Humanities,randomized_controlled_trial,adaptability,graduate_attribute,positive,mean score change 1.15 standard deviations more positive in the intervention group than the control,0.002,randomized_controlled_trial,0.225,"A large effect size was observed with mean score change 1.1, 1.15, and 0.9 standard deviations more positive in the intervention group than the control on the communication, adaptability, and resourcefulness scales r...",needs_review
1566,paper_071,Video games can develop graduate skills in higher education students: A randomised trial,2016,Minecraft,Cooperative Play,Undergraduate students in the Arts and Humanities,randomized_controlled_trial,resourcefulness,graduate_attribute,positive,mean score change 0.9 standard deviations more positive in the intervention group than the control,0.013,randomized_controlled_trial,0.225,"A large effect size was observed with mean score change 1.1, 1.15, and 0.9 standard deviations more positive in the intervention group than the control on the communication, adaptability, and resourcefulness scales r...",needs_review
1567,paper_071,Video games can develop graduate skills in higher education students: A randomised trial,2016,Minecraft,Building,Undergraduate students in the Arts and Humanities,randomized_controlled_trial,resourcefulness,graduate_attribute,positive,mean score change 0.9 standard deviations more positive in the intervention group than the control,0.013,randomized_controlled_trial,0.225,"A large effect size was observed with mean score change 1.1, 1.15, and 0.9 standard deviations more positive in the intervention group than the control on the communication, adaptability, and resourcefulness scales r...",needs_review
1568,paper_071,Video games can develop graduate skills in higher education students: A randomised trial,2016,Minecraft,Exploration,Undergraduate students in the Arts and Humanities,randomized_controlled_trial,resourcefulness,graduate_attribute,positive,mean score change 0.9 standard deviations more positive in the intervention group than the control,0.013,randomized_controlled_trial,0.225,"A large effect size was observed with mean score change 1.1, 1.15, and 0.9 standard deviations more positive in the intervention group than the control on the communication, adaptability, and resourcefulness scales r...",needs_review
1569,paper_071,Video games can develop graduate skills in higher education students: A randomised trial,2016,Minecraft,Perspective Taking,Undergraduate students in the Arts and Humanities,randomized_controlled_trial,resourcefulness,graduate_attribute,positive,mean score change 0.9 standard deviations more positive in the intervention group than the control,0.013,randomized_controlled_trial,0.225,"A large effect size was observed with mean score change 1.1, 1.15, and 0.9 standard deviations more positive in the intervention group than the control on the communication, adaptability, and resourcefulness scales r...",needs_review
1528,paper_071,Video games can develop graduate skills in higher education students: A randomised trial,2016,Borderlands 2,not_reported,Undergraduate students in the Arts and Humanities,randomized_controlled_trial,communication,graduate_attribute,positive,mean score change 1.1 standard deviations more positive in the intervention group than the control,0.004,randomized_controlled_trial,0.225,"A large effect size was observed with mean score change 1.1, 1.15, and 0.9 standard deviations more positive in the intervention group than the control on the communication, adaptability, and resourcefulness scales r...",needs_review
1519,paper_069,Effects of commercial video games on cognitive elaboration of physical concepts,2015,Cut the Rope,Level Progression,"A total of 83 students (15e16 years old), were randomly assigned to an experimental group (review using commercial casual games) or a control group (lecture-based review).",randomized_controlled_trial,cognitive elaboration (concept map scores),Learning,positive,not_reported,not_reported,randomized_controlled_trial,0.225,"Our results suggest that (a) the games supported the elaboration potential of learned physical concepts as measured by concept maps, and (b) concept maps are more suitable than multiple-choice tests for estimating th...",needs_review
1518,paper_069,Effects of commercial video games on cognitive elaboration of physical concepts,2015,Cut the Rope,Tool Use,"A total of 83 students (15e16 years old), were randomly assigned to an experimental group (review using commercial casual games) or a control group (lecture-based review).",randomized_controlled_trial,cognitive elaboration (concept map scores),Learning,positive,not_reported,not_reported,randomized_controlled_trial,0.225,"Our results suggest that (a) the games supported the elaboration potential of learned physical concepts as measured by concept maps, and (b) concept maps are more suitable than multiple-choice tests for estimating th...",needs_review
1517,paper_069,Effects of commercial video games on cognitive elaboration of physical concepts,2015,Cut the Rope,Star Collection,"A total of 83 students (15e16 years old), were randomly assigned to an experimental group (review using commercial casual games) or a control group (lecture-based review).",randomized_controlled_trial,cognitive elaboration (concept map scores),Learning,positive,not_reported,not_reported,randomized_controlled_trial,0.225,"Our results suggest that (a) the games supported the elaboration potential of learned physical concepts as measured by concept maps, and (b) concept maps are more suitable than multiple-choice tests for estimating th...",needs_review
1516,paper_069,Effects of commercial video games on cognitive elaboration of physical concepts,2015,Cut the Rope,Timing,"A total of 83 students (15e16 years old), were randomly assigned to an experimental group (review using commercial casual games) or a control group (lecture-based review).",randomized_controlled_trial,cognitive elaboration (concept map scores),Learning,positive,not_reported,not_reported,randomized_controlled_trial,0.225,"Our results suggest that (a) the games supported the elaboration potential of learned physical concepts as measured by concept maps, and (b) concept maps are more suitable than multiple-choice tests for estimating th...",needs_review
1515,paper_069,Effects of commercial video games on cognitive elaboration of physical concepts,2015,Cut the Rope,Physics Interaction,"A total of 83 students (15e16 years old), were randomly assigned to an experimental group (review using commercial casual games) or a control group (lecture-based review).",randomized_controlled_trial,cognitive elaboration (concept map scores),Learning,positive,not_reported,not_reported,randomized_controlled_trial,0.225,"Our results suggest that (a) the games supported the elaboration potential of learned physical concepts as measured by concept maps, and (b) concept maps are more suitable than multiple-choice tests for estimating th...",needs_review
1514,paper_069,Effects of commercial video games on cognitive elaboration of physical concepts,2015,Cut the Rope,Puzzle Solving,"A total of 83 students (15e16 years old), were randomly assigned to an experimental group (review using commercial casual games) or a control group (lecture-based review).",randomized_controlled_trial,cognitive elaboration (concept map scores),Learning,positive,not_reported,not_reported,randomized_controlled_trial,0.225,"Our results suggest that (a) the games supported the elaboration potential of learned physical concepts as measured by concept maps, and (b) concept maps are more suitable than multiple-choice tests for estimating th...",needs_review
1513,paper_069,Effects of commercial video games on cognitive elaboration of physical concepts,2015,Cut the Rope,Rope Cutting,"A total of 83 students (15e16 years old), were randomly assigned to an experimental group (review using commercial casual games) or a control group (lecture-based review).",randomized_controlled_trial,cognitive elaboration (concept map scores),Learning,positive,not_reported,not_reported,randomized_controlled_trial,0.225,"Our results suggest that (a) the games supported the elaboration potential of learned physical concepts as measured by concept maps, and (b) concept maps are more suitable than multiple-choice tests for estimating th...",needs_review
1511,paper_069,Effects of commercial video games on cognitive elaboration of physical concepts,2015,Angry Bird Space,not_reported,"A total of 83 students (15e16 years old), were randomly assigned to an experimental group (review using commercial casual games) or a control group (lecture-based review).",randomized_controlled_trial,cognitive elaboration (concept map scores),Learning,positive,not_reported,not_reported,randomized_controlled_trial,0.225,"Our results suggest that (a) the games supported the elaboration potential of learned physical concepts as measured by concept maps, and (b) concept maps are more suitable than multiple-choice tests for estimating th...",needs_review
1503,paper_069,Effects of commercial video games on cognitive elaboration of physical concepts,2015,Cut the Rope,Level Progression,"A total of 83 students (15e16 years old), were randomly assigned to an experimental group (review using commercial casual games) or a control group (lecture-based review).",randomized_controlled_trial,cognitive elaboration (concept map scores),Learning,positive,not_reported,not_reported,randomized_controlled_trial,0.225,"Our results suggest that (a) the games supported the elaboration potential of learned physical concepts as measured by concept maps, and (b) concept maps are more suitable than multiple-choice tests for estimating th...",needs_review
1502,paper_069,Effects of commercial video games on cognitive elaboration of physical concepts,2015,Cut the Rope,Tool Use,"A total of 83 students (15e16 years old), were randomly assigned to an experimental group (review using commercial casual games) or a control group (lecture-based review).",randomized_controlled_trial,cognitive elaboration (concept map scores),Learning,positive,not_reported,not_reported,randomized_controlled_trial,0.225,"Our results suggest that (a) the games supported the elaboration potential of learned physical concepts as measured by concept maps, and (b) concept maps are more suitable than multiple-choice tests for estimating th...",needs_review
1501,paper_069,Effects of commercial video games on cognitive elaboration of physical concepts,2015,Cut the Rope,Star Collection,"A total of 83 students (15e16 years old), were randomly assigned to an experimental group (review using commercial casual games) or a control group (lecture-based review).",randomized_controlled_trial,cognitive elaboration (concept map scores),Learning,positive,not_reported,not_reported,randomized_controlled_trial,0.225,"Our results suggest that (a) the games supported the elaboration potential of learned physical concepts as measured by concept maps, and (b) concept maps are more suitable than multiple-choice tests for estimating th...",needs_review
1500,paper_069,Effects of commercial video games on cognitive elaboration of physical concepts,2015,Cut the Rope,Timing,"A total of 83 students (15e16 years old), were randomly assigned to an experimental group (review using commercial casual games) or a control group (lecture-based review).",randomized_controlled_trial,cognitive elaboration (concept map scores),Learning,positive,not_reported,not_reported,randomized_controlled_trial,0.225,"Our results suggest that (a) the games supported the elaboration potential of learned physical concepts as measured by concept maps, and (b) concept maps are more suitable than multiple-choice tests for estimating th...",needs_review
1499,paper_069,Effects of commercial video games on cognitive elaboration of physical concepts,2015,Cut the Rope,Physics Interaction,"A total of 83 students (15e16 years old), were randomly assigned to an experimental group (review using commercial casual games) or a control group (lecture-based review).",randomized_controlled_trial,cognitive elaboration (concept map scores),Learning,positive,not_reported,not_reported,randomized_controlled_trial,0.225,"Our results suggest that (a) the games supported the elaboration potential of learned physical concepts as measured by concept maps, and (b) concept maps are more suitable than multiple-choice tests for estimating th...",needs_review
1498,paper_069,Effects of commercial video games on cognitive elaboration of physical concepts,2015,Cut the Rope,Puzzle Solving,"A total of 83 students (15e16 years old), were randomly assigned to an experimental group (review using commercial casual games) or a control group (lecture-based review).",randomized_controlled_trial,cognitive elaboration (concept map scores),Learning,positive,not_reported,not_reported,randomized_controlled_trial,0.225,"Our results suggest that (a) the games supported the elaboration potential of learned physical concepts as measured by concept maps, and (b) concept maps are more suitable than multiple-choice tests for estimating th...",needs_review
1497,paper_069,Effects of commercial video games on cognitive elaboration of physical concepts,2015,Cut the Rope,Rope Cutting,"A total of 83 students (15e16 years old), were randomly assigned to an experimental group (review using commercial casual games) or a control group (lecture-based review).",randomized_controlled_trial,cognitive elaboration (concept map scores),Learning,positive,not_reported,not_reported,randomized_controlled_trial,0.225,"Our results suggest that (a) the games supported the elaboration potential of learned physical concepts as measured by concept maps, and (b) concept maps are more suitable than multiple-choice tests for estimating th...",needs_review
3347,paper_196,Use of commercial video games to improve postural balance in patients with multiple sclerosis: A systematic review and meta-analysis of randomised controlled clinical trials,2021,NaN,not_reported,patients with multiple sclerosis (MS),randomized_controlled_trial,clinical_significance_relative_to_minimum_detectable_change,postural_balance_interpretation,NaN,not greater than the minimum detectable change reported in the literature,not_reported,randomized_controlled_trial,0.225,but these were not greater than the minimum detectable change reported in the literature.,needs_review
3346,paper_196,Use of commercial video games to improve postural balance in patients with multiple sclerosis: A systematic review and meta-analysis of randomised controlled clinical trials,2021,NaN,not_reported,patients with multiple sclerosis (MS),randomized_controlled_trial,Berg Balance Scale (BBS),postural_balance,positive,DM: 5.30,< .001,randomized_controlled_trial,0.225,"We did observe intergroup differences in BBS scores in favour of video game therapy (DM: 5.30; 95% CI,3.39—7.21; P < .001; I2 = 0%), but these were not greater than the minimum detectable change reported in the liter...",needs_review
3345,paper_196,Use of commercial video games to improve postural balance in patients with multiple sclerosis: A systematic review and meta-analysis of randomised controlled clinical trials,2021,NaN,not_reported,patients with multiple sclerosis (MS),randomized_controlled_trial,Timed 25-Foot Walk,postural_balance,NaN,DM: .15,.75,randomized_controlled_trial,0.225,"We found no signiﬁcant differences between the video game therapy group and the control group in ... Timed 25-Foot Walk scores (DM: .15; 95% CI, −1.06 to .76; P = .75; I2 = 0%)",needs_review
1530,paper_071,Video games can develop graduate skills in higher education students: A randomised trial,2016,Borderlands 2,not_reported,Undergraduate students in the Arts and Humanities,randomized_controlled_trial,resourcefulness,graduate_attribute,positive,mean score change 0.9 standard deviations more positive in the intervention group than the control,0.013,randomized_controlled_trial,0.225,"A large effect size was observed with mean score change 1.1, 1.15, and 0.9 standard deviations more positive in the intervention group than the control on the communication, adaptability, and resourcefulness scales r...",needs_review
2499,paper_142,Effects of reward and punishment in prosocial video games on attentional bias and prosocial behaviors,2022,not_reported,not_reported,"College student volunteers (N = 40) were randomly assigned to the prosocial game group (n = 20; 50% female, mean age: 22.7 years, range: 19–28 years) or to the control group (n = 20; 40% female, mean age: 21.4 years,...",randomized_controlled_trial,post-game attentional bias,Cognitive,positive,not_reported,not_reported,randomized_controlled_trial,0.225,"Based on the General Learning Model, previous studies have examined how video game content affects players’ post-game attentional bias toward prosocial information ... In Experiment 1, reward and punishment were cont...",needs_review

In [22]:
answer = llm_synthesize(
    "What does the evidence say about games for education or learning outcomes?",
    learning,
    max_rows=25,
)

print(answer)

Supported findings
- paper_071: A randomized trial in undergraduate Arts/Humanities students found large, statistically significant improvements in graduate-attribute scores after game-based interventions—communication: +1.1 SD (p=0.004), adaptability: +1.15 SD (p=0.002), resourcefulness: +0.9 SD (p=0.013) (games: Minecraft, Borderlands 2 reported).
- paper_069: A randomized trial with 83 adolescents (15–16 y) reported that commercial casual games (e.g., Cut the Rope, Angry Birds Space) "supported the elaboration potential of learned physical concepts" as measured by concept maps (effect direction: positive); effect sizes and p-values not reported.
- paper_174: A randomized trial of 30 surgical novices showed that 5 weeks of Half-Life training improved laparoscopic simulator performance ("surface examined") (Diff = 4.60, p = 0.039); a Chessmaster group and the no‑training control did not show significant improvements.

Caveats
- Reporting gaps: paper_069 did not report effect sizes or p-values, and some entries omit game names or mechanics in structured fields.
- Generalizability: studies target different populations and outcomes (graduate attributes, cognitive elaboration, procedural simulator performance), so benefits may be outcome- and population-specific (paper_071, paper_069, paper_174).
- Small samples: the surgical study had a small sample (30 novices) and effects varied by game (paper_174).

In [25]:
stem_learning = learning[
    learning[["paper_title", "outcome_canonical",  "source_quote"]]
    .astype(str)
    .agg(" ".join, axis=1)
    .str.contains(
        "STEM|science|math|mathematics|geography|genetics|computational|vocabulary|spelling",
        case=False,
        na=False,
        regex=True,
    )
]

display(summarize_counts(stem_learning))
display(stem_learning.head(50))

   rows  papers  games  mechanics  outcomes  positive  negative  mixed  null
0   428      35     50         24        98       291        85     29     0

,paper_id,paper_title,year,game_name,mechanic_name,population_raw,study_design,outcome_canonical,outcome_category,effect_direction,effect_size_raw,p_value,evidence_strength,edge_weight,source_quote,review_status
3347,paper_196,Use of commercial video games to improve postural balance in patients with multiple sclerosis: A systematic review and meta-analysis of randomised controlled clinical trials,2021,NaN,not_reported,patients with multiple sclerosis (MS),randomized_controlled_trial,clinical_significance_relative_to_minimum_detectable_change,postural_balance_interpretation,NaN,not greater than the minimum detectable change reported in the literature,not_reported,randomized_controlled_trial,0.2250,but these were not greater than the minimum detectable change reported in the literature.,needs_review
3346,paper_196,Use of commercial video games to improve postural balance in patients with multiple sclerosis: A systematic review and meta-analysis of randomised controlled clinical trials,2021,NaN,not_reported,patients with multiple sclerosis (MS),randomized_controlled_trial,Berg Balance Scale (BBS),postural_balance,positive,DM: 5.30,< .001,randomized_controlled_trial,0.2250,"We did observe intergroup differences in BBS scores in favour of video game therapy (DM: 5.30; 95% CI,3.39—7.21; P < .001; I2 = 0%), but these were not greater than the minimum detectable change reported in the liter...",needs_review
3345,paper_196,Use of commercial video games to improve postural balance in patients with multiple sclerosis: A systematic review and meta-analysis of randomised controlled clinical trials,2021,NaN,not_reported,patients with multiple sclerosis (MS),randomized_controlled_trial,Timed 25-Foot Walk,postural_balance,NaN,DM: .15,.75,randomized_controlled_trial,0.2250,"We found no signiﬁcant differences between the video game therapy group and the control group in ... Timed 25-Foot Walk scores (DM: .15; 95% CI, −1.06 to .76; P = .75; I2 = 0%)",needs_review
537,paper_015,Can video games enhance surgical skills acquisition for medical students? A systematic review,2020,NaN,not_reported,40 students,randomized_controlled_trial,time_to_completion,surgical_task_performance,positive,71.7 to 44.0 s vs 50.8 to 39.7 s,P = .006,randomized_controlled_trial,0.2250,"Harrington et al,14 who randomized 40 students to either a Wii U VGBT group or a non-VGBT control group, who then performed LAP Mentor tasks. Signiﬁcant reductions in time to completion were observed (71.7 to 44.0 s ...",needs_review
536,paper_015,Can video games enhance surgical skills acquisition for medical students? A systematic review,2020,Wii U,not_reported,40 students,randomized_controlled_trial,time_to_completion,surgical_task_performance,positive,71.7 to 44.0 s vs 50.8 to 39.7 s,P = .006,randomized_controlled_trial,0.2250,"Harrington et al,14 who randomized 40 students to either a Wii U VGBT group or a non-VGBT control group, who then performed LAP Mentor tasks. Signiﬁcant reductions in time to completion were observed (71.7 to 44.0 s ...",needs_review
3344,paper_196,Use of commercial video games to improve postural balance in patients with multiple sclerosis: A systematic review and meta-analysis of randomised controlled clinical trials,2021,NaN,not_reported,patients with multiple sclerosis (MS),randomized_controlled_trial,Four Step Square Test,postural_balance,NaN,DM: −.74,.48,randomized_controlled_trial,0.2250,"We found no signiﬁcant differences between the video game therapy group and the control group in Four Step Square Test (DM: −.74; 95% CI, −2.79 to 1.32; P = .48; I2 = 0%)",needs_review
2644,paper_158,Digital game-based spelling intervention for children with spelling deficits: A randomized controlled trial,2024,NaN,not_reported,Participants were 65 German speaking second- and third-graders with spelling disorder.,randomized_controlled_trial,phoneme-grapheme mapping,precursor_skill,positive,not_reported,not_reported,randomized_controlled_trial,0.2250,"Results showed intervention effects for precursor skills (i.e., phoneme-graphene mapping and phoneme awareness)",needs_review
3244,paper_182,Procedia - Social and Behavioral Sciences 98 ( 2014 ) 286 – 291,2014,NaN,not_reported,"The participants, (24) low-intermediate EFL learners... Forty five lower intermediate learners, ranging from 16-22 years old learning English as a foreign language (studying at Khorasan Language Institute in Kashmar,...",randomized_controlled_trial,English vocabulary learning (post-test score),Learning,positive,not_reported,not_reported,randomized_controlled_trial,0.2250,The findings of the analyzed data indicated that the experimental group outperformed the control group statistically significant in the post-test.,needs_review
3245,paper_182,Procedia - Social and Behavioral Sciences 98 ( 2014 ) 286 – 291,2014,NaN,not_reported,"The participants, (24) low-intermediate EFL learners... Forty five lower intermediate learners, ranging from 16-22 years old learning English as a foreign language (studying at Khorasan Language Institute in Kashmar,...",randomized_controlled_trial,English vocabulary learning (post-test score),Learning,positive,not_reported,not_reported,randomized_controlled_trial,0.2250,The findings of the analyzed data indicated that the experimental group outperformed the control group statistically significant in the post-test.,needs_review
3297,paper_191,This is an open access article under the CC BY-NC-ND license (https://creativecommons.org/licenses/by-nc-nd/4.0) Peer-review under responsibility of the scientific committee of the 5th International Conference on Com...,2021,not_reported,not_reported,"Initial study: 297 participants split into 2 groups (149 played video games, 148 used traditional educational app). Follow-up study: 122 participants split into 2 groups (64 played video games, 58 used traditional ed...",randomized_controlled_trial,behaviour change in decision-making,interpreted_construct,positive,not_reported,not_reported,randomized_controlled_trial,0.2250,"Physicians who played the video game has more significant behaviour change. Therefore, the video game has bigger impact to participants compared to traditional educational app.",needs_review
3299,paper_191,This is an open access article under the CC BY-NC-ND license (https://creativecommons.org/licenses/by-nc-nd/4.0) Peer-review under responsibility of the scientific committee of the 5th International Conference on Com...,2021,not_reported,not_reported,"Initial study: 297 participants split into 2 groups (149 played video games, 148 used traditional educational app). Follow-up study: 122 participants split into 2 groups (64 played video games, 58 used traditional ed...",randomized_controlled_trial,behaviour change in decision-making,interpreted_construct,positive,not_reported,not_reported,randomized_controlled_trial,0.2250,"Physicians who played the video game has more significant behaviour change. Therefore, the video game has bigger impact to participants compared to traditional educational app.",needs_review
3301,paper_191,This is an open access article under the CC BY-NC-ND license (https://creativecommons.org/licenses/by-nc-nd/4.0) Peer-review under responsibility of the scientific committee of the 5th International Conference on Com...,2021,not_reported,not_reported,"Participants were generally people who don’t play video games naturally, split into 2 random groups.",randomized_controlled_trial,improvement in target cognitive tasks,neurocognitive,positive,not_reported,not_reported,randomized_controlled_trial,0.2250,"An experiment conducted with pre-testing and post-testing. Participants were generally people who don’t play video games naturally, split into 2 random groups. One group play action video game for 10 – 50 hours, with...",needs_review
3303,paper_191,This is an open access article under the CC BY-NC-ND license (https://creativecommons.org/licenses/by-nc-nd/4.0) Peer-review under responsibility of the scientific committee of the 5th International Conference on Com...,2021,not_reported,not_reported,"Participants were generally people who don’t play video games naturally, split into 2 random groups.",randomized_controlled_trial,improvement in target cognitive tasks,neurocognitive,positive,not_reported,not_reported,randomized_controlled_trial,0.2250,"An experiment conducted with pre-testing and post-testing. Participants were generally people who don’t play video games naturally, split into 2 random groups. One group play action video game for 10 – 50 hours, with...",needs_review
3319,paper_194,"Impact of an active educational video game on children’s motivation, science knowledge, and physical activity",2014,not_reported,not_reported,"In this randomized controlled study, 53 elementary school students were assigned to an experimental condition or a comparison condition.",randomized_controlled_trial,science knowledge (test performance),Learning,NaN,η2 = 0.486 (pre-post),p < 0.001 (pre-post); between-group difference not significant,randomized_controlled_trial,0.2250,"students in both groups performed better on the post-test than they did on the pre-test (p < 0.001, η2 = 0.486), and their post-test scores did not differ signiﬁcantly.",needs_review
3320,paper_194,"Impact of an active educational video game on children’s motivation, science knowledge, and physical activity",2014,not_reported,not_reported,"In this randomized controlled study, 53 elementary school students were assigned to an experimental condition or a comparison condition.",randomized_controlled_trial,physical activity intensity (heart rate),Physiological,positive,t = 7.212,p < 0.001,randomized_controlled_trial,0.2250,"the students’ average heart rates (HRs) were in the Target-Heart-Rate-Zone (HR = 134 bpm), which was signiﬁcantly higher than the average HR (103 bpm) from the comparison condition (t = 7.212, p < 0.001).",needs_review
533,paper_015,Can video games enhance surgical skills acquisition for medical students? A systematic review,2020,portable virtual reality (VR),Movement Control,14 medical students,randomized_controlled_trial,time_to_completion,surgical_task_performance,mixed,"51.34 to 32.23 s, P < .05; 168.94 to 68.01 s, P < .05 versus 40.23 to 31.07 s, P < .05; 156.49 to 154.22 s, P > .05","some P < .05, one P > .05 as reported",randomized_controlled_trial,0.2250,Chien et al20 randomized 14 medical students to a 3-D tennis game VGBT group or a portable virtual reality (VR) training comparison group. They observed that the VR training group demonstrated a signiﬁcant reduction ...,needs_review
3322,paper_194,"Impact of an active educational video game on children’s motivation, science knowledge, and physical activity",2014,not_reported,not_reported,"In this randomized controlled study, 53 elementary school students were assigned to an experimental condition or a comparison condition.",randomized_controlled_trial,science knowledge (test performance),Learning,NaN,η2 = 0.486 (pre-post),p < 0.001 (pre-post); between-group difference not significant,randomized_controlled_trial,0.2250,"students in both groups performed better on the post-test than they did on the pre-test (p < 0.001, η2 = 0.486), and their post-test scores did not differ signiﬁcantly.",needs_review
3323,paper_194,"Impact of an active educational video game on children’s motivation, science knowledge, and physical activity",2014,not_reported,not_reported,"In this randomized controlled study, 53 elementary school students were assigned to an experimental condition or a comparison condition.",randomized_controlled_trial,physical activity intensity (heart rate),Physiological,positive,t = 7.212,p < 0.001,randomized_controlled_trial,0.2250,"the students’ average heart rates (HRs) were in the Target-Heart-Rate-Zone (HR = 134 bpm), which was signiﬁcantly higher than the average HR (103 bpm) from the comparison condition (t = 7.212, p < 0.001).",needs_review
3340,paper_196,Use of commercial video games to improve postural balance in patients with multiple sclerosis: A systematic review and meta-analysis of randomised controlled clinical trials,2021,NaN,not_reported,patients with multiple sclerosis (MS),randomized_controlled_trial,Four Step Square Test,postural_balance,NaN,DM: −.74,.48,randomized_controlled_trial,0.2250,"We found no signiﬁcant differences between the video game therapy group and the control group in Four Step Square Test (DM: −.74; 95% CI, −2.79 to 1.32; P = .48; I2 = 0%)",needs_review
3341,paper_196,Use of commercial video games to improve postural balance in patients with multiple sclerosis: A systematic review and meta-analysis of randomised controlled clinical trials,2021,NaN,not_reported,patients with multiple sclerosis (MS),randomized_controlled_trial,Timed 25-Foot Walk,postural_balance,NaN,DM: .15,.75,randomized_controlled_trial,0.2250,"We found no signiﬁcant differences between the video game therapy group and the control group in ... Timed 25-Foot Walk scores (DM: .15; 95% CI, −1.06 to .76; P = .75; I2 = 0%)",needs_review
2645,paper_158,Digital game-based spelling intervention for children with spelling deficits: A randomized controlled trial,2024,NaN,not_reported,Participants were 65 German speaking second- and third-graders with spelling disorder.,randomized_controlled_trial,phoneme awareness,precursor_skill,positive,not_reported,not_reported,randomized_controlled_trial,0.2250,"Results showed intervention effects for precursor skills (i.e., phoneme-graphene mapping and phoneme awareness)",needs_review
3321,paper_194,"Impact of an active educational video game on children’s motivation, science knowledge, and physical activity",2014,not_reported,not_reported,"In this randomized controlled study, 53 elementary school students were assigned to an experimental condition or a comparison condition.",randomized_controlled_trial,situational interest (perceived),Psychological,positive,η2 = 0.301,p < 0.01,randomized_controlled_trial,0.2250,"Students in the experimental condition perceived a higher level of situational interest than their counterparts in the comparison group (p < 0.01, and η2 = 0.301).",needs_review
2638,paper_158,Digital game-based spelling intervention for children with spelling deficits: A randomized controlled trial,2024,NaN,not_reported,Participants were 65 German speaking second- and third-graders with spelling disorder.,randomized_controlled_trial,phoneme awareness,precursor_skill,positive,not_reported,not_reported,randomized_controlled_trial,0.2250,"Results showed intervention effects for precursor skills (i.e., phoneme-graphene mapping and phoneme awareness)",needs_review
2637,paper_158,Digital game-based spelling intervention for children with spelling deficits: A randomized controlled trial,2024,NaN,not_reported,Participants were 65 German speaking second- and third-graders with spelling disorder.,randomized_controlled_trial,phoneme-grapheme mapping,precursor_skill,positive,not_reported,not_reported,randomized_controlled_trial,0.2250,"Results showed intervention effects for precursor skills (i.e., phoneme-graphene mapping and phoneme awareness)",needs_review
532,paper_015,Can video games enhance surgical skills acquisition for medical students? A systematic review,2020,portable virtual reality (VR),Multisensory Feedback,14 medical students,randomized_controlled_trial,time_to_completion,surgical_task_performance,mixed,"51.34 to 32.23 s, P < .05; 168.94 to 68.01 s, P < .05 versus 40.23 to 31.07 s, P < .05; 156.49 to 154.22 s, P > .05","some P < .05, one P > .05 as reported",randomized_controlled_trial,0.2250,Chien et al20 randomized 14 medical students to a 3-D tennis game VGBT group or a portable virtual reality (VR) training comparison group. They observed that the VR training group demonstrated a signiﬁcant reduction ...,needs_review
531,paper_015,Can video games enhance surgical skills acquisition for medical students? A systematic review,2020,portable virtual reality (VR),Immersive Interaction,14 medical students,randomized_controlled_trial,time_to_completion,surgical_task_performance,mixed,"51.34 to 32.23 s, P < .05; 168.94 to 68.01 s, P < .05 versus 40.23 to 31.07 s, P < .05; 156.49 to 154.22 s, P > .05","some P < .05, one P > .05 as reported",randomized_controlled_trial,0.2250,Chien et al20 randomized 14 medical students to a 3-D tennis game VGBT group or a portable virtual reality (VR) training comparison group. They observed that the VR training group demonstrated a signiﬁcant reduction ...,needs_review
530,paper_015,Can video games enhance surgical skills acquisition for medical students? A systematic review,2020,NaN,not_reported,14 medical students,randomized_controlled_trial,time_to_completion,surgical_task_performance,mixed,"51.34 to 32.23 s, P < .05; 168.94 to 68.01 s, P < .05 versus 40.23 to 31.07 s, P < .05; 156.49 to 154.22 s, P > .05","some P < .05, one P > .05 as reported",randomized_controlled_trial,0.2250,Chien et al20 randomized 14 medical students to a 3-D tennis game VGBT group or a portable virtual reality (VR) training comparison group. They observed that the VR training group demonstrated a signiﬁcant reduction ...,needs_review
3343,paper_196,Use of commercial video games to improve postural balance in patients with multiple sclerosis: A systematic review and meta-analysis of randomised controlled clinical trials,2021,NaN,not_reported,patients with multiple sclerosis (MS),randomized_controlled_trial,clinical_significance_relative_to_minimum_detectable_change,postural_balance_interpretation,NaN,not greater than the minimum detectable change reported in the literature,not_reported,randomized_controlled_trial,0.2250,but these were not greater than the minimum detectable change reported in the literature.,needs_review
3342,paper_196,Use of commercial video games to improve postural balance in patients with multiple sclerosis: A systematic review and meta-analysis of randomised controlled clinical trials,2021,NaN,not_reported,patients with multiple sclerosis (MS),randomized_controlled_trial,Berg Balance Scale (BBS),postural_balance,positive,DM: 5.30,< .001,randomized_controlled_trial,0.2250,"We did observe intergroup differences in BBS scores in favour of video game therapy (DM: 5.30; 95% CI,3.39—7.21; P < .001; I2 = 0%), but these were not greater than the minimum detectable change reported in the liter...",needs_review
3324,paper_194,"Impact of an active educational video game on children’s motivation, science knowledge, and physical activity",2014,not_reported,not_reported,"In this randomized controlled study, 53 elementary school students were assigned to an experimental condition or a comparison condition.",randomized_controlled_trial,situational interest (perceived),Psychological,positive,η2 = 0.301,p < 0.01,randomized_controlled_trial,0.2250,"Students in the experimental condition perceived a higher level of situational interest than their counterparts in the comparison group (p < 0.01, and η2 = 0.301).",needs_review
1476,paper_065,The effect of simulation games on the learning of computational problem solving,2010,simulation game,not_reported,117 students,quasi_experimental,learning depth,Learning,negative,not_reported,not_reported,quasi_experimental,0.1687,"In addition, the students who felt bored in the simulation game only learned to solve the problem at a superﬁcial level.",needs_review
1482,paper_065,The effect of simulation games on the learning of computational problem solving,2010,NaN,not_reported,117 students,quasi_experimental,learning-by-example strategy use (anxiety association),Problem solving strategies,negative,not_reported,not_reported,quasi_experimental,0.1687,"For instance, the students who felt anxious in the simulation game did not apply the learning-by-example strategy as frequently as those in the ﬂow state.",needs_review

In [26]:
answer = llm_synthesize(
    "What evidence links games to STEM, school, or academic learning outcomes?",
    stem_learning,
    max_rows=25,
)

print(answer)

Supported findings (papers and key results)
- paper_194 — Elementary school RCT (n=53): both game and comparison groups improved on a science knowledge test pre→post (p < .001), and the experimental group reported higher situational interest (p < .01, η2 = 0.301). Between-group post-test scores did not differ significantly.
- paper_158 — RCT with 65 German 2nd–3rd graders with spelling disorder: the digital game intervention produced positive effects on precursor literacy skills (phoneme–grapheme mapping and phoneme awareness). (Results reported as positive; effect sizes/p-values not provided.)
- paper_182 — RCT with 24 low‑intermediate EFL learners: the experimental (game) group outperformed the control group on an English vocabulary post-test (statistically significant).
- paper_191 — RCTs (adults/physicians and general participants): playing video games produced greater behaviour change in clinical decision‑making versus a traditional educational app, and action‑game training showed improvements on targeted cognitive tasks (pre/post).
- paper_015 — Studies in medical students: video/VR game training reduced time-to-completion on simulated surgical tasks in some comparisons, indicating improved procedural skill acquisition in medical education.

Caveats / limitations
- Several studies lack reported effect sizes or p-values (paper_158, paper_191) or have small samples (paper_182 n=24; some medical studies n≈14–40).
- For science knowledge (paper_194) there was no significant between‑group advantage of the game over the comparison condition despite pre→post gains.
- Some positive findings relate to professional or clinical training (paper_015, paper_191) rather than K–12 or STEM classroom outcomes.
- Not all rows concern school/STEM learning (e.g., paper_196 reports clinical/balance outcomes, not academic learning).

Summary
The provided evidence shows games can improve domain‑specific academic/learning outcomes (vocabulary, spelling precursor skills), increase situational interest in science, and support professional/clinical skill learning; however, effect magnitudes, statistical details, and generalizability are limited in the dataset (see paper_194, paper_158, paper_182, paper_191, paper_015).

In [27]:
tech_econ = supported(df)

tech_econ = tech_econ[
    tech_econ[["outcome_category", "outcome_canonical", "outcome_raw", "paper_title", "source_quote"]]
    .astype(str)
    .agg(" ".join, axis=1)
    .str.contains(
        "technology|technological|innovation|business model|market|economic|economics|purchase|intention|revenue|sales|monetization|microtransaction|freemium|subscription|consumer|brand|product|platform|console|mobile gaming|industry|user experience|usage|loyalty",
        case=False,
        na=False,
        regex=True,
    )
]

tech_econ = tech_econ[
    [col for col in ANSWER_COLS if col in tech_econ.columns]
].sort_values("edge_weight", ascending=False)

display(summarize_counts(tech_econ))
display(tech_econ.head(50))

   rows  papers  games  mechanics  outcomes  positive  negative  mixed  null
0   320      43     60         26        96       235        50     23     0

,paper_id,paper_title,year,game_name,mechanic_name,population_raw,study_design,outcome_canonical,outcome_category,effect_direction,effect_size_raw,p_value,evidence_strength,edge_weight,source_quote,review_status
2526,paper_145,"To screen, or not to screen: An experimental comparison of two methods for correlating video game loot box expenditure and problem gambling severity",2024,loot boxes,not_reported,N = 2027; non-screening approach; n = 1005; screening participants; n = 1022,randomized_controlled_trial,Problem gambling severity (PGSI) scores were inflated in the non-screening group relative to the screening group,interpreted_construct,positive,not_reported,not_reported,randomized_controlled_trial,0.2250,"However, problem gambling severity was inflated in the non-screening group, meaning that future research on gambling-like products should include gambling participation screening questions; better define what ‘gambli...",needs_review
2523,paper_145,"To screen, or not to screen: An experimental comparison of two methods for correlating video game loot box expenditure and problem gambling severity",2024,loot boxes,not_reported,N = 2027; non-screening approach; n = 1005; screening participants; n = 1022,randomized_controlled_trial,Problem gambling severity (PGSI) scores were inflated in the non-screening group relative to the screening group,interpreted_construct,positive,not_reported,not_reported,randomized_controlled_trial,0.2250,"However, problem gambling severity was inflated in the non-screening group, meaning that future research on gambling-like products should include gambling participation screening questions; better define what ‘gambli...",needs_review
4940,paper_296,Open Access Game-based learning and gamification in initial teacher training in the social sciences: an experiment with MinecraftEdu,2012,MinecraftEdu,Building,second-year university students who are pursuing a degree in Primary Education and are enrolled in a subject entitled Social Sciences II: History and Teaching at Castilla-La Mancha University.,quasi_experimental,educational innovation,learning/innovation,positive,not_reported,not_reported,quasi_experimental,0.1687,"Interest level, educational innovation and motivation are valued positively and show statistically significant improvements.",needs_review
4938,paper_296,Open Access Game-based learning and gamification in initial teacher training in the social sciences: an experiment with MinecraftEdu,2012,MinecraftEdu,Perspective Taking,second-year university students who are pursuing a degree in Primary Education and are enrolled in a subject entitled Social Sciences II: History and Teaching at Castilla-La Mancha University.,quasi_experimental,interest,engagement/motivation,positive,not_reported,not_reported,quasi_experimental,0.1687,"Interest level, educational innovation and motivation are valued positively and show statistically significant improvements.",needs_review
4937,paper_296,Open Access Game-based learning and gamification in initial teacher training in the social sciences: an experiment with MinecraftEdu,2012,MinecraftEdu,Exploration,second-year university students who are pursuing a degree in Primary Education and are enrolled in a subject entitled Social Sciences II: History and Teaching at Castilla-La Mancha University.,quasi_experimental,interest,engagement/motivation,positive,not_reported,not_reported,quasi_experimental,0.1687,"Interest level, educational innovation and motivation are valued positively and show statistically significant improvements.",needs_review
4936,paper_296,Open Access Game-based learning and gamification in initial teacher training in the social sciences: an experiment with MinecraftEdu,2012,MinecraftEdu,Building,second-year university students who are pursuing a degree in Primary Education and are enrolled in a subject entitled Social Sciences II: History and Teaching at Castilla-La Mancha University.,quasi_experimental,interest,engagement/motivation,positive,not_reported,not_reported,quasi_experimental,0.1687,"Interest level, educational innovation and motivation are valued positively and show statistically significant improvements.",needs_review
4935,paper_296,Open Access Game-based learning and gamification in initial teacher training in the social sciences: an experiment with MinecraftEdu,2012,MinecraftEdu,Cooperative Play,second-year university students who are pursuing a degree in Primary Education and are enrolled in a subject entitled Social Sciences II: History and Teaching at Castilla-La Mancha University.,quasi_experimental,interest,engagement/motivation,positive,not_reported,not_reported,quasi_experimental,0.1687,"Interest level, educational innovation and motivation are valued positively and show statistically significant improvements.",needs_review
3988,paper_255,The Substitution Effect of Mobile Games on Console Games: An Empirical Analysis of the Japanese Video Game Industry,2017,PS3,not_reported,"panel data of about 100,000 observations (Japanese video game industry)",quasi_experimental,"substitution effect of mobile game play on console game use (3DS, Wii, PSP)",measured,negative,at most about 0.1,not_reported,quasi_experimental,0.1687,"The results showed that the substitution effects of playing smart devices on 3DS, Wii, and PSP were recognizable, but did not have significant effects on PS3, and the substitution effects on PSP were very small. In a...",needs_review
3985,paper_255,The Substitution Effect of Mobile Games on Console Games: An Empirical Analysis of the Japanese Video Game Industry,2017,PSP,not_reported,"panel data of about 100,000 observations (Japanese video game industry)",quasi_experimental,"substitution effect of mobile game play on console game use (3DS, Wii, PSP)",measured,negative,at most about 0.1,not_reported,quasi_experimental,0.1687,"The results showed that the substitution effects of playing smart devices on 3DS, Wii, and PSP were recognizable, but did not have significant effects on PS3, and the substitution effects on PSP were very small. In a...",needs_review
3982,paper_255,The Substitution Effect of Mobile Games on Console Games: An Empirical Analysis of the Japanese Video Game Industry,2017,Wii,not_reported,"panel data of about 100,000 observations (Japanese video game industry)",quasi_experimental,"substitution effect of mobile game play on console game use (3DS, Wii, PSP)",measured,negative,at most about 0.1,not_reported,quasi_experimental,0.1687,"The results showed that the substitution effects of playing smart devices on 3DS, Wii, and PSP were recognizable, but did not have significant effects on PS3, and the substitution effects on PSP were very small. In a...",needs_review
3979,paper_255,The Substitution Effect of Mobile Games on Console Games: An Empirical Analysis of the Japanese Video Game Industry,2017,3DS,not_reported,"panel data of about 100,000 observations (Japanese video game industry)",quasi_experimental,"substitution effect of mobile game play on console game use (3DS, Wii, PSP)",measured,negative,at most about 0.1,not_reported,quasi_experimental,0.1687,"The results showed that the substitution effects of playing smart devices on 3DS, Wii, and PSP were recognizable, but did not have significant effects on PS3, and the substitution effects on PSP were very small. In a...",needs_review
3976,paper_255,The Substitution Effect of Mobile Games on Console Games: An Empirical Analysis of the Japanese Video Game Industry,2017,smart devices,not_reported,"panel data of about 100,000 observations (Japanese video game industry)",quasi_experimental,"substitution effect of mobile game play on console game use (3DS, Wii, PSP)",measured,negative,at most about 0.1,not_reported,quasi_experimental,0.1687,"The results showed that the substitution effects of playing smart devices on 3DS, Wii, and PSP were recognizable, but did not have significant effects on PS3, and the substitution effects on PSP were very small. In a...",needs_review
1294,paper_053,The effectiveness of serious games designed for infection prevention and promotion of safe behaviors of senior nursing students during the COVID- 19 pandemic,2022,SGs (serious game),not_reported,senior nursing students of Yıldırım Beyazıt University,quasi_experimental,game usability / user experience,usability,positive,not_reported,not_reported,quasi_experimental,0.1687,The students also considered the practice of serious games an effective teaching strategy.,needs_review
1296,paper_053,The effectiveness of serious games designed for infection prevention and promotion of safe behaviors of senior nursing students during the COVID- 19 pandemic,2022,Articulate program,not_reported,senior nursing students of Yıldırım Beyazıt University,quasi_experimental,game usability / user experience,usability,positive,not_reported,not_reported,quasi_experimental,0.1687,The students also considered the practice of serious games an effective teaching strategy.,needs_review
1298,paper_053,The effectiveness of serious games designed for infection prevention and promotion of safe behaviors of senior nursing students during the COVID- 19 pandemic,2022,https://storage.googleapis.com/covidgame/COVID_Game/story.html,not_reported,senior nursing students of Yıldırım Beyazıt University,quasi_experimental,game usability / user experience,usability,positive,not_reported,not_reported,quasi_experimental,0.1687,The students also considered the practice of serious games an effective teaching strategy.,needs_review
1300,paper_053,The effectiveness of serious games designed for infection prevention and promotion of safe behaviors of senior nursing students during the COVID- 19 pandemic,2022,smartphones,not_reported,senior nursing students of Yıldırım Beyazıt University,quasi_experimental,game usability / user experience,usability,positive,not_reported,not_reported,quasi_experimental,0.1687,The students also considered the practice of serious games an effective teaching strategy.,needs_review
1302,paper_053,The effectiveness of serious games designed for infection prevention and promotion of safe behaviors of senior nursing students during the COVID- 19 pandemic,2022,tablets,not_reported,senior nursing students of Yıldırım Beyazıt University,quasi_experimental,game usability / user experience,usability,positive,not_reported,not_reported,quasi_experimental,0.1687,The students also considered the practice of serious games an effective teaching strategy.,needs_review
1304,paper_053,The effectiveness of serious games designed for infection prevention and promotion of safe behaviors of senior nursing students during the COVID- 19 pandemic,2022,laptops,not_reported,senior nursing students of Yıldırım Beyazıt University,quasi_experimental,game usability / user experience,usability,positive,not_reported,not_reported,quasi_experimental,0.1687,The students also considered the practice of serious games an effective teaching strategy.,needs_review
1306,paper_053,The effectiveness of serious games designed for infection prevention and promotion of safe behaviors of senior nursing students during the COVID- 19 pandemic,2022,desktop computers,not_reported,senior nursing students of Yıldırım Beyazıt University,quasi_experimental,game usability / user experience,usability,positive,not_reported,not_reported,quasi_experimental,0.1687,The students also considered the practice of serious games an effective teaching strategy.,needs_review
1684,paper_080,Using a serious game to communicate risk and minimize psychological distance regarding environmental pollution,2015,serious game (virtual environment),not_reported,participants (N = 190),quasi_experimental,perceived contingency (an affordance of interactivity),Technological,positive,not_reported,not_reported,quasi_experimental,0.1687,"In terms of interactivity, higher perceptions of contingency led to greater self-efficacy",needs_review
1690,paper_080,Using a serious game to communicate risk and minimize psychological distance regarding environmental pollution,2015,serious game (virtual environment),not_reported,participants (N = 190),quasi_experimental,perceived contingency (an affordance of interactivity),Technological,positive,not_reported,not_reported,quasi_experimental,0.1687,"In terms of interactivity, higher perceptions of contingency led to greater self-efficacy",needs_review
1696,paper_080,Using a serious game to communicate risk and minimize psychological distance regarding environmental pollution,2015,serious game (virtual environment),not_reported,participants (N = 190),quasi_experimental,perceived contingency (an affordance of interactivity),Technological,positive,not_reported,not_reported,quasi_experimental,0.1687,"In terms of interactivity, higher perceptions of contingency led to greater self-efficacy",needs_review
1702,paper_080,Using a serious game to communicate risk and minimize psychological distance regarding environmental pollution,2015,serious game (virtual environment),not_reported,participants (N = 190),quasi_experimental,perceived contingency (an affordance of interactivity),Technological,positive,not_reported,not_reported,quasi_experimental,0.1687,"In terms of interactivity, higher perceptions of contingency led to greater self-efficacy",needs_review
4939,paper_296,Open Access Game-based learning and gamification in initial teacher training in the social sciences: an experiment with MinecraftEdu,2012,MinecraftEdu,Cooperative Play,second-year university students who are pursuing a degree in Primary Education and are enrolled in a subject entitled Social Sciences II: History and Teaching at Castilla-La Mancha University.,quasi_experimental,educational innovation,learning/innovation,positive,not_reported,not_reported,quasi_experimental,0.1687,"Interest level, educational innovation and motivation are valued positively and show statistically significant improvements.",needs_review
3973,paper_255,The Substitution Effect of Mobile Games on Console Games: An Empirical Analysis of the Japanese Video Game Industry,2017,mobile games,not_reported,"panel data of about 100,000 observations (Japanese video game industry)",quasi_experimental,"substitution effect of mobile game play on console game use (3DS, Wii, PSP)",measured,negative,at most about 0.1,not_reported,quasi_experimental,0.1687,"The results showed that the substitution effects of playing smart devices on 3DS, Wii, and PSP were recognizable, but did not have significant effects on PS3, and the substitution effects on PSP were very small. In a...",needs_review
4941,paper_296,Open Access Game-based learning and gamification in initial teacher training in the social sciences: an experiment with MinecraftEdu,2012,MinecraftEdu,Exploration,second-year university students who are pursuing a degree in Primary Education and are enrolled in a subject entitled Social Sciences II: History and Teaching at Castilla-La Mancha University.,quasi_experimental,educational innovation,learning/innovation,positive,not_reported,not_reported,quasi_experimental,0.1687,"Interest level, educational innovation and motivation are valued positively and show statistically significant improvements.",needs_review
4946,paper_296,Open Access Game-based learning and gamification in initial teacher training in the social sciences: an experiment with MinecraftEdu,2012,MinecraftEdu,Perspective Taking,second-year university students who are pursuing a degree in Primary Education and are enrolled in a subject entitled Social Sciences II: History and Teaching at Castilla-La Mancha University.,quasi_experimental,motivation,engagement/motivation,positive,not_reported,not_reported,quasi_experimental,0.1687,"Interest level, educational innovation and motivation are valued positively and show statistically significant improvements.",needs_review
4966,paper_296,Open Access Game-based learning and gamification in initial teacher training in the social sciences: an experiment with MinecraftEdu,2012,Minecraft,Perspective Taking,second-year university students who are pursuing a degree in Primary Education and are enrolled in a subject entitled Social Sciences II: History and Teaching at Castilla-La Mancha University.,quasi_experimental,motivation,engagement/motivation,positive,not_reported,not_reported,quasi_experimental,0.1687,"Interest level, educational innovation and motivation are valued positively and show statistically significant improvements.",needs_review
4965,paper_296,Open Access Game-based learning and gamification in initial teacher training in the social sciences: an experiment with MinecraftEdu,2012,Minecraft,Exploration,second-year university students who are pursuing a degree in Primary Education and are enrolled in a subject entitled Social Sciences II: History and Teaching at Castilla-La Mancha University.,quasi_experimental,motivation,engagement/motivation,positive,not_reported,not_reported,quasi_experimental,0.1687,"Interest level, educational innovation and motivation are valued positively and show statistically significant improvements.",needs_review
4964,paper_296,Open Access Game-based learning and gamification in initial teacher training in the social sciences: an experiment with MinecraftEdu,2012,Minecraft,Building,second-year university students who are pursuing a degree in Primary Education and are enrolled in a subject entitled Social Sciences II: History and Teaching at Castilla-La Mancha University.,quasi_experimental,motivation,engagement/motivation,positive,not_reported,not_reported,quasi_experimental,0.1687,"Interest level, educational innovation and motivation are valued positively and show statistically significant improvements.",needs_review
4963,paper_296,Open Access Game-based learning and gamification in initial teacher training in the social sciences: an experiment with MinecraftEdu,2012,Minecraft,Cooperative Play,second-year university students who are pursuing a degree in Primary Education and are enrolled in a subject entitled Social Sciences II: History and Teaching at Castilla-La Mancha University.,quasi_experimental,motivation,engagement/motivation,positive,not_reported,not_reported,quasi_experimental,0.1687,"Interest level, educational innovation and motivation are valued positively and show statistically significant improvements.",needs_review
4942,paper_296,Open Access Game-based learning and gamification in initial teacher training in the social sciences: an experiment with MinecraftEdu,2012,MinecraftEdu,Perspective Taking,second-year university students who are pursuing a degree in Primary Education and are enrolled in a subject entitled Social Sciences II: History and Teaching at Castilla-La Mancha University.,quasi_experimental,educational innovation,learning/innovation,positive,not_reported,not_reported,quasi_experimental,0.1687,"Interest level, educational innovation and motivation are valued positively and show statistically significant improvements.",needs_review
4961,paper_296,Open Access Game-based learning and gamification in initial teacher training in the social sciences: an experiment with MinecraftEdu,2012,Minecraft,Exploration,second-year university students who are pursuing a degree in Primary Education and are enrolled in a subject entitled Social Sciences II: History and Teaching at Castilla-La Mancha University.,quasi_experimental,educational innovation,learning/innovation,positive,not_reported,not_reported,quasi_experimental,0.1687,"Interest level, educational innovation and motivation are valued positively and show statistically significant improvements.",needs_review

In [28]:
answer = llm_synthesize(
    "What does the evidence say about technological or economic impacts of games and game platforms?",
    tech_econ,
    max_rows=25,
)

print(answer)

Supported findings
- Economic (substitution) effects — paper_255: Analysis of ~100,000 panel observations in the Japanese video‑game market found that play on smart devices/mobile games produced recognizable negative substitution effects on handheld/older consoles (3DS, Wii, PSP) but not on PS3; the substitution magnitudes were small (at most about 0.1). (paper_255)
- Technological/affordance effects — paper_080: In a quasi‑experimental study (N=190) of a serious game virtual environment, higher perceived contingency (an interactivity affordance) was associated with greater self‑efficacy. (paper_080)
- Technological/educational uptake — paper_296: Use of MinecraftEdu in initial teacher training was associated with increased interest, educational innovation and motivation (statistically significant improvements reported). (paper_296)

Caveats
- Most entries are quasi‑experimental; randomized details and inferential statistics (effect sizes, p‑values) are generally not reported in these rows. (paper_255, paper_080, paper_296)
- The economic substitution effect is small (≤~0.1) and not uniform across platforms (no significant effect on PS3; PSP effects described as very small). Context limited to the Japanese industry. (paper_255)
- Technological/educational findings come from specific samples (N=190; second‑year teacher‑training students) and may not generalize broadly; formal effect sizes and p‑values are not provided here. (paper_080, paper_296)

In [29]:
monetization = supported(df)

monetization = monetization[
    monetization[["paper_title", "outcome_canonical", "outcome_raw", "source_quote"]]
    .astype(str)
    .agg(" ".join, axis=1)
    .str.contains(
        "purchase|intention|microtransaction|freemium|subscription|revenue|sales|monetization|loot box|consumer|brand|loyalty|business model|market",
        case=False,
        na=False,
        regex=True,
    )
]

monetization = monetization[
    [col for col in ANSWER_COLS if col in monetization.columns]
].sort_values("edge_weight", ascending=False)

display(summarize_counts(monetization))
display(monetization.head(50))

   rows  papers  games  mechanics  outcomes  positive  negative  mixed  null
0   162      23     20          4        56       115        26     15     0

,paper_id,paper_title,year,game_name,mechanic_name,population_raw,study_design,outcome_canonical,outcome_category,effect_direction,effect_size_raw,p_value,evidence_strength,edge_weight,source_quote,review_status
2521,paper_145,"To screen, or not to screen: An experimental comparison of two methods for correlating video game loot box expenditure and problem gambling severity",2024,loot boxes,not_reported,N = 2027; non-screening approach; n = 1005; screening participants; n = 1022,randomized_controlled_trial,Loot box expenditure correlated with problem gambling severity (PGSI),game_level,positive,not_reported,not_reported,randomized_controlled_trial,0.2250,Results showed positive correlations between loot box spending and problem gambling across both experimental conditions.,needs_review
2522,paper_145,"To screen, or not to screen: An experimental comparison of two methods for correlating video game loot box expenditure and problem gambling severity",2024,loot boxes,not_reported,N = 2027; non-screening approach; n = 1005; screening participants; n = 1022,randomized_controlled_trial,Past-year gambling participation (binary) positively correlated with loot box expenditure (in screening group),game_level,positive,not_reported,not_reported,randomized_controlled_trial,0.2250,"In addition, a predicted positive correlation emerged between binary past-year gambling participation and loot box expenditure in the screening group.",needs_review
2523,paper_145,"To screen, or not to screen: An experimental comparison of two methods for correlating video game loot box expenditure and problem gambling severity",2024,loot boxes,not_reported,N = 2027; non-screening approach; n = 1005; screening participants; n = 1022,randomized_controlled_trial,Problem gambling severity (PGSI) scores were inflated in the non-screening group relative to the screening group,interpreted_construct,positive,not_reported,not_reported,randomized_controlled_trial,0.2250,"However, problem gambling severity was inflated in the non-screening group, meaning that future research on gambling-like products should include gambling participation screening questions; better define what ‘gambli...",needs_review
2524,paper_145,"To screen, or not to screen: An experimental comparison of two methods for correlating video game loot box expenditure and problem gambling severity",2024,loot boxes,not_reported,N = 2027; non-screening approach; n = 1005; screening participants; n = 1022,randomized_controlled_trial,Loot box expenditure correlated with problem gambling severity (PGSI),game_level,positive,not_reported,not_reported,randomized_controlled_trial,0.2250,Results showed positive correlations between loot box spending and problem gambling across both experimental conditions.,needs_review
2525,paper_145,"To screen, or not to screen: An experimental comparison of two methods for correlating video game loot box expenditure and problem gambling severity",2024,loot boxes,not_reported,N = 2027; non-screening approach; n = 1005; screening participants; n = 1022,randomized_controlled_trial,Past-year gambling participation (binary) positively correlated with loot box expenditure (in screening group),game_level,positive,not_reported,not_reported,randomized_controlled_trial,0.2250,"In addition, a predicted positive correlation emerged between binary past-year gambling participation and loot box expenditure in the screening group.",needs_review
2526,paper_145,"To screen, or not to screen: An experimental comparison of two methods for correlating video game loot box expenditure and problem gambling severity",2024,loot boxes,not_reported,N = 2027; non-screening approach; n = 1005; screening participants; n = 1022,randomized_controlled_trial,Problem gambling severity (PGSI) scores were inflated in the non-screening group relative to the screening group,interpreted_construct,positive,not_reported,not_reported,randomized_controlled_trial,0.2250,"However, problem gambling severity was inflated in the non-screening group, meaning that future research on gambling-like products should include gambling participation screening questions; better define what ‘gambli...",needs_review
1617,paper_076,Effectiveness of digital games in producing environmentally friendly attitudes and behaviors: A mixed methods study,2021,EnerCities,not_reported,This study was conducted among undergraduate students enrolled in an educational technology course.,quasi_experimental,attitudinal learning; behavioral learning / behavioral intentions,Psychological,positive,NaN,NaN,quasi_experimental,0.1012,Quantitative data analysis using PLS-SEM showed that EnerCities was effective in producing attitudinal and behavioral changes that were retained until one week of game play.,needs_review
1621,paper_076,Effectiveness of digital games in producing environmentally friendly attitudes and behaviors: A mixed methods study,2021,unnamed Science surgery game,not_reported,This study was conducted among undergraduate students enrolled in an educational technology course.,quasi_experimental,attitudinal learning; behavioral learning / behavioral intentions,Psychological,positive,NaN,NaN,quasi_experimental,0.1012,Quantitative data analysis using PLS-SEM showed that EnerCities was effective in producing attitudinal and behavioral changes that were retained until one week of game play.,needs_review
2551,paper_147,Theory of consumption value: A lens to examine the use and continual use intention of online game subscription services,2024,Microsoft’s Xbox Game Pass,not_reported,an empirical analysis of 412 subscribers’ and 265 non-subscribers’ views at the online game subscription service level,correlational,Fear of missing out (interactive aspect) contribution to perceived values,Psychological,positive,not_reported,not_reported,correlational,0.0788,FoMO’s (interactive aspect) contribution to value is more evident among non-subscribers than subscribers.,needs_review
2546,paper_147,Theory of consumption value: A lens to examine the use and continual use intention of online game subscription services,2024,Microsoft’s Xbox Game Pass,not_reported,an empirical analysis of 412 subscribers’ and 265 non-subscribers’ views at the online game subscription service level,correlational,Continual use intention (subscription service),Behavioral,positive,not_reported,not_reported,correlational,0.0788,"Three value types (playing games, enjoyment, and price) contribute to the use (continual use) intention.",needs_review
2547,paper_147,Theory of consumption value: A lens to examine the use and continual use intention of online game subscription services,2024,Microsoft’s Xbox Game Pass,not_reported,an empirical analysis of 412 subscribers’ and 265 non-subscribers’ views at the online game subscription service level,correlational,Perceived playing-games value,Psychological,positive,not_reported,not_reported,correlational,0.0788,"Three value types (playing games, enjoyment, and price) contribute to the use (continual use) intention.",needs_review
2548,paper_147,Theory of consumption value: A lens to examine the use and continual use intention of online game subscription services,2024,Microsoft’s Xbox Game Pass,not_reported,an empirical analysis of 412 subscribers’ and 265 non-subscribers’ views at the online game subscription service level,correlational,Perceived enjoyment value,Psychological,positive,not_reported,not_reported,correlational,0.0788,"Three value types (playing games, enjoyment, and price) contribute to the use (continual use) intention.",needs_review
2549,paper_147,Theory of consumption value: A lens to examine the use and continual use intention of online game subscription services,2024,Microsoft’s Xbox Game Pass,not_reported,an empirical analysis of 412 subscribers’ and 265 non-subscribers’ views at the online game subscription service level,correlational,Perceived price value,Psychological,positive,not_reported,not_reported,correlational,0.0788,"Three value types (playing games, enjoyment, and price) contribute to the use (continual use) intention.",needs_review
2550,paper_147,Theory of consumption value: A lens to examine the use and continual use intention of online game subscription services,2024,Microsoft’s Xbox Game Pass,not_reported,an empirical analysis of 412 subscribers’ and 265 non-subscribers’ views at the online game subscription service level,correlational,Variety preference contribution to perceived values,Psychological,positive,not_reported,not_reported,correlational,0.0788,"For both subscribers and non-subscribers, variety preference positively contributes to numerous value types.",needs_review
2555,paper_147,Theory of consumption value: A lens to examine the use and continual use intention of online game subscription services,2024,Game Pass,not_reported,an empirical analysis of 412 subscribers’ and 265 non-subscribers’ views at the online game subscription service level,correlational,Perceived enjoyment value,Psychological,positive,not_reported,not_reported,correlational,0.0788,"Three value types (playing games, enjoyment, and price) contribute to the use (continual use) intention.",needs_review
2552,paper_147,Theory of consumption value: A lens to examine the use and continual use intention of online game subscription services,2024,Microsoft’s Xbox Game Pass,not_reported,an empirical analysis of 412 subscribers’ and 265 non-subscribers’ views at the online game subscription service level,correlational,Effect of game motivations on continual use intention,Psychological,NaN,not_reported,not_reported,correlational,0.0788,an empirical analysis of 412 subscribers’ and 265 non-subscribers’ views at the online game subscription service level revealed the limited consequences of game motivations for the use (continual use) of online game ...,needs_review
2553,paper_147,Theory of consumption value: A lens to examine the use and continual use intention of online game subscription services,2024,Game Pass,not_reported,an empirical analysis of 412 subscribers’ and 265 non-subscribers’ views at the online game subscription service level,correlational,Continual use intention (subscription service),Behavioral,positive,not_reported,not_reported,correlational,0.0788,"Three value types (playing games, enjoyment, and price) contribute to the use (continual use) intention.",needs_review
2554,paper_147,Theory of consumption value: A lens to examine the use and continual use intention of online game subscription services,2024,Game Pass,not_reported,an empirical analysis of 412 subscribers’ and 265 non-subscribers’ views at the online game subscription service level,correlational,Perceived playing-games value,Psychological,positive,not_reported,not_reported,correlational,0.0788,"Three value types (playing games, enjoyment, and price) contribute to the use (continual use) intention.",needs_review
2544,paper_147,Theory of consumption value: A lens to examine the use and continual use intention of online game subscription services,2024,Game Pass,not_reported,an empirical analysis of 412 subscribers’ and 265 non-subscribers’ views at the online game subscription service level,correlational,Fear of missing out (interactive aspect) contribution to perceived values,Psychological,positive,not_reported,not_reported,correlational,0.0788,FoMO’s (interactive aspect) contribution to value is more evident among non-subscribers than subscribers.,needs_review
2556,paper_147,Theory of consumption value: A lens to examine the use and continual use intention of online game subscription services,2024,Game Pass,not_reported,an empirical analysis of 412 subscribers’ and 265 non-subscribers’ views at the online game subscription service level,correlational,Perceived price value,Psychological,positive,not_reported,not_reported,correlational,0.0788,"Three value types (playing games, enjoyment, and price) contribute to the use (continual use) intention.",needs_review
2557,paper_147,Theory of consumption value: A lens to examine the use and continual use intention of online game subscription services,2024,Game Pass,not_reported,an empirical analysis of 412 subscribers’ and 265 non-subscribers’ views at the online game subscription service level,correlational,Variety preference contribution to perceived values,Psychological,positive,not_reported,not_reported,correlational,0.0788,"For both subscribers and non-subscribers, variety preference positively contributes to numerous value types.",needs_review
2558,paper_147,Theory of consumption value: A lens to examine the use and continual use intention of online game subscription services,2024,Game Pass,not_reported,an empirical analysis of 412 subscribers’ and 265 non-subscribers’ views at the online game subscription service level,correlational,Fear of missing out (interactive aspect) contribution to perceived values,Psychological,positive,not_reported,not_reported,correlational,0.0788,FoMO’s (interactive aspect) contribution to value is more evident among non-subscribers than subscribers.,needs_review
2545,paper_147,Theory of consumption value: A lens to examine the use and continual use intention of online game subscription services,2024,Game Pass,not_reported,an empirical analysis of 412 subscribers’ and 265 non-subscribers’ views at the online game subscription service level,correlational,Effect of game motivations on continual use intention,Psychological,NaN,not_reported,not_reported,correlational,0.0788,an empirical analysis of 412 subscribers’ and 265 non-subscribers’ views at the online game subscription service level revealed the limited consequences of game motivations for the use (continual use) of online game ...,needs_review
547,paper_018,Changes in user experience and satisfaction as media technology evolves: The reciprocal relationship between video games and video game-related media,2022,NaN,not_reported,users (video game players / users of video game-related media),correlational,intention to play video games,intention,positive,not_reported,not_reported,correlational,0.0788,"In this study, we confirmed that attitudes toward online communities positively affect actual intentions to play video games, thus indicating that there is complementarity between video games and online communities.",needs_review
2543,paper_147,Theory of consumption value: A lens to examine the use and continual use intention of online game subscription services,2024,Game Pass,not_reported,an empirical analysis of 412 subscribers’ and 265 non-subscribers’ views at the online game subscription service level,correlational,Variety preference contribution to perceived values,Psychological,positive,not_reported,not_reported,correlational,0.0788,"For both subscribers and non-subscribers, variety preference positively contributes to numerous value types.",needs_review
1311,paper_054,"""Why pay premium in freemium services?"" A study on perceived value, continued use and purchase intentions in free-to-play games",2014,free-to-play games,not_reported,players of freemium/free-to-play games,correlational,continued use intention,behavioral,positive,not_reported,not_reported,correlational,0.0788,"Firstly, we find support for the ""Demand Through Inconvenience"" -hypothesis proposed in this study, indicating that the higher the enjoyment of the freemium service, the lower the intentions to purchase premium conte...",needs_review
1312,paper_054,"""Why pay premium in freemium services?"" A study on perceived value, continued use and purchase intentions in free-to-play games",2014,free-to-play games,not_reported,players of freemium/free-to-play games,correlational,purchase intention,economic/behavioral,mixed,not_reported,not_reported,correlational,0.0788,"Firstly, we find support for the ""Demand Through Inconvenience"" -hypothesis proposed in this study, indicating that the higher the enjoyment of the freemium service, the lower the intentions to purchase premium conte...",needs_review
551,paper_018,Changes in user experience and satisfaction as media technology evolves: The reciprocal relationship between video games and video game-related media,2022,NaN,not_reported,users (video game players / users of video game-related media),correlational,complementarity between video games and video game-related media,interpreted_construct,positive,not_reported,not_reported,correlational,0.0788,"We predict a complementary relationship between video game and video game-related media using a structural equation model reflecting joint effects between different media... In this study, we confirmed that attitudes...",needs_review
2542,paper_147,Theory of consumption value: A lens to examine the use and continual use intention of online game subscription services,2024,Game Pass,not_reported,an empirical analysis of 412 subscribers’ and 265 non-subscribers’ views at the online game subscription service level,correlational,Perceived price value,Psychological,positive,not_reported,not_reported,correlational,0.0788,"Three value types (playing games, enjoyment, and price) contribute to the use (continual use) intention.",needs_review
2541,paper_147,Theory of consumption value: A lens to examine the use and continual use intention of online game subscription services,2024,Game Pass,not_reported,an empirical analysis of 412 subscribers’ and 265 non-subscribers’ views at the online game subscription service level,correlational,Perceived enjoyment value,Psychological,positive,not_reported,not_reported,correlational,0.0788,"Three value types (playing games, enjoyment, and price) contribute to the use (continual use) intention.",needs_review
2540,paper_147,Theory of consumption value: A lens to examine the use and continual use intention of online game subscription services,2024,Game Pass,not_reported,an empirical analysis of 412 subscribers’ and 265 non-subscribers’ views at the online game subscription service level,correlational,Perceived playing-games value,Psychological,positive,not_reported,not_reported,correlational,0.0788,"Three value types (playing games, enjoyment, and price) contribute to the use (continual use) intention.",needs_review
2539,paper_147,Theory of consumption value: A lens to examine the use and continual use intention of online game subscription services,2024,Game Pass,not_reported,an empirical analysis of 412 subscribers’ and 265 non-subscribers’ views at the online game subscription service level,correlational,Continual use intention (subscription service),Behavioral,positive,not_reported,not_reported,correlational,0.0788,"Three value types (playing games, enjoyment, and price) contribute to the use (continual use) intention.",needs_review
2538,paper_147,Theory of consumption value: A lens to examine the use and continual use intention of online game subscription services,2024,Microsoft’s Xbox Game Pass,not_reported,an empirical analysis of 412 subscribers’ and 265 non-subscribers’ views at the online game subscription service level,correlational,Effect of game motivations on continual use intention,Psychological,NaN,not_reported,not_reported,correlational,0.0788,an empirical analysis of 412 subscribers’ and 265 non-subscribers’ views at the online game subscription service level revealed the limited consequences of game motivations for the use (continual use) of online game ...,needs_review
2537,paper_147,Theory of consumption value: A lens to examine the use and continual use intention of online game subscription services,2024,Microsoft’s Xbox Game Pass,not_reported,an empirical analysis of 412 subscribers’ and 265 non-subscribers’ views at the online game subscription service level,correlational,Fear of missing out (interactive aspect) contribution to perceived values,Psychological,positive,not_reported,not_reported,correlational,0.0788,FoMO’s (interactive aspect) contribution to value is more evident among non-subscribers than subscribers.,needs_review

In [30]:
answer = llm_synthesize(
    "What evidence links game design, monetization, or platforms to economic outcomes?",
    monetization,
    max_rows=25,
)

print(answer)

Supported findings
- Loot box monetization: Higher loot box expenditure is positively associated with problem gambling severity across both experimental conditions (paper_145). The same dataset also found past‑year gambling participation (binary) positively correlated with loot box spending in the screening group (paper_145).
- Subscription platform (Xbox Game Pass / Game Pass): Perceived value factors (playing-games value, enjoyment, and price) positively contribute to continual use intention for the subscription service; variety preference and FoMO also positively contribute to perceived value (paper_147).

Caveats
- Effect sizes, p-values, and detailed statistics are not reported in these rows (paper_145, paper_147).
- Loot box findings note measurement sensitivity: PGSI scores were inflated in the non‑screening group, indicating screening/definition issues that may affect estimates (paper_145).
- Game Pass evidence is correlational and based on self‑reported perceived values and intentions (not observed revenue or retention), limiting causal inference (paper_147).

In [31]:
health_terms = (
    "physiological|health|physical activity|exercise|energy expenditure|MET|heart rate|"
    "balance|motor|mobility|oxygen|ventilation|postural|fitness|BMI|body composition|"
    "rehabilitation|Parkinson|multiple sclerosis|cystic fibrosis|cancer|stroke|older adults|"
    "scoliosis|traumatic brain injury|pain|anxiety|sleep"
)

health = supported(df)

health = health[
    health[["paper_title", "population_raw", "outcome_category", "outcome_canonical", "outcome_raw", "measurement_raw", "source_quote"]]
    .astype(str)
    .agg(" ".join, axis=1)
    .str.contains(health_terms, case=False, na=False, regex=True)
]

health = health[
    [col for col in ANSWER_COLS if col in health.columns]
].sort_values("edge_weight", ascending=False)

display(summarize_counts(health))
display(health.head(75))

   rows  papers  games  mechanics  outcomes  positive  negative  mixed  null
0  1634     106    169         32       304       947       154     65     0

,paper_id,paper_title,year,game_name,mechanic_name,population_raw,study_design,outcome_canonical,outcome_category,effect_direction,effect_size_raw,p_value,evidence_strength,edge_weight,source_quote,review_status
4734,paper_286,Open Access Computer game-based and traditional learning method: a comparison regarding students’ knowledge retention,2013,NaN,not_reported,Speech-Language and Hearing pathology undergraduate students.,randomized_controlled_trial,long-term Physiology knowledge (6 months post-test),Knowledge retention,negative,not_reported,not_reported,randomized_controlled_trial,0.225,Students that received the traditional lecture performed better in both post-test and long-term post-test when considering the Anatomy and Physiology questions.,needs_review
4732,paper_286,Open Access Computer game-based and traditional learning method: a comparison regarding students’ knowledge retention,2013,NaN,not_reported,Speech-Language and Hearing pathology undergraduate students.,randomized_controlled_trial,short-term Physiology knowledge (post-test),Knowledge retention,negative,not_reported,not_reported,randomized_controlled_trial,0.225,Students that received the traditional lecture performed better in both post-test and long-term post-test when considering the Anatomy and Physiology questions.,needs_review
4751,paper_287,Page 1 of 5 (page number not for citation purposes),2008,NaN,not_reported,Twenty children (mean ± SD age = 12 ± 1.5 years; 40% female) were randomised to receive either an active video game upgrade package or to a control group (no intervention).,randomized_controlled_trial,physical activity (accelerometer counts/min) at 6 weeks,physical_activity_objective,positive,difference at 6 weeks = 194 counts/min,0.04,randomized_controlled_trial,0.225,"Average time spent in all physical activities measured with an accelerometer was higher in the active video game intervention group compared to the control group (difference at 6 weeks = 194 counts/min, p = 0.04...",needs_review
4749,paper_287,Page 1 of 5 (page number not for citation purposes),2008,PlayStation®2,not_reported,Twenty children (mean ± SD age = 12 ± 1.5 years; 40% female) were randomised to receive either an active video game upgrade package or to a control group (no intervention).,randomized_controlled_trial,physical activity (accelerometer counts/min) at 12 weeks,physical_activity_objective,NaN,difference at 12 weeks = 48 counts/min,0.06,randomized_controlled_trial,0.225,"...and at 12 weeks = 48 counts/min, p = 0.06).",needs_review
4748,paper_287,Page 1 of 5 (page number not for citation purposes),2008,PlayStation®2,not_reported,Twenty children (mean ± SD age = 12 ± 1.5 years; 40% female) were randomised to receive either an active video game upgrade package or to a control group (no intervention).,randomized_controlled_trial,physical activity (accelerometer counts/min) at 6 weeks,physical_activity_objective,positive,difference at 6 weeks = 194 counts/min,0.04,randomized_controlled_trial,0.225,"Average time spent in all physical activities measured with an accelerometer was higher in the active video game intervention group compared to the control group (difference at 6 weeks = 194 counts/min, p = 0.04...",needs_review
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,X-Box 360 Kinect,Gesture Input,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,randomized_controlled_trial,Community Balance and Mobility Scale (CB&M),Balance/Mobility,positive,not_reported,not_reported,randomized_controlled_trial,0.225,"Both groups improved in CB&M scores, but only the VGT group increased on the UBS and TUG with a between-group significance (p < 0.05). Selective attention improved significantly in the VGT group (p < 0.01).",needs_review
3347,paper_196,Use of commercial video games to improve postural balance in patients with multiple sclerosis: A systematic review and meta-analysis of randomised controlled clinical trials,2021,NaN,not_reported,patients with multiple sclerosis (MS),randomized_controlled_trial,clinical_significance_relative_to_minimum_detectable_change,postural_balance_interpretation,NaN,not greater than the minimum detectable change reported in the literature,not_reported,randomized_controlled_trial,0.225,but these were not greater than the minimum detectable change reported in the literature.,needs_review
3346,paper_196,Use of commercial video games to improve postural balance in patients with multiple sclerosis: A systematic review and meta-analysis of randomised controlled clinical trials,2021,NaN,not_reported,patients with multiple sclerosis (MS),randomized_controlled_trial,Berg Balance Scale (BBS),postural_balance,positive,DM: 5.30,< .001,randomized_controlled_trial,0.225,"We did observe intergroup differences in BBS scores in favour of video game therapy (DM: 5.30; 95% CI,3.39—7.21; P < .001; I2 = 0%), but these were not greater than the minimum detectable change reported in the liter...",needs_review
3345,paper_196,Use of commercial video games to improve postural balance in patients with multiple sclerosis: A systematic review and meta-analysis of randomised controlled clinical trials,2021,NaN,not_reported,patients with multiple sclerosis (MS),randomized_controlled_trial,Timed 25-Foot Walk,postural_balance,NaN,DM: .15,.75,randomized_controlled_trial,0.225,"We found no signiﬁcant differences between the video game therapy group and the control group in ... Timed 25-Foot Walk scores (DM: .15; 95% CI, −1.06 to .76; P = .75; I2 = 0%)",needs_review
3344,paper_196,Use of commercial video games to improve postural balance in patients with multiple sclerosis: A systematic review and meta-analysis of randomised controlled clinical trials,2021,NaN,not_reported,patients with multiple sclerosis (MS),randomized_controlled_trial,Four Step Square Test,postural_balance,NaN,DM: −.74,.48,randomized_controlled_trial,0.225,"We found no signiﬁcant differences between the video game therapy group and the control group in Four Step Square Test (DM: −.74; 95% CI, −2.79 to 1.32; P = .48; I2 = 0%)",needs_review

In [33]:
impact_patterns = {
    "energy_expenditure_activity": "energy expenditure|MET|physical activity|activity counts|exercise intensity|moderate-to-vigorous|MVPA",
    "cardiorespiratory": "heart rate|oxygen|SpO2|ventilation|VO2|cardiorespiratory|aerobic",
    "balance_motor_rehab": "balance|postural|motor|mobility|rehabilitation|Parkinson|stroke|traumatic brain injury|scoliosis",
    "body_composition_fitness": "BMI|body composition|weight|fitness|aerobic fitness|excess weight|obesity",
    "pain_anxiety_clinical": "pain|anxiety|procedural|cancer|cystic fibrosis|multiple sclerosis|clinical",
    "sleep_fatigue": "sleep|fatigue",
}

health_impact_rows = []

for impact, pattern in impact_patterns.items():
    subset = health[
        health[["paper_title", "population_raw", "outcome_category", "outcome_canonical",  "source_quote"]]
        .astype(str)
        .agg(" ".join, axis=1)
        .str.contains(pattern, case=False, na=False, regex=True)
    ]
    
    health_impact_rows.append({
        "impact_area": impact,
        "rows": len(subset),
        "papers": subset["paper_id"].nunique(),
        "positive": int((subset["effect_direction"] == "positive").sum()),
        "negative": int((subset["effect_direction"] == "negative").sum()),
        "mixed": int((subset["effect_direction"] == "mixed").sum()),
        "null": int((subset["effect_direction"] == "null").sum()),
        "top_games": ", ".join(subset["game_name"].dropna().value_counts().head(5).index.astype(str)),
        "top_outcomes": ", ".join(subset["outcome_canonical"].dropna().value_counts().head(5).index.astype(str)),
    })

health_impact_summary = pd.DataFrame(health_impact_rows).sort_values("papers", ascending=False)
display(health_impact_summary)

,impact_area,rows,papers,positive,negative,mixed,null,top_games,top_outcomes
0,energy_expenditure_activity,758,43,417,64,0,0,"custom-made action video game, Wii boxing, Wii Fit Plus, virtual reality, Your Shape Fitness Evolved (Tai Chi)","perceived exertion (RPE Borg scale), activity counts (accelerometer-derived), energy expenditure (METs; kJ/min), correlation(energy expenditure/activity counts, balance status), information processing (overall)"
4,pain_anxiety_clinical,151,18,61,60,0,0,"virtual reality, conventional video game, distracting games, interactive audiovisual game, preparatory games","anxiety, procedural pain, acceptability/satisfaction, adverse effects, need for physical restraint during procedure"
2,balance_motor_rehab,306,17,187,26,1,0,"League of Legends, Kinect Sports, Kinect Adventures, X-Box 360 Kinect, Counter-Strike","correlation(energy expenditure/activity counts, balance status), reaction time (motor response speed), cancellation ability (stop-signal process), FPS viewing increases Fraction of Time of sensorimotor-related CAPs r..."
1,cardiorespiratory,218,11,98,23,37,0,"Wii Fit Plus, Kinect, first-person shooter, Wii Fit, EA SPORTS™ACTIVE","heart rate (HR), minute ventilation (VE), peak HR, VO2, VE (CPET), oxygen consumption (VO2), dyspnea"
3,body_composition_fitness,215,6,67,16,22,0,"Kinect, Wii Fit Plus, EA SPORTS™ACTIVE, Microsoft Xbox, Internet video games","energy cost (between-group comparison), minute ventilation (VE), dyspnea, oxygen uptake (VO2), Wii-Acti and Wii-Train impose metabolic demand comparable to 6MWT"
5,sleep_fatigue,40,4,12,24,0,0,"Nintendo Wii, Nintendo WiiFit™, World of Warcraft, MMORPG","daytime functioning, Irritability, sleep disturbance and mood changes (self-reported), sleep onset latency (delay), sleep continuity / stability / organization, sleep quality"

In [35]:
def show_health_impact(impact_area: str, n: int = 30):
    pattern = impact_patterns[impact_area]
    subset = health[
        health[["paper_title", "population_raw", "outcome_category", "outcome_canonical", "source_quote"]]
        .astype(str)
        .agg(" ".join, axis=1)
        .str.contains(pattern, case=False, na=False, regex=True)
    ]
    subset = subset.sort_values("edge_weight", ascending=False)
    display(summarize_counts(subset))
    display(subset.head(n))
    return subset

balance_rehab = show_health_impact("balance_motor_rehab")

   rows  papers  games  mechanics  outcomes  positive  negative  mixed  null
0   306      17     54         32        45       187        26      1     0

,paper_id,paper_title,year,game_name,mechanic_name,population_raw,study_design,outcome_canonical,outcome_category,effect_direction,effect_size_raw,p_value,evidence_strength,edge_weight,source_quote,review_status
4041,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,Biodex balance platform,not_reported,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,randomized_controlled_trial,Unified Balance Scale (UBS),Balance/Mobility,positive,not_reported,<0.05,randomized_controlled_trial,0.225,"Both groups improved in CB&M scores, but only the VGT group increased on the UBS and TUG with a between-group significance (p < 0.05).",needs_review
3999,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,X-Box 360 Kinect,Sports Simulation,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,randomized_controlled_trial,Unified Balance Scale (UBS),Balance/Mobility,positive,not_reported,<0.05,randomized_controlled_trial,0.225,"Both groups improved in CB&M scores, but only the VGT group increased on the UBS and TUG with a between-group significance (p < 0.05).",needs_review
4038,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,Kinect Sports,Sports Simulation,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,randomized_controlled_trial,Selective visual attention (Go/No-go task),Attention / Neurocognitive,positive,not_reported,<0.01,randomized_controlled_trial,0.225,Selective attention improved significantly in the VGT group (p < 0.01).,needs_review
4037,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,Kinect Sports,Gesture Input,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,randomized_controlled_trial,Selective visual attention (Go/No-go task),Attention / Neurocognitive,positive,not_reported,<0.01,randomized_controlled_trial,0.225,Selective attention improved significantly in the VGT group (p < 0.01).,needs_review
4033,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,Kinect Sports,Movement Control,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,randomized_controlled_trial,Timed Up and Go (TUG),Mobility/Functional mobility,positive,not_reported,<0.05,randomized_controlled_trial,0.225,"Both groups improved in CB&M scores, but only the VGT group increased on the UBS and TUG with a between-group significance (p < 0.05).",needs_review
4032,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,Kinect Sports,Sports Simulation,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,randomized_controlled_trial,Timed Up and Go (TUG),Mobility/Functional mobility,positive,not_reported,<0.05,randomized_controlled_trial,0.225,"Both groups improved in CB&M scores, but only the VGT group increased on the UBS and TUG with a between-group significance (p < 0.05).",needs_review
4031,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,Kinect Sports,Gesture Input,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,randomized_controlled_trial,Timed Up and Go (TUG),Mobility/Functional mobility,positive,not_reported,<0.05,randomized_controlled_trial,0.225,"Both groups improved in CB&M scores, but only the VGT group increased on the UBS and TUG with a between-group significance (p < 0.05).",needs_review
4030,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,Kinect Sports,Movement Control,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,randomized_controlled_trial,Unified Balance Scale (UBS),Balance/Mobility,positive,not_reported,<0.05,randomized_controlled_trial,0.225,"Both groups improved in CB&M scores, but only the VGT group increased on the UBS and TUG with a between-group significance (p < 0.05).",needs_review
4029,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,Kinect Sports,Sports Simulation,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,randomized_controlled_trial,Unified Balance Scale (UBS),Balance/Mobility,positive,not_reported,<0.05,randomized_controlled_trial,0.225,"Both groups improved in CB&M scores, but only the VGT group increased on the UBS and TUG with a between-group significance (p < 0.05).",needs_review
4028,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,Kinect Sports,Gesture Input,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,randomized_controlled_trial,Unified Balance Scale (UBS),Balance/Mobility,positive,not_reported,<0.05,randomized_controlled_trial,0.225,"Both groups improved in CB&M scores, but only the VGT group increased on the UBS and TUG with a between-group significance (p < 0.05).",needs_review
4027,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,Kinect Sports,Movement Control,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,randomized_controlled_trial,Community Balance and Mobility Scale (CB&M),Balance/Mobility,positive,not_reported,not_reported,randomized_controlled_trial,0.225,"Both groups improved in CB&M scores, but only the VGT group increased on the UBS and TUG with a between-group significance (p < 0.05). Selective attention improved significantly in the VGT group (p < 0.01).",needs_review
4026,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,Kinect Sports,Sports Simulation,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,randomized_controlled_trial,Community Balance and Mobility Scale (CB&M),Balance/Mobility,positive,not_reported,not_reported,randomized_controlled_trial,0.225,"Both groups improved in CB&M scores, but only the VGT group increased on the UBS and TUG with a between-group significance (p < 0.05). Selective attention improved significantly in the VGT group (p < 0.01).",needs_review
4025,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,Kinect Sports,Gesture Input,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,randomized_controlled_trial,Community Balance and Mobility Scale (CB&M),Balance/Mobility,positive,not_reported,not_reported,randomized_controlled_trial,0.225,"Both groups improved in CB&M scores, but only the VGT group increased on the UBS and TUG with a between-group significance (p < 0.05). Selective attention improved significantly in the VGT group (p < 0.01).",needs_review
4024,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,Kinect Adventures,Movement Control,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,randomized_controlled_trial,Selective visual attention (Go/No-go task),Attention / Neurocognitive,positive,not_reported,<0.01,randomized_controlled_trial,0.225,Selective attention improved significantly in the VGT group (p < 0.01).,needs_review
4022,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,Kinect Adventures,Gesture Input,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,randomized_controlled_trial,Selective visual attention (Go/No-go task),Attention / Neurocognitive,positive,not_reported,<0.01,randomized_controlled_trial,0.225,Selective attention improved significantly in the VGT group (p < 0.01).,needs_review
4018,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,Kinect Adventures,Movement Control,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,randomized_controlled_trial,Timed Up and Go (TUG),Mobility/Functional mobility,positive,not_reported,<0.05,randomized_controlled_trial,0.225,"Both groups improved in CB&M scores, but only the VGT group increased on the UBS and TUG with a between-group significance (p < 0.05).",needs_review
4017,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,Kinect Adventures,Sports Simulation,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,randomized_controlled_trial,Timed Up and Go (TUG),Mobility/Functional mobility,positive,not_reported,<0.05,randomized_controlled_trial,0.225,"Both groups improved in CB&M scores, but only the VGT group increased on the UBS and TUG with a between-group significance (p < 0.05).",needs_review
4016,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,Kinect Adventures,Gesture Input,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,randomized_controlled_trial,Timed Up and Go (TUG),Mobility/Functional mobility,positive,not_reported,<0.05,randomized_controlled_trial,0.225,"Both groups improved in CB&M scores, but only the VGT group increased on the UBS and TUG with a between-group significance (p < 0.05).",needs_review
4015,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,Kinect Adventures,Movement Control,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,randomized_controlled_trial,Unified Balance Scale (UBS),Balance/Mobility,positive,not_reported,<0.05,randomized_controlled_trial,0.225,"Both groups improved in CB&M scores, but only the VGT group increased on the UBS and TUG with a between-group significance (p < 0.05).",needs_review
4014,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,Kinect Adventures,Sports Simulation,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,randomized_controlled_trial,Unified Balance Scale (UBS),Balance/Mobility,positive,not_reported,<0.05,randomized_controlled_trial,0.225,"Both groups improved in CB&M scores, but only the VGT group increased on the UBS and TUG with a between-group significance (p < 0.05).",needs_review
4013,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,Kinect Adventures,Gesture Input,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,randomized_controlled_trial,Unified Balance Scale (UBS),Balance/Mobility,positive,not_reported,<0.05,randomized_controlled_trial,0.225,"Both groups improved in CB&M scores, but only the VGT group increased on the UBS and TUG with a between-group significance (p < 0.05).",needs_review
4012,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,Kinect Adventures,Movement Control,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,randomized_controlled_trial,Community Balance and Mobility Scale (CB&M),Balance/Mobility,positive,not_reported,not_reported,randomized_controlled_trial,0.225,"Both groups improved in CB&M scores, but only the VGT group increased on the UBS and TUG with a between-group significance (p < 0.05). Selective attention improved significantly in the VGT group (p < 0.01).",needs_review
4011,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,Kinect Adventures,Sports Simulation,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,randomized_controlled_trial,Community Balance and Mobility Scale (CB&M),Balance/Mobility,positive,not_reported,not_reported,randomized_controlled_trial,0.225,"Both groups improved in CB&M scores, but only the VGT group increased on the UBS and TUG with a between-group significance (p < 0.05). Selective attention improved significantly in the VGT group (p < 0.01).",needs_review
4010,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,Kinect Adventures,Gesture Input,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,randomized_controlled_trial,Community Balance and Mobility Scale (CB&M),Balance/Mobility,positive,not_reported,not_reported,randomized_controlled_trial,0.225,"Both groups improved in CB&M scores, but only the VGT group increased on the UBS and TUG with a between-group significance (p < 0.05). Selective attention improved significantly in the VGT group (p < 0.01).",needs_review
4009,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,X-Box 360 Kinect,Movement Control,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,randomized_controlled_trial,Selective visual attention (Go/No-go task),Attention / Neurocognitive,positive,not_reported,<0.01,randomized_controlled_trial,0.225,Selective attention improved significantly in the VGT group (p < 0.01).,needs_review
4008,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,X-Box 360 Kinect,Sports Simulation,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,randomized_controlled_trial,Selective visual attention (Go/No-go task),Attention / Neurocognitive,positive,not_reported,<0.01,randomized_controlled_trial,0.225,Selective attention improved significantly in the VGT group (p < 0.01).,needs_review
4007,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,X-Box 360 Kinect,Gesture Input,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,randomized_controlled_trial,Selective visual attention (Go/No-go task),Attention / Neurocognitive,positive,not_reported,<0.01,randomized_controlled_trial,0.225,Selective attention improved significantly in the VGT group (p < 0.01).,needs_review
4003,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,X-Box 360 Kinect,Movement Control,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,randomized_controlled_trial,Timed Up and Go (TUG),Mobility/Functional mobility,positive,not_reported,<0.05,randomized_controlled_trial,0.225,"Both groups improved in CB&M scores, but only the VGT group increased on the UBS and TUG with a between-group significance (p < 0.05).",needs_review
4002,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,X-Box 360 Kinect,Sports Simulation,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,randomized_controlled_trial,Timed Up and Go (TUG),Mobility/Functional mobility,positive,not_reported,<0.05,randomized_controlled_trial,0.225,"Both groups improved in CB&M scores, but only the VGT group increased on the UBS and TUG with a between-group significance (p < 0.05).",needs_review
4001,paper_257,Open Access The effects of video game therapy on balance and attention in chronic ambulatory traumatic brain injury: an exploratory study,2013,X-Box 360 Kinect,Gesture Input,We enrolled chronic traumatic brain injury patients (n = 21) that randomly received VGT or BPT for 3 sessions per week for 6 weeks.,randomized_controlled_trial,Timed Up and Go (TUG),Mobility/Functional mobility,positive,not_reported,<0.05,randomized_controlled_trial,0.225,"Both groups improved in CB&M scores, but only the VGT group increased on the UBS and TUG with a between-group significance (p < 0.05).",needs_review

In [36]:
answer = llm_synthesize(
    "What physiological and health impacts of games are supported by the evidence? Organize the answer by impact area.",
    health,
    max_rows=35,
)

print(answer)

Supported findings

- Physical activity (objective)
  - Active (motion/“exergame”) play increased accelerometer-measured activity at 6 weeks in children: difference = +194 counts/min, p = 0.04 (paper_287).
  - That effect attenuated by 12 weeks (difference = +48 counts/min, p = 0.06) (paper_287).

- Body composition / BMI
  - In overweight/obese children, an EyeToy exergame intervention produced small but statistically significant reductions at 24 weeks: BMI difference ≈ −0.33 (SE 0.12), p = 0.01; percent body fat difference ≈ −0.83 (SE 0.36), p = 0.02. Aerobic fitness partly mediated these effects (paper_288).

- Balance and mobility
  - Video-game-based therapy (VGT) improved balance/mobility measures vs comparator in chronic ambulatory traumatic brain injury: between-group improvement on Unified Balance Scale and Timed Up & Go, p < 0.05 (paper_257).

- Attention / Neurocognitive
  - Selective visual attention improved significantly after VGT (Go/No‑go task), p < 0.01 (paper_257).

- Behavioral / mental-health risk (gambling)
  - Positive correlation between loot-box expenditure and problem gambling severity across experimental conditions (paper_145).

Null or no-effect findings / caveats

- Clinical pediatric cancer population: no between-group differences for motor performance (M-ABC2, p = 0.77), fatigue (PedsQL fatigue, p = 1.00), accelerometer counts change (p = 0.22), accelerometer counts/hour (p = 0.63), MET·h/week (p = 0.38), or self-reported minutes/day (p = 0.95) for Wii/WiiFit interventions (paper_268).
- Several findings are short-term (e.g., 6 weeks) or population-specific; sample sizes vary and are small in some trials (e.g., n = 20 in paper_287), so generalizability is limited (papers_287, 257, 268, 288).
- Some outcomes showed mixed or domain-specific effects (e.g., educational knowledge retention was mixed in paper_286).

(References: paper_287, paper_288, paper_257, paper_268, paper_145, paper_286.)

In [37]:
answer = llm_synthesize(
    "What evidence links active video games or exergames to balance, motor, or rehabilitation outcomes?",
    balance_rehab,
    max_rows=25,
)

print(answer)

Supported findings (from paper_257)
- A randomized controlled trial in chronic ambulatory traumatic brain injury patients (n = 21) found that video-game therapy (VGT) produced between-group improvements versus conventional balance therapy on Unified Balance Scale (UBS) and Timed Up and Go (TUG) (p < 0.05). Games/platforms reported: X-Box 360 Kinect / Kinect Sports / Kinect Adventures / Biodex balance platform (paper_257).
- Community Balance and Mobility Scale (CB&M) scores improved in both groups; selective visual attention (Go/No‑go) improved significantly in the VGT group (p < 0.01) (paper_257).

Caveats
- Small sample (n = 21) and effect sizes not reported; many CB&M entries lack p-values (paper_257).
- Multiple games/mechanics were used (gesture/movement control, sports simulation); the specific contribution of any single game is unclear (paper_257).
- Population limited to chronic ambulatory TBI patients—generalizability to other groups is unknown (paper_257).
- Study labeled exploratory / review_status "needs_review" despite randomized controlled design (paper_257).

In [38]:
answer = llm_synthesize(
    "What video game mechanics help in balance, motor, or rehabilitation outcomes?",
    balance_rehab,
    max_rows=25,
)

print(answer)

Supported findings (all from paper_id: paper_257)
- Movement Control (Kinect Sports / Kinect Adventures / X‑Box 360 Kinect) — associated with improved balance/mobility: increases on Unified Balance Scale (UBS, between‑group p < 0.05) and faster Timed Up and Go (TUG, between‑group p < 0.05). Also linked to improved Community Balance & Mobility (CB&M) (improvement reported).
- Gesture Input (Kinect titles) — associated with improved balance/mobility (UBS, TUG) and with better selective visual attention on a Go/No‑go task (p < 0.01).
- Sports Simulation (Kinect titles / X‑Box) — associated with improved balance/mobility (UBS, TUG, CB&M) and improved selective attention (p < 0.01 reported for attention).

Caveats
- All evidence comes from one small RCT (n = 21) in chronic ambulatory traumatic brain injury (paper_257).
- Effect sizes were not reported; some outcomes (CB&M) improved in both groups, so not all improvements were uniquely attributable to video‑game therapy.
- Several entries list p‑values but lack detailed magnitude or long‑term follow‑up data.